//! The engine's constructors and its builder methods.
//!
//! Split out of `engine.rs`: the execution paths stay elsewhere, every way of
//! assembling an `ORIAEngine` lives here.

use std::path::PathBuf;
use std::sync::{Arc, Mutex};
use std::time::Duration;

use apollia_core::{EventBusSender, ORIAConfig, PendingApprovals, StepBudgetConfig};
use apollia_llm::{CompletionModel, LlmRouter};
use apollia_memory::manager::MemoryManager;
use apollia_workspace::ProjectRuntime;

use crate::actor::ToolProxyTrait;
use crate::context_manager::ContextManager;
use crate::engine::ORIAEngine;
use crate::plan_cache::PlanCacheRepository;
use crate::plan_gate::PendingPlanGates;
use crate::reasoner::Reasoner;
use crate::resilience::ResilienceLayer;

impl ORIAEngine {
    /// Create an `ORIAEngine` with default values (Mode Direct only).
    ///
    /// To enable Mode Orchestrated, chain with [`with_reasoner`].
    /// To enable HITL, chain with [`with_pending_approvals`] and [`with_task_repository`].
    ///
    /// [`with_reasoner`]: ORIAEngine::with_reasoner
    /// [`with_pending_approvals`]: ORIAEngine::with_pending_approvals
    /// [`with_task_repository`]: ORIAEngine::with_task_repository
    pub fn new() -> Self {
        let (event_bus, _) = tokio::sync::broadcast::channel(64);
        let oria_config = ORIAConfig::default();
        let context_manager = ContextManager::from_config(&oria_config);
        Self {
            reasoner: None,
            tool_proxy: None,
            llm_router: LlmRouter::empty(),
            resilience: ResilienceLayer::new(3, Duration::from_secs(30)),
            event_bus,
            runtime_config: StepBudgetConfig::default(),
            oria_config,
            db_path: None,
            pending_approvals: None,
            pending_plan_gates: None,
            plan_gate_override: None,
            task_repository: None,
            memory_manager: None,
            plan_cache: None,
            workspace_assembler: ProjectRuntime::default_project(),
            cwd: PathBuf::from("."),
            context_manager,
        }
    }
    /// Configure the `ORIAEngine` with an LLM to enable Mode Orchestrated.
    ///
    /// `max_steps` bounds the size of plans generated by the Reasoner
    /// (non-negotiable safety guardrail).
    pub fn with_reasoner(mut self, model: Arc<dyn CompletionModel>, max_steps: u32) -> Self {
        self.reasoner = Some(Reasoner::new(model, max_steps));
        self
    }
    /// Returns `true` when a [`Reasoner`] has been wired via
    /// [`with_reasoner`](Self::with_reasoner) or
    /// [`with_llm_router_and_reasoner`](Self::with_llm_router_and_reasoner).
    ///
    /// The runtime relies on this to fail orchestrated tasks with a
    /// stable `NO_LLM` code at `engine.execute()` time: without this check,
    /// orchestrated agents would fall through to NO_HANDLER because the engine
    /// was never wired with a Reasoner.
    pub fn has_reasoner(&self) -> bool {
        self.reasoner.is_some()
    }
    /// Configure the `ToolProxy` for executing orchestrated steps.
    ///
    /// Without a `ToolProxy`, steps with a `tool_hint` fail via `NoopToolProxy`.
    pub fn with_tool_proxy(mut self, proxy: Arc<dyn ToolProxyTrait>) -> Self {
        self.tool_proxy = Some(proxy);
        self
    }
    /// Configure the `LlmRouter` for LLM synthesis in orchestrated steps.
    pub fn with_llm_router(mut self, router: LlmRouter) -> Self {
        self.llm_router = router;
        self
    }
    /// Configure the LLM router and instantiate the Reasoner from the precise backend.
    ///
    /// Combines [`with_llm_router`](Self::with_llm_router) and [`with_reasoner`](Self::with_reasoner):
    /// selects `route_precise()` for orchestrated planning, then stores the router
    /// for step-level LLM calls.
    ///
    /// # Errors
    ///
    /// - [`apollia_llm::LlmError::RoutingConfigMissing`]: `[llm.routing]` missing from the config.
    /// - [`apollia_llm::LlmError::BackendNotFound`]: `precise` backend not found in the router.
    pub fn with_llm_router_and_reasoner(
        mut self,
        router: LlmRouter,
        max_steps: u32,
    ) -> Result<Self, apollia_llm::LlmError> {
        let model = router.route_precise()?;
        self.reasoner = Some(Reasoner::new(model, max_steps));
        self.llm_router = router;
        Ok(self)
    }
    /// Inject an `EventBusSender` to broadcast plan events on the bus.
    pub fn with_event_bus(mut self, bus: EventBusSender) -> Self {
        self.event_bus = bus;
        self
    }
    /// Inject the ORIA configuration read from `apollia.toml`.
    ///
    /// If not called, [`ORIAConfig::default`] is used (`max_replans = 2`).
    /// The `max_replans` value controls how many re-plans are allowed in
    /// Orchestrated mode before failing permanently.
    /// Also updates the `ContextManager` with the configured compaction thresholds.
    pub fn with_oria_config(mut self, config: ORIAConfig) -> Self {
        self.context_manager = ContextManager::from_config(&config);
        self.oria_config = config;
        self
    }
    /// Inject the HITL registry of pending approvals.
    ///
    /// Required for `execute_direct()` to suspend the task in `input_required` status
    /// and wait for the human decision through a oneshot channel.
    /// Shared between the `ORIAEngine` and the REST routes via `AppState`.
    pub fn with_pending_approvals(mut self, pending: Arc<PendingApprovals>) -> Self {
        self.pending_approvals = Some(pending);
        self
    }
    /// Inject the plan-gate registry, shared with the decision consumer.
    ///
    /// Required for an active gate to suspend the run after plan generation and
    /// await an approve/reject decision. Shared between the `ORIAEngine` and the
    /// REST routes via `AppState`.
    pub fn with_pending_plan_gates(mut self, gates: Arc<PendingPlanGates>) -> Self {
        self.pending_plan_gates = Some(gates);
        self
    }
    /// Force the plan gate active for every orchestrated run.
    ///
    /// Convenience for `with_plan_gate_override(Some(force))`: independent of the
    /// autonomy tier, `true` always gates and `false` always bypasses.
    pub fn with_force_plan_gate(mut self, force: bool) -> Self {
        self.plan_gate_override = Some(force);
        self
    }
    /// Set the per-run plan-gate override.
    ///
    /// `Some(true)` forces the gate, `Some(false)` bypasses it, `None` defers to
    /// the autonomy tier.
    pub fn with_plan_gate_override(mut self, override_: Option<bool>) -> Self {
        self.plan_gate_override = override_;
        self
    }
    /// Inject the HITL SQLite repository to persist the prompt and context.
    ///
    /// If absent, SQLite persistence is skipped but HITL execution continues
    /// (logged warning: fail fast only for detectable errors).
    pub fn with_task_repository(mut self, repo: Arc<apollia_tools::TaskRepository>) -> Self {
        self.task_repository = Some(repo);
        self
    }
    /// Inject a [`MemoryManager`] for per-step episodic recording.
    ///
    /// Passed to the [`ActorLoop`] during orchestrated execution. Each completed step
    /// automatically records an episodic entry in the agent's namespace.
    pub fn with_memory_manager(mut self, mm: Arc<Mutex<MemoryManager>>) -> Self {
        self.memory_manager = Some(mm);
        self
    }
    /// Add the plan cache to the engine, shared with the rest of the runtime.
    ///
    /// [`execute_orchestrated_plan`] then checks it before calling the Reasoner:
    /// a hit avoids the LLM call, clones the plan with a new `plan_id`, and emits
    /// [`RuntimeEvent::PlanCacheHit`]. Cache errors are logged at `warn` without
    /// blocking execution.
    ///
    /// The repository is borrowed, not owned, because the supervisor opens it at
    /// boot and hands the same handle to the REST stats and clear routes. The
    /// builder this replaces took ownership, which no caller could satisfy, and
    /// for want of that signature the engine ran with no cache at all: every
    /// orchestrated run re-planned from scratch while `plan cache stats` reported
    /// an empty cache, which was true and read as "nothing cached yet".
    ///
    /// [`execute_orchestrated_plan`]: ORIAEngine::execute_orchestrated_plan
    pub fn with_shared_plan_cache(mut self, repo: Arc<Mutex<PlanCacheRepository>>) -> Self {
        self.plan_cache = Some(repo);
        self
    }
    /// Configure the working directory for workspace context collection.
    ///
    /// Used by `execute_orchestrated_plan` to collect the git branch, file status,
    /// and `APOLLIA.md` content before each execution.
    pub fn with_cwd(mut self, cwd: PathBuf) -> Self {
        self.cwd = cwd;
        self
    }
    /// Create an `ORIAEngine` with a specific working directory.
    ///
    /// Shorthand equivalent to `ORIAEngine::new().with_cwd(cwd)`.
    /// Mainly used in unit tests.
    pub fn new_with_cwd(cwd: PathBuf) -> Self {
        Self::new().with_cwd(cwd)
    }
    /// Collect the workspace context and return the `<context name="...">` blocks.
    ///
    /// Uses [`ProjectRuntime`] with the configured TTL cache to avoid repeated I/O.
    /// Returns an empty string when no context is available (directory outside a git
    /// repo, no `APOLLIA.md`, or the collection timeout was exceeded).
    /// Each section is wrapped in its own `<context name="...">` tag.
    pub async fn build_system_prompt(&self) -> String {
        let snapshot = self.workspace_assembler.collect(&self.cwd).await;
        snapshot.format_for_prompt()
    }
}
