use serde::{Deserialize, Serialize};

/// Structured narration attached to a tool call.
///
/// Generated by [`MetaRoutine::GenerateToolCallRationale`] *before* execution
/// and carried in [`RuntimeEvent::ChatToolCallStarted`] so the frontend can
/// display it without waiting for the tool to finish.
///
/// Lives in `apollia-core` so that `RuntimeEvent` can reference it without
/// creating a circular dependency with `apollia-llm`.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct ToolCallRationale {
    /// Narrative sentence (<= 25 words) explaining why the call is made.
    pub summary: String,
    /// Compact recap of the key parameters, order preserved.
    #[serde(default)]
    pub inputs_recap: Vec<(String, String)>,
    /// Expected result of the tool (one sentence).
    pub expected_outcome: String,
    /// Performance hint (e.g. "Expected duration: 2s" or a suggestion of a
    /// faster tool); absent when no relevant hint applies.
    #[serde(default)]
    pub performance_hint: Option<String>,
}

impl ToolCallRationale {
    /// Deserialize a raw LLM response (trim plus strip Markdown backticks).
    pub fn parse(raw: &str) -> Result<Self, serde_json::Error> {
        let clean = raw
            .trim()
            .trim_start_matches("```json")
            .trim_start_matches("```")
            .trim_end_matches("```")
            .trim();
        serde_json::from_str(clean)
    }
}
