//! Commandes IPC Tauri pour l'inspection et l'initialisation du workspace.
//!
//! Délègue à l'API REST interne pour les opérations workspace qui nécessitent
//! l'accès au runtime, et opère directement sur le système de fichiers pour
//! les opérations locales.

use apollia_runtime::embedded::RuntimeHandle;
use serde::Serialize;
use tauri::State;

/// Statut du workspace courant.
#[derive(Debug, Serialize)]
pub struct WorkspaceStatus {
    /// Chemin du workspace courant.
    pub path: String,
    /// Indique si `apollia.toml` est présent et valide.
    pub has_config: bool,
    /// Indique si le dossier `.apollia/` est initialisé.
    pub initialized: bool,
    /// Nombre d'agents déclarés dans la config (ou chargés dans le runtime).
    pub agent_count: usize,
    /// Version de la config (si présente).
    pub config_version: Option<String>,
}

/// Retourne le statut du workspace courant.
///
/// Lit `apollia.toml` dans le répertoire courant et les métadonnées runtime
/// pour construire une vue synthétique de l'état du workspace.
#[tauri::command]
pub async fn get_workspace_status(
    state: State<'_, RuntimeHandle>,
) -> Result<WorkspaceStatus, String> {
    let cwd = std::env::current_dir()
        .map_err(|e| format!("cannot determine cwd: {e}"))?;

    let config_path = cwd.join("apollia.toml");
    let has_config = config_path.exists();
    let apollia_dir = cwd.join(".apollia");
    let initialized = apollia_dir.exists();

    // Count agents via the registry handle; fall back to 0 on error.
    let agent_count = state
        .registry_handle
        .list_agents()
        .await
        .map(|v| v.len())
        .unwrap_or(0);

    // Extract the `version` field from apollia.toml if present.
    let config_version = if has_config {
        std::fs::read_to_string(&config_path)
            .ok()
            .and_then(|content| {
                content
                    .lines()
                    .find(|l| l.starts_with("version"))
                    .and_then(|l| l.split('=').nth(1))
                    .map(|v| v.trim().trim_matches('"').to_string())
            })
    } else {
        None
    };

    Ok(WorkspaceStatus {
        path: cwd.display().to_string(),
        has_config,
        initialized,
        agent_count,
        config_version,
    })
}

/// Initialise le workspace en créant la structure de base.
///
/// Crée `apollia.toml` minimal et le dossier `.apollia/` si absents.
/// Retourne une erreur si le workspace est déjà initialisé, sauf avec `force = true`.
/// En cas de succès, retourne le chemin absolu du workspace initialisé.
#[tauri::command]
pub async fn init_workspace(force: bool) -> Result<String, String> {
    let cwd = std::env::current_dir()
        .map_err(|e| format!("cannot determine cwd: {e}"))?;

    let config_path = cwd.join("apollia.toml");
    let apollia_dir = cwd.join(".apollia");

    if config_path.exists() && !force {
        return Err(format!(
            "workspace already initialized at {}. Use force=true to reinitialize.",
            cwd.display()
        ));
    }

    // Create .apollia/ if absent.
    if !apollia_dir.exists() {
        std::fs::create_dir_all(&apollia_dir)
            .map_err(|e| format!("failed to create .apollia/: {e}"))?;
    }

    // Create apollia.toml minimal if absent or if force.
    if !config_path.exists() || force {
        let template = r#"# Apollia OS workspace configuration
# Generated by apollia-desktop

[runtime]
data_dir = ".apollia"

[llm]
default_backend = "local"

# [[agents]]
# name = "my-agent"
# path = "./agents/my_agent.py"
"#;
        std::fs::write(&config_path, template)
            .map_err(|e| format!("failed to write apollia.toml: {e}"))?;
    }

    Ok(cwd.display().to_string())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_workspace_status_serializes_initialized() {
        // GIVEN a fully initialized workspace status
        let status = WorkspaceStatus {
            path: "/home/user/my-project".to_string(),
            has_config: true,
            initialized: true,
            agent_count: 3,
            config_version: Some("1".to_string()),
        };

        // WHEN serialized to JSON
        let json = serde_json::to_value(&status).expect("serialize");

        // THEN all fields are present and correct
        assert_eq!(json["path"], "/home/user/my-project");
        assert_eq!(json["has_config"], true);
        assert_eq!(json["initialized"], true);
        assert_eq!(json["agent_count"], 3);
        assert_eq!(json["config_version"], "1");
    }

    #[test]
    fn test_workspace_status_serializes_empty() {
        // GIVEN an empty workspace (no config, not initialized)
        let status = WorkspaceStatus {
            path: "/tmp/empty".to_string(),
            has_config: false,
            initialized: false,
            agent_count: 0,
            config_version: None,
        };

        // WHEN serialized to JSON
        let json = serde_json::to_value(&status).expect("serialize");

        // THEN optional fields are null
        assert_eq!(json["has_config"], false);
        assert_eq!(json["initialized"], false);
        assert_eq!(json["agent_count"], 0);
        assert!(json["config_version"].is_null());
    }
}
