//! Execution plan types for ORIA's Orchestrated mode.
//!
//! These types are produced by [`crate::reasoner::Reasoner`], validated by
//! [`crate::topo::topological_sort`], and consumed by the `ActorLoop`.

/// Multi-step execution plan generated by the Reasoner.
///
/// Serializable to JSON to be sent to the LLM and parsed from its response.
/// Validation (unique step IDs, valid dependencies, no cycles) is performed by
/// [`crate::reasoner::Reasoner::parse_and_validate`].
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct ExecutionPlan {
    /// Unique plan identifier (UUID v4), generated at creation.
    pub plan_id: String,
    /// Identifier of the task this plan belongs to.
    pub task_id: String,
    /// Steps to execute in the order resolved by the topological sort.
    pub steps: Vec<PlanStep>,
}

/// A single step in an [`ExecutionPlan`].
///
/// Each step represents an atomic action the `ActorLoop` must execute.
/// Execution order is determined by `depends_on` via
/// [`crate::topo::topological_sort`].
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct PlanStep {
    /// Unique identifier within the plan (e.g. `"s1"`, `"s2"`).
    pub step_id: String,
    /// Natural-language description of the action to perform.
    pub description: String,
    /// Tool suggested by the LLM (`None` when the step needs no native tool).
    #[serde(default)]
    pub tool_hint: Option<String>,
    /// Identifiers of the steps this step depends on (execution DAG).
    ///
    /// All steps listed here must complete before this step can start.
    /// Validated by `parse_and_validate()`.
    #[serde(default)]
    pub depends_on: Vec<String>,
    /// Optional hint to route this step to a specific LLM backend.
    ///
    /// When `None`, the `LlmRouter`'s default backend is used.
    /// Resolving the hint to a concrete backend is done by the `ActorLoop`.
    #[serde(default)]
    pub model_hint: Option<String>,
}
