//! Topological sort of an `ExecutionPlan`'s steps based on their dependencies.
//!
//! This module exposes [`topological_sort`], a pure function used by two
//! consumers:
//! - [`crate::reasoner::Reasoner::parse_and_validate`]: to detect cycles before
//!   accepting a plan generated by the LLM.
//! - `ActorLoop`: to obtain the sequential execution order of the steps.

use std::collections::{HashMap, VecDeque};

use crate::plan::PlanStep;

/// Builds the in-degree vector and the dependents adjacency list shared by
/// [`topological_sort`] and [`topological_levels`].
///
/// `in_degree[i]` counts the valid (known) dependencies of `steps[i]`.
/// `dependents[step_id]` lists the indices of steps that depend on `step_id`.
/// Unknown dependencies are ignored in the in-degree count (already validated
/// upstream) but still recorded as edges in the dependents map, matching the
/// original inline behaviour of both callers.
fn build_dependency_graph(steps: &[PlanStep]) -> (Vec<usize>, HashMap<&str, Vec<usize>>) {
    let id_to_idx: HashMap<&str, usize> = steps
        .iter()
        .enumerate()
        .map(|(i, s)| (s.step_id.as_str(), i))
        .collect();

    let mut in_degree = vec![0usize; steps.len()];
    let mut dependents: HashMap<&str, Vec<usize>> = HashMap::new();
    for (i, step) in steps.iter().enumerate() {
        for dep in &step.depends_on {
            if id_to_idx.contains_key(dep.as_str()) {
                in_degree[i] += 1;
            }
            dependents.entry(dep.as_str()).or_default().push(i);
        }
    }

    (in_degree, dependents)
}

/// Decrements the in-degree of every step that depends on `completed_id` and
/// returns the indices whose in-degree just reached zero (newly unblocked).
///
/// Shared by both Kahn-style traversals. `in_degree` is mutated in place.
fn release_dependents(
    completed_id: &str,
    dependents: &HashMap<&str, Vec<usize>>,
    in_degree: &mut [usize],
) -> Vec<usize> {
    let mut unblocked = Vec::new();
    if let Some(dep_indices) = dependents.get(completed_id) {
        for &dep_idx in dep_indices {
            in_degree[dep_idx] -= 1;
            if in_degree[dep_idx] == 0 {
                unblocked.push(dep_idx);
            }
        }
    }
    unblocked
}

/// Error returned when a cycle is detected in the plan's dependencies.
///
/// Indicates that at least two steps form a circular dependency, making ordered
/// execution impossible.
#[derive(Debug, thiserror::Error)]
#[error("circular dependency detected in the execution plan")]
pub struct CycleError;

/// Groups steps into execution levels.
///
/// Steps in the same level share no dependency edge between them and can therefore
/// be executed concurrently. Steps in level N must all complete before any step in
/// level N+1 starts.
///
/// Returns `Err(CycleError)` if the dependency graph contains a cycle.
///
/// **Algorithm**: standard BFS level-assignment after in-degree initialisation.
/// All steps with in-degree 0 form level 0. After processing a level, each step
/// whose in-degree reaches 0 is placed in the next level.
pub fn topological_levels(steps: &[PlanStep]) -> Result<Vec<Vec<String>>, CycleError> {
    if steps.is_empty() {
        return Ok(vec![]);
    }

    let (mut in_degree, dependents) = build_dependency_graph(steps);

    let mut current_level: Vec<usize> = in_degree
        .iter()
        .enumerate()
        .filter(|(_, &d)| d == 0)
        .map(|(i, _)| i)
        .collect();

    let mut levels: Vec<Vec<String>> = Vec::new();
    let mut processed = 0usize;

    while !current_level.is_empty() {
        let level_ids: Vec<String> = current_level
            .iter()
            .map(|&i| steps[i].step_id.clone())
            .collect();
        processed += current_level.len();

        // Build the next level: steps unblocked by completing the current level.
        let mut next_level: Vec<usize> = Vec::new();
        for &idx in &current_level {
            next_level.extend(release_dependents(
                steps[idx].step_id.as_str(),
                &dependents,
                &mut in_degree,
            ));
        }

        levels.push(level_ids);
        current_level = next_level;
    }

    if processed != steps.len() {
        Err(CycleError)
    } else {
        Ok(levels)
    }
}

/// Topological sort of an `ExecutionPlan`'s steps based on their dependencies.
///
/// Returns the list of `step_id`s in a valid execution order: each step appears
/// after all steps listed in its `depends_on`.
/// Returns `Err(CycleError)` if the dependencies form a cycle.
///
/// **Kahn's algorithm (BFS):**
/// 1. Compute the in-degree of each step (number of valid direct dependencies)
/// 2. Initialize the queue with steps that have no dependencies (in-degree = 0)
/// 3. While the queue is non-empty:
///    a. Pop a step from the queue and add it to the result
///    b. For each step that depends on it: decrement its in-degree
///    c. If in-degree reaches 0: add it to the queue
/// 4. If `result.len() != steps.len()`: a cycle was detected
///
/// The function is **pure**: no global mutable state, same input = same output.
/// No recursion: avoids stack overflows on large plans.
pub fn topological_sort(steps: &[PlanStep]) -> Result<Vec<String>, CycleError> {
    if steps.is_empty() {
        return Ok(vec![]);
    }

    // in_degree[i] = number of valid dependencies step i has (predecessors).
    // dependents[step_id] = list of indices that depend on step_id.
    // Unknown deps are ignored in the in-degree count, already validated by
    // parse_and_validate().
    let (mut in_degree, dependents) = build_dependency_graph(steps);

    // Initialize queue with steps that have no dependencies
    let mut queue: VecDeque<usize> = in_degree
        .iter()
        .enumerate()
        .filter(|(_, &d)| d == 0)
        .map(|(i, _)| i)
        .collect();

    let mut result = Vec::with_capacity(steps.len());

    while let Some(idx) = queue.pop_front() {
        result.push(steps[idx].step_id.clone());

        // For each step that depends on the current step, decrement its in-degree
        queue.extend(release_dependents(
            steps[idx].step_id.as_str(),
            &dependents,
            &mut in_degree,
        ));
    }

    if result.len() != steps.len() {
        Err(CycleError)
    } else {
        Ok(result)
    }
}

// Tests

#[cfg(test)]
mod tests {
    use super::*;

    fn step(id: &str, deps: &[&str]) -> PlanStep {
        let mut s = PlanStep::new(id, format!("Step {id}"));
        s.depends_on = deps.iter().map(|d| d.to_string()).collect();
        s
    }

    /// GIVEN [s1 (no deps), s2 (depends_on: [s1]), s3 (depends_on: [s2])]
    /// WHEN topological_sort(&steps) is called
    /// THEN Ok(["s1", "s2", "s3"]) is returned
    #[test]
    fn test_plan_lineaire() {
        // GIVEN
        let steps = vec![step("s1", &[]), step("s2", &["s1"]), step("s3", &["s2"])];
        // WHEN
        let result = topological_sort(&steps).unwrap();
        // THEN
        assert_eq!(result, vec!["s1", "s2", "s3"]);
    }

    /// GIVEN [s1, s2, s3 (all with no deps), s4 (depends_on: [s1, s2, s3])]
    /// WHEN topological_sort(&steps) is called
    /// THEN s1, s2, s3 appear before s4
    #[test]
    fn test_branches_paralleles() {
        // GIVEN
        let steps = vec![
            step("s1", &[]),
            step("s2", &[]),
            step("s3", &[]),
            step("s4", &["s1", "s2", "s3"]),
        ];
        // WHEN
        let result = topological_sort(&steps).unwrap();
        // THEN
        assert_eq!(result.len(), 4);
        let s4_pos = result.iter().position(|s| s == "s4").unwrap();
        for s in ["s1", "s2", "s3"] {
            let pos = result.iter().position(|x| x == s).unwrap();
            assert!(pos < s4_pos, "{s} doit précéder s4");
        }
    }

    /// GIVEN [s1 (depends_on: [s2]), s2 (depends_on: [s1])]
    /// WHEN topological_sort(&steps) is called
    /// THEN Err(CycleError) is returned
    #[test]
    fn test_cycle_simple() {
        // GIVEN
        let steps = vec![step("s1", &["s2"]), step("s2", &["s1"])];
        // WHEN
        let result = topological_sort(&steps);
        // THEN
        assert!(matches!(result, Err(CycleError)));
    }

    /// GIVEN [s1->s3, s2->s1, s3->s2] (long cycle)
    /// WHEN topological_sort(&steps) is called
    /// THEN Err(CycleError) is returned
    #[test]
    fn test_cycle_long() {
        // GIVEN
        let steps = vec![
            step("s1", &["s3"]),
            step("s2", &["s1"]),
            step("s3", &["s2"]),
        ];
        // WHEN
        let result = topological_sort(&steps);
        // THEN
        assert!(matches!(result, Err(CycleError)));
    }

    /// GIVEN an empty list
    /// WHEN topological_sort(&[]) is called
    /// THEN Ok([]) is returned
    #[test]
    fn test_plan_vide() {
        // GIVEN / WHEN / THEN
        let result = topological_sort(&[]).unwrap();
        assert!(result.is_empty());
    }

    /// GIVEN [s2 (depends_on: [s1]), s1 (no deps)], reversed order in the Vec
    /// WHEN topological_sort(&steps) is called
    /// THEN s1 appears before s2 in the result
    #[test]
    fn test_ordre_entree_irrelevant() {
        // GIVEN
        let steps = vec![step("s2", &["s1"]), step("s1", &[])];
        // WHEN
        let result = topological_sort(&steps).unwrap();
        // THEN
        let s1_pos = result.iter().position(|s| s == "s1").unwrap();
        let s2_pos = result.iter().position(|s| s == "s2").unwrap();
        assert!(s1_pos < s2_pos);
    }

    /// GIVEN a single step with no dependencies
    /// WHEN topological_sort is called
    /// THEN Ok(["s1"]) is returned
    #[test]
    fn test_step_unique_sans_dep() {
        // GIVEN / WHEN
        let steps = vec![step("s1", &[])];
        let result = topological_sort(&steps).unwrap();
        // THEN
        assert_eq!(result, vec!["s1"]);
    }

    // -----------------------------------------------------------------------
    // topological_levels tests
    // -----------------------------------------------------------------------

    #[test]
    fn test_levels_empty() {
        // GIVEN / WHEN / THEN
        assert_eq!(topological_levels(&[]).unwrap(), Vec::<Vec<String>>::new());
    }

    #[test]
    fn test_levels_single_step() {
        // GIVEN
        let steps = vec![step("s1", &[])];
        // WHEN
        let levels = topological_levels(&steps).unwrap();
        // THEN
        assert_eq!(levels, vec![vec!["s1".to_string()]]);
    }

    #[test]
    fn test_levels_linear_chain() {
        // GIVEN: s1 -> s2 -> s3
        let steps = vec![step("s1", &[]), step("s2", &["s1"]), step("s3", &["s2"])];
        // WHEN
        let levels = topological_levels(&steps).unwrap();
        // THEN: three separate levels (no parallelism possible)
        assert_eq!(levels.len(), 3);
        assert_eq!(levels[0], vec!["s1"]);
        assert_eq!(levels[1], vec!["s2"]);
        assert_eq!(levels[2], vec!["s3"]);
    }

    #[test]
    fn test_levels_parallel_fan_out() {
        // GIVEN: s1 (no deps), s2 (no deps), s3 (no deps), s4 (depends on all)
        let steps = vec![
            step("s1", &[]),
            step("s2", &[]),
            step("s3", &[]),
            step("s4", &["s1", "s2", "s3"]),
        ];
        // WHEN
        let levels = topological_levels(&steps).unwrap();
        // THEN: level 0: {s1, s2, s3}; level 1: {s4}
        assert_eq!(levels.len(), 2);
        let mut level0 = levels[0].clone();
        level0.sort();
        assert_eq!(level0, vec!["s1", "s2", "s3"]);
        assert_eq!(levels[1], vec!["s4"]);
    }

    #[test]
    fn test_levels_diamond() {
        // GIVEN: s1 -> s2, s1 -> s3, s2 -> s4, s3 -> s4
        let steps = vec![
            step("s1", &[]),
            step("s2", &["s1"]),
            step("s3", &["s1"]),
            step("s4", &["s2", "s3"]),
        ];
        // WHEN
        let levels = topological_levels(&steps).unwrap();
        // THEN: level 0: {s1}, level 1: {s2, s3}, level 2: {s4}
        assert_eq!(levels.len(), 3);
        assert_eq!(levels[0], vec!["s1"]);
        let mut level1 = levels[1].clone();
        level1.sort();
        assert_eq!(level1, vec!["s2", "s3"]);
        assert_eq!(levels[2], vec!["s4"]);
    }

    #[test]
    fn test_levels_cycle_returns_error() {
        // GIVEN
        let steps = vec![step("s1", &["s2"]), step("s2", &["s1"])];
        // WHEN / THEN
        assert!(matches!(topological_levels(&steps), Err(CycleError)));
    }

    /// GIVEN a diamond s1->s2, s1->s3, s2->s4, s3->s4
    /// WHEN topological_sort is called
    /// THEN s1 before s4, result of length 4
    #[test]
    fn test_diamant() {
        // GIVEN
        let steps = vec![
            step("s1", &[]),
            step("s2", &["s1"]),
            step("s3", &["s1"]),
            step("s4", &["s2", "s3"]),
        ];
        // WHEN
        let result = topological_sort(&steps).unwrap();
        // THEN
        assert_eq!(result.len(), 4);
        let s1_pos = result.iter().position(|s| s == "s1").unwrap();
        let s4_pos = result.iter().position(|s| s == "s4").unwrap();
        assert!(s1_pos < s4_pos);
    }
}
