//! SSE streaming route for task events, `GET /api/v1/tasks/{id}/stream`.
//!
//! Subscribes to the runtime [`EventBus`] and filters [`RuntimeEvent`]s by
//! `task_id`, pushing each matching event as an SSE frame. The stream closes
//! automatically when a terminal event (completed/failed/canceled) is received.

use std::convert::Infallible;

use axum::extract::{Path, State};
use axum::http::StatusCode;
use axum::response::sse::{Event, KeepAlive, Sse};
use axum::response::IntoResponse;
use axum::Json;
use serde::Serialize;
use tokio_stream::wrappers::BroadcastStream;
use tokio_stream::StreamExt;

use apollia_core::RuntimeEvent;

use crate::api::server::AppState;
use crate::coordinator::ExecutionBackend;

/// SSE event sent to the client.
///
/// Serialized as a flat JSON object with an `event` field discriminating
/// the event type and additional data fields depending on the variant.
#[derive(Debug, Serialize)]
pub struct SseTaskEvent {
    /// Event type: "step", "tool_call", "completed", "failed", "canceled", "started".
    pub event: String,
    /// Additional event data (flattened into the top-level JSON object).
    #[serde(flatten)]
    pub data: serde_json::Value,
}

/// Standard error response body (same as routes_tasks).
#[derive(Debug, Serialize)]
struct ErrorResponse {
    /// Human-readable error description.
    error: String,
}

/// Convert a [`RuntimeEvent`] into an [`SseTaskEvent`] if it matches the given `task_id`.
///
/// Returns `None` for events that do not belong to the task or are not relevant
/// for per-task streaming (e.g. system-level events).
/// Returns `Some((event, is_terminal))`, `is_terminal` is true for events that
/// signal the end of the task execution (completed, failed, canceled, plan_failed).
fn runtime_event_to_sse(event: &RuntimeEvent, task_id: &str) -> Option<(SseTaskEvent, bool)> {
    match event {
        // Direct-mode events
        RuntimeEvent::StepExecuted {
            task_id: tid,
            step,
            tool,
        } if tid == task_id => {
            let data = match tool {
                Some(t) => serde_json::json!({ "step": step, "tool": t }),
                None => serde_json::json!({ "step": step }),
            };
            Some((
                SseTaskEvent {
                    event: "step".into(),
                    data,
                },
                false,
            ))
        }
        RuntimeEvent::TaskStarted {
            task_id: tid,
            agent_id,
        } if tid == task_id => Some((
            SseTaskEvent {
                event: "started".into(),
                data: serde_json::json!({ "agent_id": agent_id }),
            },
            false,
        )),
        RuntimeEvent::TaskCompleted {
            task_id: tid,
            success,
            output,
            ..
        } if tid == task_id => {
            let event_name = if *success { "completed" } else { "failed" };
            // Include the agent output text in the "completed" event so that CLI
            // callers (both polling and SSE) can display the result without a
            // separate endpoint (GET /api/v1/tasks/:id never carries the output).
            //
            // For failures we surface the same text under `error` so the CLI
            // can render an actionable message instead of falling back to a
            // generic "unknown error". The coordinator already encodes
            // `[CODE] message details=…` in `output` on failure, so this
            // re-surfaces the worker-reported reason all the way to the
            // operator.
            let mut data = serde_json::json!({ "success": success });
            if let Some(text) = output {
                if *success {
                    data["result"] = serde_json::Value::String(text.clone());
                } else {
                    data["error"] = serde_json::Value::String(text.clone());
                }
            }
            Some((
                SseTaskEvent {
                    event: event_name.into(),
                    data,
                },
                true,
            ))
        }
        RuntimeEvent::TaskCanceled { task_id: tid } if tid == task_id => Some((
            SseTaskEvent {
                event: "canceled".into(),
                data: serde_json::json!({}),
            },
            true,
        )),

        // Orchestrated plan events

        // A new execution plan has been generated by the Reasoner.
        RuntimeEvent::PlanGenerated {
            task_id: tid,
            plan_id,
            step_count,
            agent_name,
            run_id: _,
        } if tid == task_id => Some((
            SseTaskEvent {
                event: "plan_generated".into(),
                data: serde_json::json!({
                    "plan_id":    plan_id,
                    "step_count": step_count,
                    "agent_name": agent_name,
                }),
            },
            false,
        )),

        // A plan step has started its execution.
        RuntimeEvent::StepStarted {
            task_id: tid,
            plan_id,
            step_id,
            step_num,
            total,
            desc,
        } if tid == task_id => Some((
            SseTaskEvent {
                event: "step_started".into(),
                data: serde_json::json!({
                    "plan_id": plan_id,
                    "step_id": step_id,
                    "num":     step_num,
                    "total":   total,
                    "desc":    desc,
                }),
            },
            false,
        )),

        // A plan step completed successfully.
        RuntimeEvent::StepCompleted {
            task_id: tid,
            plan_id,
            step_id,
            duration_ms,
        } if tid == task_id => Some((
            SseTaskEvent {
                event: "step_completed".into(),
                data: serde_json::json!({
                    "plan_id":     plan_id,
                    "step_id":     step_id,
                    "duration_ms": duration_ms,
                }),
            },
            false,
        )),

        // A plan step failed, may trigger replanning.
        RuntimeEvent::StepFailed {
            task_id: tid,
            plan_id,
            step_id,
            error,
            retryable,
        } if tid == task_id => Some((
            SseTaskEvent {
                event: "step_failed".into(),
                data: serde_json::json!({
                    "plan_id":   plan_id,
                    "step_id":   step_id,
                    "error":     error,
                    "retryable": retryable,
                }),
            },
            false,
        )),

        // A replanning cycle has been triggered after a retryable step failure.
        RuntimeEvent::PlanReplanning {
            task_id: tid,
            plan_id,
            attempt,
            failed_step,
            reason,
        } if tid == task_id => Some((
            SseTaskEvent {
                event: "replanning".into(),
                data: serde_json::json!({
                    "plan_id":     plan_id,
                    "attempt":     attempt,
                    "failed_step": failed_step,
                    "reason":      reason,
                }),
            },
            false,
        )),

        // All steps completed, the plan finished successfully.
        RuntimeEvent::PlanCompleted {
            task_id: tid,
            plan_id,
            step_count,
            duration_ms,
        } if tid == task_id => Some((
            SseTaskEvent {
                event: "plan_completed".into(),
                data: serde_json::json!({
                    "plan_id":     plan_id,
                    "step_count":  step_count,
                    "duration_ms": duration_ms,
                }),
            },
            false,
        )),

        // The plan failed irrecoverably, terminal event, closes the stream.
        RuntimeEvent::PlanFailed {
            task_id: tid,
            plan_id,
            reason,
        } if tid == task_id => Some((
            SseTaskEvent {
                event: "plan_failed".into(),
                data: serde_json::json!({
                    "plan_id": plan_id,
                    "reason":  reason,
                }),
            },
            true,
        )),

        // Human-in-the-loop events

        // The task is suspended waiting for human approval, non-terminal.
        RuntimeEvent::TaskInputRequired {
            task_id: tid,
            prompt,
            step_id,
        } if tid == task_id => Some((
            SseTaskEvent {
                event: "input_required".into(),
                data: serde_json::json!({
                    "task_id":  tid,
                    "prompt":   prompt,
                    "step_id":  step_id,
                    "channel":  "approvals",
                }),
            },
            false,
        )),

        // The task has been resumed after HITL, non-terminal, execution continues.
        RuntimeEvent::TaskResumed {
            task_id: tid,
            approved,
        } if tid == task_id => Some((
            SseTaskEvent {
                event: "resumed".into(),
                data: serde_json::json!({
                    "task_id":  tid,
                    "approved": approved,
                    "channel":  "approvals",
                }),
            },
            false,
        )),

        _ => None,
    }
}

/// Handler for `GET /api/v1/tasks/{id}/stream`.
///
/// Subscribes to the runtime EventBus and streams task-specific events via SSE.
/// Returns 404 if the task does not exist in the TaskRouter.
/// The stream closes after a terminal event (completed/failed/canceled).
/// Client disconnection drops the subscriber automatically (no leak).
pub async fn stream_task<B: ExecutionBackend + Clone>(
    State(state): State<AppState<B>>,
    Path(task_id): Path<String>,
) -> Result<Sse<impl tokio_stream::Stream<Item = Result<Event, Infallible>>>, impl IntoResponse> {
    // Verify the task exists before subscribing
    let status = state
        .router_handle
        .get_status(&task_id)
        .await
        .map_err(|_| {
            (
                StatusCode::INTERNAL_SERVER_ERROR,
                Json(ErrorResponse {
                    error: "router actor is dead".into(),
                }),
            )
        })?;

    if status.is_none() {
        return Err((
            StatusCode::NOT_FOUND,
            Json(ErrorResponse {
                error: format!("task not found: {task_id}"),
            }),
        ));
    }

    // Subscribe to the EventBus broadcast channel
    let rx = state.event_sender.subscribe();
    let stream = BroadcastStream::new(rx);

    // Filter events for this task_id, convert to SSE frames, stop on terminal
    let task_id_owned = task_id.clone();
    let sse_stream = stream
        .filter_map(move |result| {
            match result {
                Ok(event) => runtime_event_to_sse(&event, &task_id_owned),
                // Lagged receiver: skip lost events silently
                Err(_) => None,
            }
        })
        .map(|(sse_event, is_terminal)| (sse_event, is_terminal))
        // Take events until (and including) the first terminal event
        .take_while_inclusive(|(_event, is_terminal)| !is_terminal)
        .map(|(sse_event, _)| {
            let json = serde_json::to_string(&sse_event).unwrap_or_else(|_| "{}".into());
            Ok(Event::default().data(json))
        });

    Ok(Sse::new(sse_stream).keep_alive(KeepAlive::default()))
}

/// Extension trait to add `take_while_inclusive` to streams.
///
/// Unlike `take_while`, this yields the first item that fails the predicate
/// before closing the stream, needed to send the terminal SSE event.
struct TakeWhileInclusive<S, F> {
    stream: S,
    predicate: F,
    done: bool,
}

impl<S, F, T> tokio_stream::Stream for TakeWhileInclusive<S, F>
where
    S: tokio_stream::Stream<Item = T> + Unpin,
    F: FnMut(&T) -> bool + Unpin,
{
    type Item = T;

    fn poll_next(
        self: std::pin::Pin<&mut Self>,
        cx: &mut std::task::Context<'_>,
    ) -> std::task::Poll<Option<Self::Item>> {
        let this = self.get_mut();
        if this.done {
            return std::task::Poll::Ready(None);
        }
        match std::pin::Pin::new(&mut this.stream).poll_next(cx) {
            std::task::Poll::Ready(Some(item)) => {
                if (this.predicate)(&item) {
                    std::task::Poll::Ready(Some(item))
                } else {
                    this.done = true;
                    std::task::Poll::Ready(Some(item))
                }
            }
            std::task::Poll::Ready(None) => std::task::Poll::Ready(None),
            std::task::Poll::Pending => std::task::Poll::Pending,
        }
    }
}

/// Extension trait providing `take_while_inclusive` on any stream.
trait TakeWhileInclusiveExt: tokio_stream::Stream + Sized {
    /// Yields items while `predicate` returns true, then yields the first
    /// item for which `predicate` returns false and closes.
    fn take_while_inclusive<F>(self, predicate: F) -> TakeWhileInclusive<Self, F>
    where
        F: FnMut(&Self::Item) -> bool;
}

impl<S: tokio_stream::Stream> TakeWhileInclusiveExt for S {
    fn take_while_inclusive<F>(self, predicate: F) -> TakeWhileInclusive<Self, F>
    where
        F: FnMut(&Self::Item) -> bool,
    {
        TakeWhileInclusive {
            stream: self,
            predicate,
            done: false,
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::eventbus::EventBus;
    use crate::registry::AgentRegistry;
    use crate::router::TaskRouterHandle;
    use apollia_core::{AIPResult, AIPTask, TaskStatus};
    use std::future::Future;
    use std::pin::Pin;

    use axum::body::Body;
    use axum::http::{Request, StatusCode};
    use axum::routing::get;
    use axum::Router;
    use tower::ServiceExt;

    /// Minimal backend for testing (never actually executes in these tests).
    #[derive(Clone)]
    struct MockBackend;

    impl ExecutionBackend for MockBackend {
        fn execute(
            &self,
            task: AIPTask,
        ) -> Pin<Box<dyn Future<Output = Result<AIPResult, String>> + Send>> {
            Box::pin(async move {
                Ok(AIPResult {
                    task_id: task.task_id,
                    status: TaskStatus::Completed,
                    output: Vec::new(),
                    error: None,
                    artifacts: Vec::new(),
                    input_required_data: None,
                })
            })
        }
    }

    /// Build a minimal test router (no agents) for 404 tests.
    fn test_router_no_agents() -> Router {
        let (event_tx, _) = EventBus::new();
        let registry_handle = AgentRegistry::spawn(event_tx.clone());
        let router_handle: TaskRouterHandle<MockBackend> =
            TaskRouterHandle::spawn(registry_handle.clone(), event_tx.clone(), 64);
        let state = AppState {
            router_handle,
            registry_handle,
            event_sender: event_tx,
            agent_loader: std::sync::Arc::new(crate::api::routes_agents::StubAgentLoader),
            backend: MockBackend,
            llm_router: crate::api::server::empty_shared_llm_router(),
            trigger_engine: None,
            config_path: None,
            task_repository: None,
            pending_approvals: None,
            notification_config: None,
            backend_factory: None,
            tool_registry_handle: None,
            audit_trail: None,
            obs_config: apollia_core::ObservabilityConfig::default(),
            llm_call_repository: None,
            trigger_def_repo: None,
            notification_repo: None,
            notification_engine_handle: None,
            chat_manager: None,
            plan_cache: None,
            mailbox_handle: None,
            user_memory: None,
            stt_engine: None,
            stt_repository: None,
            mcp_handle: None,
            mcp_server_repo: None,
            llm_backend_repo: None,
            stt_config_repo: None,
            a2a_invoker: None,
            resilience_layer: None,
            runner_proxy: None,
        };
        Router::new()
            .route("/api/v1/tasks/:id/stream", get(stream_task::<MockBackend>))
            .with_state(state)
    }

    #[tokio::test]
    async fn test_sse_unknown_task_returns_404() {
        // GIVEN no task "t-999"
        let router = test_router_no_agents();

        // WHEN GET /api/v1/tasks/t-999/stream
        let req = Request::builder()
            .uri("/api/v1/tasks/t-999/stream")
            .body(Body::empty())
            .expect("build request");
        let resp = router.oneshot(req).await.expect("request failed");

        // THEN 404 with an error
        assert_eq!(resp.status(), StatusCode::NOT_FOUND);
        let bytes = axum::body::to_bytes(resp.into_body(), 4096)
            .await
            .expect("read body");
        let json: serde_json::Value = serde_json::from_slice(&bytes).expect("parse json");
        assert!(json["error"]
            .as_str()
            .expect("error str")
            .contains("task not found"));
    }

    #[tokio::test]
    async fn test_runtime_event_to_sse_step_event() {
        // GIVEN a StepExecuted event for task "t-001"
        let event = RuntimeEvent::StepExecuted {
            task_id: "t-001".into(),
            step: 3,
            tool: Some("file_io".into()),
        };

        // WHEN converting it
        let result = runtime_event_to_sse(&event, "t-001");

        // THEN we get a non-terminal "step" SseTaskEvent
        let (sse, is_terminal) = result.expect("should match");
        assert_eq!(sse.event, "step");
        assert_eq!(sse.data["step"], 3);
        assert_eq!(sse.data["tool"], "file_io");
        assert!(!is_terminal);
    }

    #[tokio::test]
    async fn test_runtime_event_to_sse_filters_by_task_id() {
        // GIVEN a StepExecuted event for task "t-002"
        let event = RuntimeEvent::StepExecuted {
            task_id: "t-002".into(),
            step: 1,
            tool: None,
        };

        // WHEN converting it with task_id "t-001"
        let result = runtime_event_to_sse(&event, "t-001");

        // THEN None (wrong task_id)
        assert!(result.is_none());
    }

    #[tokio::test]
    async fn test_runtime_event_to_sse_completed_is_terminal() {
        // GIVEN a TaskCompleted event for task "t-001"
        let event = RuntimeEvent::TaskCompleted {
            agent_id: "agent-1".into(),
            task_id: "t-001".into(),
            success: true,
            output: None,
        };

        // WHEN converting it
        let result = runtime_event_to_sse(&event, "t-001");

        // THEN we get a terminal "completed" SseTaskEvent
        let (sse, is_terminal) = result.expect("should match");
        assert_eq!(sse.event, "completed");
        assert!(is_terminal);
    }

    #[tokio::test]
    async fn test_runtime_event_to_sse_canceled_is_terminal() {
        // GIVEN a TaskCanceled event for task "t-001"
        let event = RuntimeEvent::TaskCanceled {
            task_id: "t-001".into(),
        };

        // WHEN converting it
        let result = runtime_event_to_sse(&event, "t-001");

        // THEN we get a terminal "canceled" SseTaskEvent
        let (sse, is_terminal) = result.expect("should match");
        assert_eq!(sse.event, "canceled");
        assert!(is_terminal);
    }

    #[tokio::test]
    async fn test_runtime_event_to_sse_failed_is_terminal() {
        // GIVEN a TaskCompleted event with success=false
        let event = RuntimeEvent::TaskCompleted {
            agent_id: "agent-1".into(),
            task_id: "t-001".into(),
            success: false,
            output: None,
        };

        // WHEN converting it
        let result = runtime_event_to_sse(&event, "t-001");

        // THEN we get a terminal "failed" SseTaskEvent
        let (sse, is_terminal) = result.expect("should match");
        assert_eq!(sse.event, "failed");
        assert!(is_terminal);
    }

    #[tokio::test]
    async fn test_runtime_event_to_sse_ignores_system_events() {
        // GIVEN a system-level event (AllReady)
        let event = RuntimeEvent::AllReady;

        // WHEN converting it
        let result = runtime_event_to_sse(&event, "t-001");

        // THEN None (not a task event)
        assert!(result.is_none());
    }

    #[tokio::test]
    async fn test_take_while_inclusive_includes_terminal() {
        // GIVEN a stream of numbers
        let items = vec![1, 2, 3, 4, 5];
        let stream = tokio_stream::iter(items);

        // WHEN applying take_while_inclusive with predicate < 4
        let collected: Vec<i32> = stream.take_while_inclusive(|x| *x < 4).collect().await;

        // THEN we get [1, 2, 3, 4] (4 included, the first item that fails the predicate)
        assert_eq!(collected, vec![1, 2, 3, 4]);
    }

    // Tests: orchestrated plan events

    #[test]
    fn test_plan_generated_converti() {
        // GIVEN RuntimeEvent::PlanGenerated for task-001
        let event = RuntimeEvent::PlanGenerated {
            task_id: "task-001".into(),
            agent_name: "agent".into(),
            plan_id: "plan-001".into(),
            step_count: 4,
            run_id: None,
        };

        // WHEN converted to SSE
        let result = runtime_event_to_sse(&event, "task-001");

        // THEN non-terminal "plan_generated" event with step_count
        let (sse, is_terminal) = result.expect("should match task-001");
        assert_eq!(sse.event, "plan_generated");
        assert_eq!(sse.data["step_count"], 4);
        assert_eq!(sse.data["plan_id"], "plan-001");
        assert!(!is_terminal);
    }

    #[test]
    fn test_step_started_converti() {
        // GIVEN RuntimeEvent::StepStarted for task-001, step s1
        let event = RuntimeEvent::StepStarted {
            task_id: "task-001".into(),
            plan_id: "plan-001".into(),
            step_id: "s1".into(),
            step_num: 1,
            total: 4,
            desc: "Lire le fichier".into(),
        };

        // WHEN converted to SSE
        let (sse, is_terminal) =
            runtime_event_to_sse(&event, "task-001").expect("should match task-001");

        // THEN non-terminal "step_started" event with num and total
        assert_eq!(sse.event, "step_started");
        assert_eq!(sse.data["num"], 1);
        assert_eq!(sse.data["total"], 4);
        assert_eq!(sse.data["step_id"], "s1");
        assert!(!is_terminal);
    }

    #[test]
    fn test_event_autre_task_filtre() {
        // GIVEN RuntimeEvent::StepStarted for task-002 (a different task)
        let event = RuntimeEvent::StepStarted {
            task_id: "task-002".into(),
            plan_id: "plan-002".into(),
            step_id: "s1".into(),
            step_num: 1,
            total: 2,
            desc: "Step".into(),
        };

        // WHEN filtering for task-001
        let result = runtime_event_to_sse(&event, "task-001");

        // THEN None, event ignored
        assert!(result.is_none());
    }

    #[test]
    fn test_plan_failed_est_terminal() {
        // GIVEN RuntimeEvent::PlanFailed for task-001
        let event = RuntimeEvent::PlanFailed {
            task_id: "task-001".into(),
            plan_id: "plan-001".into(),
            reason: "MAX_REPLAN".into(),
        };

        // WHEN converted to SSE
        let (sse, is_terminal) =
            runtime_event_to_sse(&event, "task-001").expect("should match task-001");

        // THEN "plan_failed" event with is_terminal=true (closes the stream)
        assert_eq!(sse.event, "plan_failed");
        assert_eq!(sse.data["reason"], "MAX_REPLAN");
        assert!(is_terminal, "plan_failed doit etre terminal");
    }

    // Tests: human-in-the-loop events mapped to SSE

    #[test]
    fn test_task_input_required_mapped_to_sse() {
        // GIVEN RuntimeEvent::TaskInputRequired for task "t-001"
        let event = RuntimeEvent::TaskInputRequired {
            task_id: "t-001".into(),
            prompt: "Confirmer l'envoi ?".into(),
            step_id: Some("s3".into()),
        };

        // WHEN runtime_event_to_sse()
        let result = runtime_event_to_sse(&event, "t-001");

        // THEN SseTaskEvent{event:"input_required", data contains channel:"approvals"}
        let (sse, is_terminal) = result.expect("TaskInputRequired should match t-001");
        assert_eq!(sse.event, "input_required");
        assert_eq!(sse.data["channel"], "approvals");
        assert_eq!(sse.data["prompt"], "Confirmer l'envoi ?");
        assert!(!is_terminal, "input_required est non-terminal");
    }

    #[test]
    fn test_task_resumed_mapped_to_sse() {
        // GIVEN RuntimeEvent::TaskResumed{approved:true} for task "t-001"
        let event = RuntimeEvent::TaskResumed {
            task_id: "t-001".into(),
            approved: true,
        };

        // WHEN runtime_event_to_sse()
        let result = runtime_event_to_sse(&event, "t-001");

        // THEN SseTaskEvent{event:"resumed", data.approved==true}, non-terminal
        let (sse, is_terminal) = result.expect("TaskResumed should match t-001");
        assert_eq!(sse.event, "resumed");
        assert_eq!(sse.data["approved"], true);
        assert!(!is_terminal, "resumed est non-terminal");
    }
}
