//! The Anthropic Messages API wire types.
//!
//! Split out of `anthropic.rs`: the client stays in the parent, the request and
//! response shapes it serialises live here.

/// Representation of `cache_control` in the Anthropic API format.
///
/// Serialized as `{"type": "ephemeral"}`.
#[derive(serde::Serialize, Clone)]
pub(super) struct AnthropicCacheControl {
    #[serde(rename = "type")]
    pub(super) cache_type: &'static str,
}
impl AnthropicCacheControl {
    /// Build a `cache_control` of type `ephemeral`.
    pub(super) fn ephemeral() -> Self {
        Self {
            cache_type: "ephemeral",
        }
    }
}
/// Anthropic Messages API request format.
#[derive(serde::Serialize)]
pub(super) struct AnthropicRequest {
    pub(super) model: String,
    pub(super) max_tokens: u32,
    pub(super) messages: Vec<AnthropicMessage>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub(super) system: Option<AnthropicSystem>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub(super) tools: Option<Vec<AnthropicTool>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub(super) stream: Option<bool>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub(super) temperature: Option<f32>,
}
/// System prompt content: either a plain string or an array of blocks with
/// cache_control.
///
/// The Anthropic API accepts both forms. The array is used when prompt caching
/// is enabled to allow including `cache_control` on the last block.
#[derive(serde::Serialize, Clone)]
#[serde(untagged)]
pub(super) enum AnthropicSystem {
    /// System prompt without caching, serialized as a JSON string.
    Plain(String),
    /// System prompt with caching, serialized as an array of blocks.
    Blocks(Vec<AnthropicSystemBlock>),
}
/// Content block in the `system` field of the Anthropic request.
#[derive(serde::Serialize, Clone)]
pub(super) struct AnthropicSystemBlock {
    #[serde(rename = "type")]
    pub(super) block_type: &'static str,
    pub(super) text: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub(super) cache_control: Option<AnthropicCacheControl>,
}
/// Message in the Anthropic format (`role` + `content`).
#[derive(serde::Serialize, Clone)]
pub(super) struct AnthropicMessage {
    pub(super) role: &'static str,
    pub(super) content: AnthropicContent,
}
/// Content of an Anthropic message: plain text or an array of blocks.
#[derive(serde::Serialize, Clone)]
#[serde(untagged)]
pub(super) enum AnthropicContent {
    /// Plain text content.
    Text(String),
    /// Array of content blocks (tool, tool result, or structured text).
    Blocks(Vec<AnthropicBlock>),
}
/// Content block in the Anthropic format.
#[derive(serde::Serialize, Clone)]
#[serde(tag = "type", rename_all = "snake_case")]
pub(super) enum AnthropicBlock {
    /// Text block with optional cache support.
    Text {
        text: String,
        #[serde(skip_serializing_if = "Option::is_none")]
        cache_control: Option<AnthropicCacheControl>,
    },
    /// Tool call requested by the model.
    ToolUse {
        id: String,
        name: String,
        input: serde_json::Value,
    },
    /// Result of a tool call returned to the model, with optional cache support.
    ToolResult {
        tool_use_id: String,
        content: String,
        #[serde(skip_serializing_if = "Option::is_none")]
        cache_control: Option<AnthropicCacheControl>,
    },
}
/// Tool specification in the Anthropic format.
#[derive(serde::Serialize, Clone)]
pub(super) struct AnthropicTool {
    pub(super) name: String,
    pub(super) description: String,
    /// JSON schema of the parameters (equivalent to `parameters` in the OpenAI format).
    pub(super) input_schema: serde_json::Value,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub(super) cache_control: Option<AnthropicCacheControl>,
}
/// Anthropic response parsed from JSON.
#[derive(serde::Deserialize)]
pub(super) struct AnthropicResponse {
    pub(super) content: Vec<AnthropicResponseContent>,
    pub(super) stop_reason: Option<String>,
    pub(super) usage: AnthropicUsage,
}
/// Content item in the Anthropic response.
#[derive(serde::Deserialize)]
#[serde(tag = "type", rename_all = "snake_case")]
pub(super) enum AnthropicResponseContent {
    /// Text generated by the model.
    Text { text: String },
    /// Tool call requested by the model.
    ToolUse {
        id: String,
        name: String,
        input: serde_json::Value,
    },
}
/// Token statistics in the Anthropic response, including the cache fields.
#[derive(serde::Deserialize)]
pub(super) struct AnthropicUsage {
    pub(super) input_tokens: u32,
    pub(super) output_tokens: u32,
    /// Tokens read from the cache, present only if prompt caching is active.
    #[serde(default)]
    pub(super) cache_read_input_tokens: u32,
    /// Tokens written to the cache, present only if prompt caching is active.
    #[serde(default)]
    pub(super) cache_write_input_tokens: u32,
}
