//! CLI command modules.

pub mod agent;
pub mod audit;
pub mod auth;
pub mod chat;
pub mod llm;
pub mod mcp;
pub mod mcp_server;
pub mod memory;
pub mod model;
pub mod notify;
pub mod onboard;
pub mod permissions;
pub mod pipeline;
pub mod plan_cache;
pub mod resilience;
pub mod review;
pub mod rollback;
pub mod run;
pub mod start;
pub mod status;
pub mod stop;
pub mod stt;
pub mod task;
pub mod tools;
pub mod trigger;
pub mod update;
pub mod workspace;
