//! `LlmProxy`: PyO3 bridge exposing the LLM engine to Python via `ctx.llm`.
//!
//! All async methods use `pyo3_async_runtimes::tokio::future_into_py`.
//!
//! Tests requiring a full Python environment are gated behind
//! `#[cfg(feature = "python-tests")]`.

use std::sync::Arc;

use futures::StreamExt;
use pyo3::exceptions::{PyRuntimeError, PyStopAsyncIteration, PyValueError};
use pyo3::prelude::*;
use pyo3::IntoPyObjectExt;
use tokio::sync::{mpsc, Mutex as AsyncMutex};

use apollia_core::events::EventBusSender;
use apollia_llm::{
    ChatMessage, CompletionRequest, LlmError, LlmRouter, MessageContent, ObservabilityConfig, Role,
    StepBudgetView, StreamChunk, ToolCallHelper, ToolSpec,
};

/// Default bound on how many `map` items call the model at once when the caller
/// does not pass `max_concurrency`. Kept modest: the backend (llama-server) does
/// the real batching, and this only caps in-flight requests.
const DEFAULT_MAP_CONCURRENCY: usize = 8;

/// Capacity of the channel buffering streamed LLM token chunks between the
/// background forwarder and the Python async iterator. Bounded so a slow
/// consumer applies backpressure rather than letting the queue grow unbounded.
const TOKEN_STREAM_BUFFER_CAPACITY: usize = 1024;

// PyO3 types

/// Token-consumption statistics returned to Python.
///
/// Accessible via `response.usage.prompt_tokens`, etc.
#[pyclass(name = "TokenUsage")]
#[derive(Clone)]
pub struct PyTokenUsage {
    /// Number of tokens in the prompt (input).
    #[pyo3(get)]
    pub prompt_tokens: u32,
    /// Number of tokens generated (output).
    #[pyo3(get)]
    pub completion_tokens: u32,
    /// Estimated cost in USD; `None` for local backends.
    #[pyo3(get)]
    pub cost_usd: Option<f64>,
}

/// LLM response exposed to Python.
///
/// Returned by `ctx.llm.chat()` and `ctx.llm.complete()`.
///
/// # Python example
/// ```python
/// response = await ctx.llm.chat(system="Be helpful.", user="Hello")
/// print(response.content)          # str
/// print(response.usage.prompt_tokens)  # int
/// print(response.latency_ms)       # int
/// ```
#[pyclass(name = "LlmResponse")]
pub struct PyLlmResponse {
    /// Text content generated by the model.
    #[pyo3(get)]
    pub content: String,
    /// Total call latency in milliseconds.
    #[pyo3(get)]
    pub latency_ms: u64,
    /// Token-consumption statistics.
    #[pyo3(get)]
    pub usage: PyTokenUsage,
}

// LlmProxy

/// PyO3 bridge to the Rust `LlmRouter`, exposed to Python via `ctx.llm`.
///
/// Injected into `RuntimeContext`. Wrapped in `Arc<LlmRouter>` to allow
/// copy-free sharing between the runtime and agents.
///
/// # Full Python example
///
/// ```python
/// # Case 1: simple API (80% of agents)
/// response = await ctx.llm.chat(
///     system="You are a sales assistant.",
///     user=task.input.parts[0].text,
/// )
/// # response.content : str
/// # response.usage.prompt_tokens : int
///
/// # Case 2: multi-turn with history
/// response = await ctx.llm.complete([
///     {"role": "system",    "content": "Be concise."},
///     {"role": "user",      "content": "Summarize in 3 points."},
/// ])
///
/// # Case 3: streaming (async iterator)
/// async for chunk in await ctx.llm.stream([{"role": "user", "content": "..."}]):
///     print(chunk)
///
/// # Case 4: automatic ReAct loop
/// result = await ctx.llm.run_tools(
///     messages=[{"role": "user", "content": "Read the file."}],
///     tools=[{"name": "file_io", "description": "...", "parameters": {}}],
///     max_iterations=5,
/// )
///
/// # One-off backend override
/// response = await ctx.llm.chat(
///     system="...", user="...", backend="anthropic"
/// )
/// ```
#[pyclass(name = "LlmProxy")]
#[derive(Clone)]
pub struct LlmProxy {
    router: Arc<LlmRouter>,
    tool_helper: Arc<ToolCallHelper>,
    budget_view: Arc<StepBudgetView>,
    obs_config: Arc<ObservabilityConfig>,
    event_bus: Option<EventBusSender>,
    /// Current task; injected via [`with_task_context`] to tag
    /// `LlmCallStarted` events. `None` suppresses emission without breaking
    /// dispatch.
    task_id: Option<String>,
    /// Current agent; same role as `task_id`.
    agent_id: Option<String>,
    /// Run this proxy belongs to; tags `LlmCallStarted` for audit correlation.
    run_id: Option<apollia_core::events::RunId>,
}

impl LlmProxy {
    /// Creates an `LlmProxy` to inject into the Python `RuntimeContext`.
    ///
    /// Called when the agent context is initialized.
    /// `event_bus` is `None` when no Supervisor is active (unit tests).
    pub fn new(
        router: Arc<LlmRouter>,
        tool_helper: Arc<ToolCallHelper>,
        budget_view: Arc<StepBudgetView>,
        obs_config: Arc<ObservabilityConfig>,
        event_bus: Option<EventBusSender>,
    ) -> Self {
        Self {
            router,
            tool_helper,
            budget_view,
            obs_config,
            event_bus,
            task_id: None,
            agent_id: None,
            run_id: None,
        }
    }

    /// Binds this proxy to the current execution identity for observability.
    /// Without this setter, `LlmCallStarted` events are not emitted (but
    /// `complete_with_observability` still emits `LlmCallCompleted` /
    /// `LlmCallFailed` on the router side).
    pub fn with_task_context(mut self, task_id: String, agent_id: String) -> Self {
        self.task_id = Some(task_id);
        self.agent_id = Some(agent_id);
        self
    }

    /// Binds this proxy to the run it executes within, so `LlmCallStarted`
    /// events can be attributed to the run for audit. `None` leaves the call
    /// uncorrelated.
    pub fn with_run_id(mut self, run_id: Option<apollia_core::events::RunId>) -> Self {
        self.run_id = run_id;
        self
    }

    /// Charge one reasoning step against the shared budget (Direct path).
    ///
    /// Returns the Python error to raise when the step dimension is already
    /// spent, otherwise advances the shared step counter. This enforces
    /// `max_steps` for a Python agent's `ctx.llm` calls (principle #7). Outside
    /// the Direct path the view is unlimited, so this is a no-op increment.
    fn charge_step(&self) -> PyResult<()> {
        if self.budget_view.is_exhausted() {
            return Err(PyRuntimeError::new_err(
                "step budget exhausted: max_steps reached",
            ));
        }
        self.budget_view.increment_steps();
        Ok(())
    }

    /// Emits `RuntimeEvent::LlmCallStarted` if both bus and task_id are set.
    fn emit_started(&self, backend: &str, model: &str, messages_count: u32, prompt_chars: u64) {
        if let (Some(bus), Some(task_id), Some(agent_id)) = (
            self.event_bus.as_ref(),
            self.task_id.as_ref(),
            self.agent_id.as_ref(),
        ) {
            let _ = bus.send(apollia_core::events::RuntimeEvent::LlmCallStarted {
                task_id: task_id.clone().into(),
                agent_id: agent_id.clone().into(),
                step_id: None,
                backend: backend.to_string(),
                model: model.to_string(),
                messages_count,
                prompt_chars,
                run_id: self.run_id.clone(),
            });
        }
    }
}

#[pymethods]
impl LlmProxy {
    /// Name of the default LLM backend configured in `apollia.toml`.
    ///
    /// Python property `ctx.llm.default_backend`.
    /// Returns an empty string if no backend is configured.
    #[getter]
    fn default_backend(&self) -> String {
        self.router.default_name().to_string()
    }

    /// Simplified LLM call: system prompt + user message.
    ///
    /// Automatically builds `[ChatMessage::system(system), ChatMessage::user(user)]`.
    /// `backend` overrides the default backend configured in `apollia.toml`.
    /// `temperature`, `max_tokens`, and `seed` are optional sampling overrides;
    /// when left `None` the per-model defaults apply.
    ///
    /// Returns a Python awaitable resolving to `LlmResponse`.
    // The parameter list mirrors the Python-facing signature (backend + sampling
    // overrides); PyO3 requires them flat, so they cannot be grouped into a struct.
    #[allow(clippy::too_many_arguments)]
    #[pyo3(signature = (system, user, *, backend = None, temperature = None, max_tokens = None, seed = None))]
    fn chat<'py>(
        &self,
        py: Python<'py>,
        system: String,
        user: String,
        backend: Option<String>,
        temperature: Option<f32>,
        max_tokens: Option<u32>,
        seed: Option<u64>,
    ) -> PyResult<Bound<'py, PyAny>> {
        // Charge one step against the budget before dispatch (Direct path).
        self.charge_step()?;

        // Emit LlmCallStarted before dispatch.
        let prompt_chars = (system.chars().count() + user.chars().count()) as u64;
        let backend_label = backend
            .as_deref()
            .unwrap_or_else(|| self.router.default_name())
            .to_string();
        self.emit_started(&backend_label, "<resolved-by-router>", 2, prompt_chars);

        let router = Arc::clone(&self.router);
        let obs = Arc::clone(&self.obs_config);
        let bus = self.event_bus.clone();
        let run_id = self.run_id.clone();
        let capture_backend = backend_label.clone();

        pyo3_async_runtimes::tokio::future_into_py(py, async move {
            // Inject the authoritative current-date and host-environment
            // blocks at the top of the system message so the LLM never falls
            // back to its training cutoff for "today"-type queries nor guesses
            // the host OS. Mirrors what Chat Libre's `build_system_prompt` does.
            let system_with_context = prepend_context_blocks(&system);
            let req = CompletionRequest {
                messages: vec![
                    ChatMessage::system(system_with_context),
                    ChatMessage::user(user),
                ],
                temperature,
                max_tokens,
                seed,
                ..Default::default()
            };
            let resp = router
                .complete_with_observability(backend.as_deref(), req, bus.as_ref(), &obs)
                .await
                .map_err(llm_err_to_py)?;
            emit_llm_capture(&bus, &run_id, &capture_backend, &resp);

            Python::with_gil(|py| {
                let usage = PyTokenUsage {
                    prompt_tokens: resp.usage.prompt_tokens,
                    completion_tokens: resp.usage.completion_tokens,
                    cost_usd: resp.usage.cost_usd,
                };
                let py_resp = PyLlmResponse {
                    content: resp.content,
                    latency_ms: resp.latency_ms,
                    usage,
                };
                Py::new(py, py_resp).map(|p| p.into_any())
            })
        })
    }

    /// Batch a shared-prefix prompt over many items (`ctx.llm.map`).
    ///
    /// Each item is completed as `[system(prefix), user(item)]`, so the system
    /// message is byte-identical across items: on a batching backend
    /// (llama-server) this maximizes the prompt-prefix cache hit rate and lets
    /// continuous batching amortize the cost, while on other backends it degrades
    /// to bounded-concurrent calls (still correct). Apollia owns the concurrency
    /// and prefix sharing; the caller never touches slots or batching.
    ///
    /// Returns a Python awaitable resolving to a list of dicts, order-preserving,
    /// one per item: `{"index": int, "ok": bool, "text"?: str, "error"?: str,
    /// "usage"?: {...}}`. A single item failing never aborts the batch.
    // Flat parameters mirror the Python-facing signature (see `chat`).
    #[allow(clippy::too_many_arguments)]
    #[pyo3(signature = (prefix, items, *, backend = None, temperature = None, max_tokens = None, max_concurrency = None))]
    fn map<'py>(
        &self,
        py: Python<'py>,
        prefix: String,
        items: Vec<String>,
        backend: Option<String>,
        temperature: Option<f32>,
        max_tokens: Option<u32>,
        max_concurrency: Option<usize>,
    ) -> PyResult<Bound<'py, PyAny>> {
        let router = Arc::clone(&self.router);
        let obs = Arc::clone(&self.obs_config);
        let budget = Arc::clone(&self.budget_view);
        let bus = self.event_bus.clone();
        let concurrency = max_concurrency.unwrap_or(DEFAULT_MAP_CONCURRENCY).max(1);
        // Prepend the temporal and host-environment context ONCE to the shared
        // prefix so every item's system message stays byte-identical (see
        // method doc: prefix-cache hits).
        let system_prefix = prepend_context_blocks(&prefix);

        pyo3_async_runtimes::tokio::future_into_py(py, async move {
            let sem = Arc::new(tokio::sync::Semaphore::new(concurrency));
            let per_item = items.into_iter().enumerate().map(|(index, item)| {
                let router = Arc::clone(&router);
                let obs = Arc::clone(&obs);
                let budget = Arc::clone(&budget);
                let bus = bus.clone();
                let sem = Arc::clone(&sem);
                let backend = backend.clone();
                let system_prefix = system_prefix.clone();
                async move {
                    // Bound in-flight calls; the owned permit (no borrow across
                    // the await) is held for the item's duration. The semaphore is
                    // never closed, so acquire only fails in impossible states.
                    let _permit = Arc::clone(&sem).acquire_owned().await.ok();
                    // Honour a run-level budget already exhausted elsewhere rather
                    // than overrunning it; the item reports the reason instead.
                    // Each dispatched item is charged as one step (Direct path).
                    if budget.is_exhausted() {
                        return (index, Err("budget exhausted".to_string()));
                    }
                    budget.increment_steps();
                    let req = CompletionRequest {
                        messages: vec![ChatMessage::system(system_prefix), ChatMessage::user(item)],
                        temperature,
                        max_tokens,
                        ..Default::default()
                    };
                    let res = router
                        .complete_with_observability(backend.as_deref(), req, bus.as_ref(), &obs)
                        .await
                        .map_err(|e| e.to_string());
                    (index, res)
                }
            });

            let mut results = futures::future::join_all(per_item).await;
            results.sort_by_key(|(index, _)| *index);

            Python::with_gil(|py| {
                let out = pyo3::types::PyList::empty(py);
                for (index, res) in results {
                    let entry = pyo3::types::PyDict::new(py);
                    entry.set_item("index", index)?;
                    match res {
                        Ok(resp) => {
                            entry.set_item("ok", true)?;
                            entry.set_item("text", resp.content)?;
                            let usage = pyo3::types::PyDict::new(py);
                            usage.set_item("prompt_tokens", resp.usage.prompt_tokens)?;
                            usage.set_item("completion_tokens", resp.usage.completion_tokens)?;
                            usage.set_item("cost_usd", resp.usage.cost_usd)?;
                            entry.set_item("usage", usage)?;
                        }
                        Err(error) => {
                            entry.set_item("ok", false)?;
                            entry.set_item("error", error)?;
                        }
                    }
                    out.append(entry)?;
                }
                Ok::<_, PyErr>(out.into_any().unbind())
            })
        })
    }

    /// LLM call with full multi-turn history.
    ///
    /// `messages` is a list of dicts `{"role": "system"|"user"|"assistant"|"tool", "content": "..."}`.
    /// Returns a Python awaitable resolving to `LlmResponse`.
    ///
    /// Returns `PyValueError` if a message dict is invalid (missing or unknown role).
    ///
    /// `temperature`, `max_tokens`, and `seed` are optional sampling overrides;
    /// when left `None` the per-model defaults apply.
    // Flat parameters mirror the Python-facing signature (see `chat`).
    #[allow(clippy::too_many_arguments)]
    #[pyo3(signature = (messages, *, backend = None, temperature = None, max_tokens = None, seed = None))]
    fn complete<'py>(
        &self,
        py: Python<'py>,
        messages: Vec<PyObject>,
        backend: Option<String>,
        temperature: Option<f32>,
        max_tokens: Option<u32>,
        seed: Option<u64>,
    ) -> PyResult<Bound<'py, PyAny>> {
        // Synchronous conversion before crossing the async boundary.
        let chat_messages = messages
            .iter()
            .map(|obj| py_dict_to_chat_message(py, obj))
            .collect::<PyResult<Vec<_>>>()?;

        // Charge one step against the budget before dispatch (Direct path).
        self.charge_step()?;

        // Emit LlmCallStarted before dispatch.
        // MessageContent may carry plain text or tool_calls; we sum the
        // countable chars as a size proxy.
        let prompt_chars: u64 = chat_messages
            .iter()
            .map(|m| match &m.content {
                apollia_llm::types::MessageContent::Text(t) => t.chars().count() as u64,
                apollia_llm::types::MessageContent::ToolResult { content, .. } => {
                    content.chars().count() as u64
                }
                apollia_llm::types::MessageContent::WithToolCalls { text, .. } => {
                    text.chars().count() as u64
                }
            })
            .sum();
        let backend_label = backend
            .as_deref()
            .unwrap_or_else(|| self.router.default_name())
            .to_string();
        self.emit_started(
            &backend_label,
            "<resolved-by-router>",
            chat_messages.len() as u32,
            prompt_chars,
        );

        let router = Arc::clone(&self.router);
        let obs = Arc::clone(&self.obs_config);
        let bus = self.event_bus.clone();
        let run_id = self.run_id.clone();
        let capture_backend = backend_label.clone();

        pyo3_async_runtimes::tokio::future_into_py(py, async move {
            // Same temporal-context injection as `chat()`. If the first
            // message is a system message, prepend the block to its text.
            // Otherwise insert a fresh system message at index 0. Keeps
            // multi-turn agent calls grounded on the real wall clock.
            let messages = inject_temporal_context_into_messages(chat_messages);
            let req = CompletionRequest {
                messages,
                temperature,
                // Default a cap when the agent does not set one: an unbounded
                // completion lets a local model run to context-fill and appear
                // to hang forever (the onboarding-agent symptom). An agent that
                // needs a longer answer passes max_tokens explicitly.
                max_tokens: max_tokens.or(Some(4096)),
                seed,
                ..Default::default()
            };
            let resp = router
                .complete_with_observability(backend.as_deref(), req, bus.as_ref(), &obs)
                .await
                .map_err(llm_err_to_py)?;
            emit_llm_capture(&bus, &run_id, &capture_backend, &resp);

            Python::with_gil(|py| {
                let usage = PyTokenUsage {
                    prompt_tokens: resp.usage.prompt_tokens,
                    completion_tokens: resp.usage.completion_tokens,
                    cost_usd: resp.usage.cost_usd,
                };
                let py_resp = PyLlmResponse {
                    content: resp.content,
                    latency_ms: resp.latency_ms,
                    usage,
                };
                Py::new(py, py_resp).map(|p| p.into_any())
            })
        })
    }

    /// Automatic ReAct loop: LLM, tool(s), LLM, ..., final answer.
    ///
    /// `messages`: list of dicts `{"role": "...", "content": "..."}`.
    /// `tools`: list of dicts `{"name": "...", "description": "...", "parameters": {...}}`.
    /// `max_iterations`: guard rail, the maximum number of LLM calls (default: 5).
    ///
    /// Returns a Python awaitable resolving to `str` (the LLM's final answer
    /// after all tool calls have run).
    ///
    /// Raises `PyRuntimeError` if the agent budget is exhausted or
    /// `max_iterations` is reached.
    #[pyo3(signature = (messages, tools, max_iterations = 5))]
    fn run_tools<'py>(
        &self,
        py: Python<'py>,
        messages: Vec<PyObject>,
        tools: Vec<PyObject>,
        max_iterations: u32,
    ) -> PyResult<Bound<'py, PyAny>> {
        let chat_messages = messages
            .iter()
            .map(|obj| py_dict_to_chat_message(py, obj))
            .collect::<PyResult<Vec<_>>>()?;

        let tool_specs = tools
            .iter()
            .map(|obj| py_dict_to_tool_spec(py, obj))
            .collect::<PyResult<Vec<_>>>()?;

        let helper = Arc::clone(&self.tool_helper);
        let budget = Arc::clone(&self.budget_view);

        pyo3_async_runtimes::tokio::future_into_py(py, async move {
            let result = helper
                .run_tools(chat_messages, tool_specs, max_iterations, &budget)
                .await
                .map_err(llm_err_to_py)?;

            Python::with_gil(|py| result.into_py_any(py))
        })
    }

    /// Streaming LLM call: returns an async iterator yielding text chunks.
    ///
    /// Canonical streaming surface. Returns a [`PyTokenStream`]
    /// implementing the async iteration protocol (`__aiter__` / `__anext__`).
    /// Each chunk is yielded as soon as it arrives from the backend so the
    /// agent can emit real-time `ChatToken` events.
    ///
    /// Backends that cannot stream natively fall back to a single
    /// `complete()` call yielded as one chunk.
    ///
    /// # Example
    /// ```python
    /// async for chunk in await ctx.llm.stream(messages):
    ///     buffer += chunk
    ///     await ctx.emit_token(chunk)  # route to frontend
    /// ```
    // Flat parameters mirror the Python-facing signature (see `chat`).
    #[allow(clippy::too_many_arguments)]
    #[pyo3(signature = (messages, *, backend = None, temperature = None, max_tokens = None, seed = None))]
    fn stream<'py>(
        &self,
        py: Python<'py>,
        messages: Vec<PyObject>,
        backend: Option<String>,
        temperature: Option<f32>,
        max_tokens: Option<u32>,
        seed: Option<u64>,
    ) -> PyResult<Bound<'py, PyAny>> {
        let chat_messages = messages
            .iter()
            .map(|obj| py_dict_to_chat_message(py, obj))
            .collect::<PyResult<Vec<_>>>()?;

        let router = Arc::clone(&self.router);
        let obs = Arc::clone(&self.obs_config);
        let bus = self.event_bus.clone();

        pyo3_async_runtimes::tokio::future_into_py(py, async move {
            // REASON: bounded so a slow Python consumer applies backpressure onto
            // the LLM stream (the forwarder awaits on a full buffer) instead of
            // letting a fast backend grow the queue without limit. Token chunks
            // are small; 1024 leaves generous slack before backpressure engages.
            let (tx, rx) = mpsc::channel::<Result<String, LlmError>>(TOKEN_STREAM_BUFFER_CAPACITY);

            // Background task: stream from the backend and forward onto tx.
            tokio::spawn(async move {
                forward_stream(StreamForward {
                    router,
                    obs,
                    bus,
                    backend,
                    chat_messages,
                    temperature,
                    max_tokens,
                    seed,
                    tx,
                })
                .await;
                // Dropping tx closes the channel, so __anext__ raises
                // PyStopAsyncIteration.
            });

            Python::with_gil(|py| {
                let stream = PyTokenStream {
                    rx: Arc::new(AsyncMutex::new(rx)),
                };
                Py::new(py, stream).map(|p| p.into_any())
            })
        })
    }
}

/// Emit `LlmResponseCaptured` so a task-mode LLM completion is journaled (the
/// audit journal only captures completions carrying a `run_id`), enabling
/// `audit replay` and putting the model's output in the tamper-evident trail,
/// mirroring what the chat agent does.
fn emit_llm_capture(
    bus: &Option<EventBusSender>,
    run_id: &Option<apollia_core::events::RunId>,
    backend: &str,
    resp: &apollia_llm::types::CompletionResponse,
) {
    let (Some(bus), Some(run_id)) = (bus.as_ref(), run_id.as_ref()) else {
        return;
    };
    let tool_calls: Vec<serde_json::Value> = resp
        .tool_calls
        .iter()
        .map(|tc| serde_json::json!({ "id": tc.id, "name": tc.name, "arguments": tc.arguments }))
        .collect();
    let _ = bus.send(apollia_core::events::RuntimeEvent::LlmResponseCaptured {
        run_id: run_id.clone(),
        backend: backend.to_string(),
        model: String::new(),
        content: resp.content.clone(),
        tool_calls,
        prompt_tokens: resp.usage.prompt_tokens,
        completion_tokens: resp.usage.completion_tokens,
        cost_usd: resp.usage.cost_usd,
        stream_truncated: false,
    });
}

/// Owned inputs for [`forward_stream`], the background task feeding a
/// [`PyTokenStream`].
struct StreamForward {
    router: Arc<LlmRouter>,
    obs: Arc<ObservabilityConfig>,
    bus: Option<EventBusSender>,
    backend: Option<String>,
    chat_messages: Vec<ChatMessage>,
    temperature: Option<f32>,
    max_tokens: Option<u32>,
    seed: Option<u64>,
    tx: mpsc::Sender<Result<String, LlmError>>,
}

/// Streams chunks from the resolved backend and forwards each one onto `tx`.
///
/// Backends that cannot stream natively fall back to a single `complete()`
/// call forwarded as one chunk. Sends a `BackendUnavailable` error when no
/// backend matches.
async fn forward_stream(f: StreamForward) {
    let StreamForward {
        router,
        obs,
        bus,
        backend,
        chat_messages,
        temperature,
        max_tokens,
        seed,
        tx,
    } = f;
    let backend_key = backend.as_deref();
    let Some(model) = router.get(backend_key) else {
        let _ = tx
            .send(Err(LlmError::BackendUnavailable {
                backend: backend_key.unwrap_or("(default)").to_string(),
                reason: "no matching backend".to_string(),
            }))
            .await;
        return;
    };

    let req = CompletionRequest {
        messages: chat_messages.clone(),
        temperature,
        max_tokens,
        seed,
        ..Default::default()
    };
    match model.stream(req).await {
        Ok(mut stream) => {
            while let Some(chunk) = stream.next().await {
                match chunk {
                    Ok(StreamChunk::Text(text)) => {
                        if tx.send(Ok(text)).await.is_err() {
                            break;
                        }
                    }
                    Ok(StreamChunk::ToolCall(_)) => {
                        // Tool calls within the stream are not surfaced
                        // to Python; assistants parse JSON from the
                        // accumulated text.
                    }
                    Ok(StreamChunk::Usage(_)) => {
                        // Token accounting is not surfaced on this text-only
                        // Python bridge; drop the terminal usage chunk.
                    }
                    Ok(StreamChunk::Timings(_)) => {
                        // Same: engine timings are observed where they are
                        // produced, not forwarded to Python.
                    }
                    Err(e) => {
                        let _ = tx.send(Err(e)).await;
                        break;
                    }
                }
            }
        }
        // Fallback: backend does not support stream(),
        // so call complete() and forward as a single chunk.
        Err(_) => {
            let fallback_req = CompletionRequest {
                messages: chat_messages,
                temperature,
                max_tokens,
                seed,
                ..Default::default()
            };
            match router
                .complete_with_observability(backend_key, fallback_req, bus.as_ref(), &obs)
                .await
            {
                Ok(resp) => {
                    let _ = tx.send(Ok(resp.content)).await;
                }
                Err(e) => {
                    let _ = tx.send(Err(e)).await;
                }
            }
        }
    }
}

// PyTokenStream: Python async iterator exposing a chunk-by-chunk LLM stream

/// Python async iterator yielding text chunks from a streamed LLM call.
///
/// Implements the `__aiter__` + `__anext__` protocol. Raises
/// `StopAsyncIteration` when the stream is exhausted, `RuntimeError` on a
/// backend error.
#[pyclass(name = "TokenStream")]
pub struct PyTokenStream {
    rx: Arc<AsyncMutex<mpsc::Receiver<Result<String, LlmError>>>>,
}

#[pymethods]
impl PyTokenStream {
    fn __aiter__(slf: PyRef<'_, Self>) -> PyRef<'_, Self> {
        slf
    }

    fn __anext__<'py>(slf: PyRef<'py, Self>, py: Python<'py>) -> PyResult<Bound<'py, PyAny>> {
        let rx = Arc::clone(&slf.rx);
        pyo3_async_runtimes::tokio::future_into_py(py, async move {
            let mut guard = rx.lock().await;
            match guard.recv().await {
                Some(Ok(chunk)) => Ok(chunk),
                Some(Err(e)) => Err(PyRuntimeError::new_err(e.to_string())),
                None => Err(PyStopAsyncIteration::new_err("stream exhausted")),
            }
        })
    }
}

// Private conversion functions

/// Render the host-environment block for the bridge layer.
///
/// Gathering lives in `apollia-tools`, rendering in `apollia-prompts`; the
/// workspace root is not known at this layer, so the block reports the
/// generic session-root wording.
fn host_environment_block() -> String {
    let env = apollia_tools::host_env::gather_host_environment(None);
    let shell = env.posix_shell.as_ref().map(|p| p.display().to_string());
    apollia_prompts::blocks::environment_block(
        env.os,
        env.os_version.as_deref(),
        env.arch,
        shell.as_deref(),
        None,
    )
}

/// Prepend the temporal block and the host-environment block to `system`.
///
/// Both are authoritative "here and now" facts and sit at the top, in that
/// order, mirroring Chat Libre's `build_system_prompt`.
fn prepend_context_blocks(system: &str) -> String {
    apollia_core::temporal_context::prepend_temporal_context(&format!(
        "{}\n\n{}",
        host_environment_block(),
        system
    ))
}

/// Inject the authoritative temporal + host-environment blocks into a
/// multi-turn message list. If the first message is a `system` role, prepend
/// the blocks to its text. Otherwise insert a brand-new `system` message at
/// index 0.
///
/// Keeps Python agents on the real wall clock for "today"/"now"/relative
/// dates, and on the real host OS for shell and path decisions, without
/// requiring the agent author to remember anything.
fn inject_temporal_context_into_messages(mut messages: Vec<ChatMessage>) -> Vec<ChatMessage> {
    use apollia_llm::types::{MessageContent, Role};

    let is_first_system = messages
        .first()
        .map(|m| matches!(m.role, Role::System))
        .unwrap_or(false);

    if is_first_system {
        if let Some(first) = messages.first_mut() {
            if let MessageContent::Text(ref text) = first.content {
                let merged = prepend_context_blocks(text);
                first.content = MessageContent::Text(merged);
            }
            // Non-text system content (rare): leave untouched and prepend
            // a fresh system block ahead of it as a safety net.
        }
    } else {
        messages.insert(
            0,
            ChatMessage::system(format!(
                "{}\n{}",
                apollia_core::temporal_context::temporal_context_block(),
                host_environment_block()
            )),
        );
    }
    messages
}

/// Converts a Python dict `{"role": "...", "content": ...}` into a `ChatMessage`.
///
/// `content` can be:
/// - a `str` (text fast path);
/// - a `list[dict]` of typed blocks (vision typing), each block being either
///   `{"type": "text", "text": "..."}` or
///   `{"type": "image", "source": {"type": "base64"|"url", ...}}`.
///   Text blocks are concatenated (joined with `\n\n`). Image blocks are
///   annotated as `[image: <media_type|url>]` because no LLM backend reachable
///   via `LlmProxy` supports vision today (the local engine is text-only).
///   The JSON shape is preserved as received so a future cloud vision backend
///   can be wired in without breaking the API.
///
/// Returns `PyValueError` if `role` is missing or matches no known role
/// (`system` / `user` / `assistant` / `tool`).
fn py_dict_to_chat_message(py: Python<'_>, obj: &PyObject) -> PyResult<ChatMessage> {
    let bound = obj.bind(py);

    let role_str: String = bound
        .get_item("role")
        .map_err(|_| PyValueError::new_err("message dict missing 'role' key"))?
        .extract()
        .map_err(|e| PyValueError::new_err(format!("'role' must be a str: {e}")))?;

    let content_obj = bound
        .get_item("content")
        .map_err(|_| PyValueError::new_err("message dict missing 'content' key"))?;

    // Fast path: plain string content.
    let content_str: String = match content_obj.extract::<String>() {
        Ok(s) => s,
        Err(_) => {
            // Slow path: list[MessageContent], flatten to text representation.
            flatten_multimodal_content(py, &content_obj)?
        }
    };

    let role = match role_str.as_str() {
        "system" => Role::System,
        "user" => Role::User,
        "assistant" => Role::Assistant,
        "tool" => Role::Tool,
        other => {
            return Err(PyValueError::new_err(format!(
                "unknown role '{other}' - expected system/user/assistant/tool"
            )))
        }
    };

    Ok(ChatMessage {
        role,
        content: MessageContent::Text(content_str),
        cache_control: None,
    })
}

/// Flattens a list of multimodal content blocks (TextContent / ImageContent)
/// to a textual representation suitable for text-only backends.
///
/// - `{"type": "text", "text": "..."}` ⇒ raw text fragment.
/// - `{"type": "image", "source": {...}}` ⇒ `[image: <descriptor>]` marker
///   where descriptor is the `media_type` for base64 sources or the truncated
///   URL for URL sources.
///
/// Returns `PyValueError` if a block is malformed (missing `type`, unknown
/// kind, or non-iterable input).
fn flatten_multimodal_content(py: Python<'_>, content: &Bound<'_, PyAny>) -> PyResult<String> {
    use pyo3::types::PyList;

    if !content.is_instance_of::<PyList>() {
        return Err(PyValueError::new_err(
            "'content' must be either a str or a list of content blocks",
        ));
    }
    let list = content
        .downcast::<PyList>()
        .map_err(|e| PyValueError::new_err(format!("'content' is not a valid list: {e}")))?;

    let json_mod = py
        .import("json")
        .map_err(|e| PyRuntimeError::new_err(format!("import json: {e}")))?;

    let mut fragments: Vec<String> = Vec::with_capacity(list.len());
    for item in list.iter() {
        // Each block must be a dict with a 'type' key.
        let type_str: String = item
            .get_item("type")
            .map_err(|_| PyValueError::new_err("content block missing 'type' key"))?
            .extract()
            .map_err(|e| PyValueError::new_err(format!("'type' must be a str: {e}")))?;

        match type_str.as_str() {
            "text" => {
                let text: String = item
                    .get_item("text")
                    .map_err(|_| PyValueError::new_err("text block missing 'text' key"))?
                    .extract()
                    .map_err(|e| PyValueError::new_err(format!("'text' must be a str: {e}")))?;
                fragments.push(text);
            }
            "image" => {
                // Pull a short descriptor from `source` for the placeholder. The
                // full JSON is also captured (truncated) so a future vision-capable
                // backend can reconstruct the payload if we expose a richer
                // MessageContent variant later.
                let source = item
                    .get_item("source")
                    .map_err(|_| PyValueError::new_err("image block missing 'source' key"))?;
                let descriptor = source
                    .get_item("media_type")
                    .ok()
                    .and_then(|v| v.extract::<String>().ok())
                    .or_else(|| {
                        source
                            .get_item("url")
                            .ok()
                            .and_then(|v| v.extract::<String>().ok())
                            .map(|u| truncate(&u, 80))
                    })
                    .unwrap_or_else(|| "unknown".to_string());
                fragments.push(format!("[image: {descriptor}]"));
                // Tracing: let operators discover that an image was sent to a
                // text-only backend so they can switch to a cloud vision model.
                tracing::warn!(
                    media = %descriptor,
                    "vision content received by LlmProxy - current backends are text-only, \
                     image was flattened to a placeholder"
                );
                // Drop the dumped JSON if we ever need it for debugging.
                let _ = json_mod;
            }
            other => {
                return Err(PyValueError::new_err(format!(
                    "unknown content block type '{other}' - expected 'text' or 'image'"
                )));
            }
        }
    }

    Ok(fragments.join("\n\n"))
}

/// Truncates a string to at most `max_chars` characters with an ellipsis.
fn truncate(s: &str, max_chars: usize) -> String {
    if s.chars().count() <= max_chars {
        return s.to_string();
    }
    let mut out: String = s.chars().take(max_chars).collect();
    out.push('…');
    out
}

/// Converts a Python dict `{"name": "...", "description": "...", "parameters": {...}}`
/// into a `ToolSpec`.
///
/// `parameters` is optional; defaults to `{}` when absent.
/// Returns `PyValueError` if `name` or `description` is missing.
fn py_dict_to_tool_spec(py: Python<'_>, obj: &PyObject) -> PyResult<ToolSpec> {
    let bound = obj.bind(py);

    let name: String = bound
        .get_item("name")
        .map_err(|_| PyValueError::new_err("tool spec dict missing 'name' key"))?
        .extract()
        .map_err(|e| PyValueError::new_err(format!("'name' must be a str: {e}")))?;

    let description: String = bound
        .get_item("description")
        .map_err(|_| PyValueError::new_err("tool spec dict missing 'description' key"))?
        .extract()
        .map_err(|e| PyValueError::new_err(format!("'description' must be a str: {e}")))?;

    // `parameters` is optional; serialize via json.dumps to handle any
    // Python type (dict, list, etc.)
    let parameters: serde_json::Value = match bound.get_item("parameters") {
        Ok(params_obj) => {
            let json_mod = py
                .import("json")
                .map_err(|e| PyRuntimeError::new_err(format!("import json: {e}")))?;
            let json_str: String = json_mod
                .call_method1("dumps", (params_obj,))
                .map_err(|e| PyRuntimeError::new_err(format!("json.dumps failed: {e}")))?
                .extract()
                .map_err(|e| PyRuntimeError::new_err(format!("extract failed: {e}")))?;
            serde_json::from_str(&json_str)
                .map_err(|e| PyValueError::new_err(format!("parameters JSON parse: {e}")))?
        }
        Err(_) => serde_json::json!({}),
    };

    Ok(ToolSpec {
        name,
        description,
        parameters,
    })
}

/// Maps an [`LlmError`] to a `PyRuntimeError`.
fn llm_err_to_py(e: LlmError) -> PyErr {
    PyRuntimeError::new_err(e.to_string())
}

// Tests

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn emit_llm_capture_sends_response_captured_with_run_id() {
        // GIVEN a bus, a run_id, and a completion response
        let (tx, mut rx) = tokio::sync::broadcast::channel(8);
        let run_id = apollia_core::events::RunId::new();
        let resp = apollia_llm::types::CompletionResponse {
            engine_timings: None,
            content: "hello world".to_string(),
            tool_calls: vec![],
            usage: apollia_llm::types::TokenUsage {
                prompt_tokens: 10,
                completion_tokens: 5,
                cost_usd: Some(0.01),
                ..Default::default()
            },
            finish_reason: apollia_llm::types::FinishReason::Stop,
            latency_ms: 42,
            ttft_ms: None,
        };

        // WHEN a capture is emitted
        emit_llm_capture(&Some(tx), &Some(run_id.clone()), "test-backend", &resp);

        // THEN an LlmResponseCaptured event carries the run_id + content
        let ev = rx.try_recv().expect("event expected");
        match ev {
            apollia_core::events::RuntimeEvent::LlmResponseCaptured {
                run_id: rid,
                content,
                completion_tokens,
                ..
            } => {
                assert_eq!(rid, run_id);
                assert_eq!(content, "hello world");
                assert_eq!(completion_tokens, 5);
            }
            other => panic!("expected LlmResponseCaptured, got {other:?}"),
        }
    }

    #[test]
    fn emit_llm_capture_noop_without_run_id() {
        // GIVEN a bus but no run_id (a run-agnostic call)
        let (tx, mut rx) = tokio::sync::broadcast::channel(8);
        let resp = apollia_llm::types::CompletionResponse {
            engine_timings: None,
            content: "x".to_string(),
            tool_calls: vec![],
            usage: apollia_llm::types::TokenUsage {
                prompt_tokens: 0,
                completion_tokens: 0,
                cost_usd: None,
                ..Default::default()
            },
            finish_reason: apollia_llm::types::FinishReason::Stop,
            latency_ms: 0,
            ttft_ms: None,
        };

        // WHEN / THEN no event is emitted when run_id is absent
        emit_llm_capture(&Some(tx), &None, "b", &resp);
        assert!(rx.try_recv().is_err(), "no event without a run_id");
    }

    /// `py_dict_to_chat_message`: role "user" converts correctly.
    #[test]
    fn test_py_dict_to_chat_message_user() {
        // GIVEN
        pyo3::prepare_freethreaded_python();
        Python::with_gil(|py| {
            let dict = pyo3::types::PyDict::new(py);
            dict.set_item("role", "user").unwrap();
            dict.set_item("content", "bonjour").unwrap();
            // WHEN
            let msg = py_dict_to_chat_message(py, &dict.into()).unwrap();
            // THEN
            assert_eq!(msg.role, Role::User);
            assert!(matches!(msg.content, MessageContent::Text(ref t) if t == "bonjour"));
        });
    }

    /// Invalid role yields `PyValueError`.
    #[test]
    fn test_py_dict_to_chat_message_invalid_role() {
        // GIVEN
        pyo3::prepare_freethreaded_python();
        Python::with_gil(|py| {
            let dict = pyo3::types::PyDict::new(py);
            dict.set_item("role", "invalid_role").unwrap();
            dict.set_item("content", "...").unwrap();
            // WHEN
            let result = py_dict_to_chat_message(py, &dict.into());
            // THEN
            assert!(result.is_err());
            let err = result.unwrap_err();
            assert!(err.to_string().contains("unknown role"));
        });
    }

    /// `py_dict_to_tool_spec`: fields extracted correctly.
    #[test]
    fn test_py_dict_to_tool_spec() {
        // GIVEN
        pyo3::prepare_freethreaded_python();
        Python::with_gil(|py| {
            let dict = pyo3::types::PyDict::new(py);
            dict.set_item("name", "file_io").unwrap();
            dict.set_item("description", "lit un fichier").unwrap();
            dict.set_item("parameters", pyo3::types::PyDict::new(py))
                .unwrap();
            // WHEN
            let spec = py_dict_to_tool_spec(py, &dict.into()).unwrap();
            // THEN
            assert_eq!(spec.name, "file_io");
            assert_eq!(spec.description, "lit un fichier");
        });
    }

    /// Missing "role" key yields `PyValueError`.
    #[test]
    fn test_py_dict_to_chat_message_missing_role() {
        // GIVEN
        pyo3::prepare_freethreaded_python();
        Python::with_gil(|py| {
            let dict = pyo3::types::PyDict::new(py);
            dict.set_item("content", "test").unwrap();
            // WHEN: no "role" key
            let result = py_dict_to_chat_message(py, &dict.into());
            // THEN
            assert!(result.is_err());
        });
    }

    /// role "system" converts correctly.
    #[test]
    fn test_py_dict_to_chat_message_system() {
        // GIVEN
        pyo3::prepare_freethreaded_python();
        Python::with_gil(|py| {
            let dict = pyo3::types::PyDict::new(py);
            dict.set_item("role", "system").unwrap();
            dict.set_item("content", "tu es utile").unwrap();
            // WHEN
            let msg = py_dict_to_chat_message(py, &dict.into()).unwrap();
            // THEN
            assert_eq!(msg.role, Role::System);
        });
    }

    /// Missing "name" key in tool spec yields `PyValueError`.
    #[test]
    fn test_py_dict_to_tool_spec_missing_name() {
        // GIVEN
        pyo3::prepare_freethreaded_python();
        Python::with_gil(|py| {
            let dict = pyo3::types::PyDict::new(py);
            dict.set_item("description", "test").unwrap();
            // WHEN: no "name" key
            let result = py_dict_to_tool_spec(py, &dict.into());
            // THEN
            assert!(result.is_err());
        });
    }

    /// Multi-modal content list with a text block is accepted and flattened.
    #[test]
    fn test_py_dict_to_chat_message_multimodal_text_only() {
        pyo3::prepare_freethreaded_python();
        Python::with_gil(|py| {
            // GIVEN a message whose `content` is a list[TextContent]
            let dict = pyo3::types::PyDict::new(py);
            dict.set_item("role", "user").unwrap();
            let text_block = pyo3::types::PyDict::new(py);
            text_block.set_item("type", "text").unwrap();
            text_block.set_item("text", "describe").unwrap();
            let parts = pyo3::types::PyList::new(py, &[text_block]).unwrap();
            dict.set_item("content", parts).unwrap();

            // WHEN converted
            let msg = py_dict_to_chat_message(py, &dict.into()).unwrap();

            // THEN the text fragment survives intact
            assert_eq!(msg.role, Role::User);
            assert!(matches!(msg.content, MessageContent::Text(ref t) if t == "describe"));
        });
    }

    /// Image content blocks are flattened to a placeholder.
    #[test]
    fn test_py_dict_to_chat_message_multimodal_with_image() {
        pyo3::prepare_freethreaded_python();
        Python::with_gil(|py| {
            // GIVEN a message with [text, image_base64]
            let dict = pyo3::types::PyDict::new(py);
            dict.set_item("role", "user").unwrap();

            let text_block = pyo3::types::PyDict::new(py);
            text_block.set_item("type", "text").unwrap();
            text_block
                .set_item("text", "what is in this picture?")
                .unwrap();

            let source = pyo3::types::PyDict::new(py);
            source.set_item("type", "base64").unwrap();
            source.set_item("media_type", "image/png").unwrap();
            source.set_item("data", "AAAA").unwrap();
            let image_block = pyo3::types::PyDict::new(py);
            image_block.set_item("type", "image").unwrap();
            image_block.set_item("source", source).unwrap();

            let parts = pyo3::types::PyList::new(py, &[text_block, image_block]).unwrap();
            dict.set_item("content", parts).unwrap();

            // WHEN converted
            let msg = py_dict_to_chat_message(py, &dict.into()).unwrap();

            // THEN the image is annotated as a placeholder alongside the text
            assert_eq!(msg.role, Role::User);
            let text = match msg.content {
                MessageContent::Text(t) => t,
                _ => panic!("expected text content"),
            };
            assert!(text.contains("what is in this picture?"));
            assert!(text.contains("[image: image/png]"));
        });
    }

    /// Unknown block type raises PyValueError.
    #[test]
    fn test_py_dict_to_chat_message_unknown_block_type() {
        pyo3::prepare_freethreaded_python();
        Python::with_gil(|py| {
            let dict = pyo3::types::PyDict::new(py);
            dict.set_item("role", "user").unwrap();
            let bogus = pyo3::types::PyDict::new(py);
            bogus.set_item("type", "video").unwrap();
            let parts = pyo3::types::PyList::new(py, &[bogus]).unwrap();
            dict.set_item("content", parts).unwrap();

            let result = py_dict_to_chat_message(py, &dict.into());
            assert!(result.is_err());
            let err = result.unwrap_err();
            assert!(err.to_string().contains("unknown content block type"));
        });
    }

    /// `parameters` absent yields default `{}`.
    #[test]
    fn test_py_dict_to_tool_spec_parameters_optional() {
        // GIVEN
        pyo3::prepare_freethreaded_python();
        Python::with_gil(|py| {
            let dict = pyo3::types::PyDict::new(py);
            dict.set_item("name", "echo").unwrap();
            dict.set_item("description", "echo input").unwrap();
            // WHEN: no "parameters" key
            let spec = py_dict_to_tool_spec(py, &dict.into()).unwrap();
            // THEN
            assert_eq!(spec.parameters, serde_json::json!({}));
        });
    }
}
