#!/usr/bin/env python3
"""Pin the two derived automation scripts to the output of their generators.

`scripts/automation/master-det.json` is generated by `tools/regen_master.py`
from the per-page `<page>-det.json` scripts, and `master-det-scan.json` is
generated from the master by `tools/make_scan.py` with its default arguments
(the declared contract of the tracked file). Both are committed, so both can
drift from what their generator would produce: the scan sat 201 steps stale
for twelve days because its generator answered exit 0 whether the tracked
file matched or not.

This guard regenerates both, in a temporary directory for the scan so the
tree is never written, and compares. Any difference is a red.

Usage:
    python3 scripts/check_automation_derived.py

Exit codes: 0 both derived files match their generator, 1 a derived file
drifted (or is missing), 2 a generator is missing or crashed (nothing
measured, which is not a pass).
"""

import json
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
TOOLS = REPO_ROOT / "scripts/automation/tools"
SCRIPTS = REPO_ROOT / "scripts/automation"


def main() -> int:
    regen = TOOLS / "regen_master.py"
    make_scan = TOOLS / "make_scan.py"
    for generator in (regen, make_scan):
        if not generator.is_file():
            print(f"NOTHING MEASURED: generator {generator.relative_to(REPO_ROOT)} "
                  f"is missing")
            return 2

    failed = False

    # master-det.json: the generator's dry run compares content and answers
    # 0 identical, 1 drift.
    run = subprocess.run(
        [sys.executable, str(regen)],
        cwd=REPO_ROOT,
        capture_output=True,
        text=True,
    )
    if run.returncode == 0:
        print("master-det.json matches regen_master.py")
    elif run.returncode == 1:
        print("DRIFT: master-det.json is not the output of regen_master.py. "
              "Regenerate it with: python3 scripts/automation/tools/regen_master.py --write")
        print(run.stdout.strip())
        failed = True
    else:
        print(f"NOTHING MEASURED: regen_master.py exited {run.returncode}:\n"
              f"{run.stdout}{run.stderr}")
        return 2

    # master-det-scan.json: regenerate in a throwaway tree with the default
    # arguments and compare, so the tracked file is never rewritten.
    tracked = SCRIPTS / "master-det-scan.json"
    master = SCRIPTS / "master-det.json"
    if not tracked.is_file():
        print("DRIFT: master-det-scan.json is missing. Regenerate it with: "
              "python3 scripts/automation/tools/make_scan.py")
        failed = True
    else:
        with tempfile.TemporaryDirectory() as tmp:
            scratch = Path(tmp) / "scripts/automation"
            scratch.mkdir(parents=True)
            shutil.copy(master, scratch / "master-det.json")
            run = subprocess.run(
                [sys.executable, str(make_scan)],
                cwd=tmp,
                capture_output=True,
                text=True,
            )
            produced = scratch / "master-det-scan.json"
            if run.returncode != 0 or not produced.is_file():
                print(f"NOTHING MEASURED: make_scan.py exited {run.returncode}:\n"
                      f"{run.stdout}{run.stderr}")
                return 2
            if json.load(open(produced)) == json.load(open(tracked)):
                print("master-det-scan.json matches make_scan.py (default arguments)")
            else:
                print("DRIFT: master-det-scan.json is not the output of make_scan.py "
                      "on the current master-det.json. Regenerate it with: "
                      "python3 scripts/automation/tools/make_scan.py")
                failed = True

    if failed:
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
