"""Agent scaffolding - generates a ready-to-run agent from a template.

All scaffolds use the canonical decorator-first SDK (``@agent``, ``@skill``,
``@on_message``, ``@orchestrated``). No legacy base classes are produced.
"""

from __future__ import annotations

import argparse
import os
import sys
from pathlib import Path

# Public agent types map directly to the new decorator surfaces:
#   react           -> @agent + a single @skill using the ``react()`` helper
#   conversational  -> @agent + @on_message
#   orchestrated    -> @agent + @orchestrated
#   worker          -> @agent + one @skill (A2A-exposed)
VALID_AGENT_TYPES = ("react", "conversational", "orchestrated", "worker")

# ---------------------------------------------------------------------------
# Name conversions
# ---------------------------------------------------------------------------


def to_class_name(name: str) -> str:
    """Convert a kebab-case name to PascalCase with ``Agent`` suffix.

    The suffix is appended only when *name* does not already end with
    ``-agent`` or ``_agent``.

    Args:
        name: Name in kebab-case (e.g. ``'my-agent'``).

    Returns:
        PascalCase name ending in ``Agent`` (e.g. ``'MyAgent'``).
    """
    pascal = "".join(part.capitalize() for part in name.replace("_", "-").split("-"))
    if not pascal.lower().endswith("agent"):
        pascal += "Agent"
    return pascal


def to_module_name(name: str) -> str:
    """Convert a kebab-case name to snake_case.

    Args:
        name: Name in kebab-case (e.g. ``'my-agent'``).

    Returns:
        Name in snake_case (e.g. ``'my_agent'``).
    """
    return name.replace("-", "_")


# Section: scaffold templates (decorator-first style)

REACT_TEMPLATE = '''\
"""Agent {name} (ReAct mode, decorator SDK)."""

from apollia import DomainError, agent, on_message, react
from apollia.types import Ctx, Message


SYSTEM_PROMPT = "You are a helpful assistant. Reason step by step."


@agent(
    name="{name}",
    version="0.1.0",
    description="Agent {name} generated by Apollia SDK",
)
class {class_name}:
    """ReAct agent generated by ``apollia new``."""

    @on_message
    async def chat(
        self,
        message: str,
        history: list[Message],
        ctx: Ctx,
    ) -> str:
        return await react(
            ctx,
            system=SYSTEM_PROMPT,
            user=message,
            tools=[],
            max_steps=10,
        )
'''

CONVERSATIONAL_TEMPLATE = '''\
"""Agent {name} (Conversational mode, decorator SDK)."""

from apollia import agent, on_message
from apollia.types import Ctx, Message


SYSTEM_PROMPT = "You are a helpful assistant."


@agent(
    name="{name}",
    version="0.1.0",
    description="Agent {name} generated by Apollia SDK",
)
class {class_name}:
    """Conversational agent generated by ``apollia new``."""

    @on_message
    async def chat(
        self,
        message: str,
        history: list[Message],
        ctx: Ctx,
    ) -> str:
        response = await ctx.llm.complete(
            messages=[
                {{"role": "system", "content": SYSTEM_PROMPT}},
                *history,
                {{"role": "user", "content": message}},
            ],
        )
        return response.content
'''

ORCHESTRATED_TEMPLATE = '''\
"""Agent {name} (Orchestrated mode, ORIA-piloted, decorator SDK)."""

from apollia import agent, orchestrated
from apollia.types import Ctx


SYSTEM_PROMPT = (
    "You are a planning assistant for the {name} domain. "
    "Break each user task into discrete steps and execute them with "
    "the available tools."
)


@agent(
    name="{name}",
    version="0.1.0",
    description="Agent {name} generated by Apollia SDK",
)
@orchestrated(system_prompt=SYSTEM_PROMPT)
class {class_name}:
    """Orchestrated agent generated by ``apollia new``."""

    async def on_plan_complete(
        self,
        step_results: dict[str, str],
        ctx: Ctx,
    ) -> str:
        return "\\n\\n".join(text for text in step_results.values() if text)
'''

WORKER_TEMPLATE = '''\
"""Worker Agent {name} (decorator SDK)."""

from apollia import DomainError, agent, skill
from apollia.types import Ctx


@agent(
    name="{name}",
    version="0.1.0",
    description="Worker Agent {name}, generated by Apollia SDK",
    agent_type="worker",
    memory_namespace="{name}",
    tags=("{module_name}", "worker"),
)
class {class_name}:
    """Worker Agent {name}."""

    @skill(
        "{module_name}.default",
        description="Default skill for {name}.",
        examples=[{{"input_text": "hello"}}],
    )
    async def default(self, input_text: str, ctx: Ctx) -> dict:
        if not input_text:
            raise DomainError("INVALID_INPUT", "input_text must be non-empty")
        return {{"echo": input_text}}
'''

TEST_TEMPLATE = '''\
"""Tests for {class_name}."""

import pytest

from apollia.testing import mock, assert_result_completed


@pytest.mark.asyncio
async def test_{module_name}_responds() -> None:
    """Verify the agent responds via @on_message with a mocked LLM."""
    from {module_name}_agent import {class_name}

    agent_ref, ctx = mock({class_name})
    ctx.llm.responses = [{{"content": "Hello back from the mock LLM."}}]
    ctx.llm.run_tools_responses = ["Hello back from the mock react loop."]

    result = await agent_ref.invoke_message("hello")

    assert_result_completed(result)
'''

WORKER_TEST_TEMPLATE = '''\
"""Tests for worker agent {name}."""

import pytest

from apollia.testing import mock, assert_result_completed, assert_result_failed


def _load_agent_class():
    import importlib.util
    from pathlib import Path

    agent_path = Path(__file__).resolve().parent.parent / "{name}.py"
    spec = importlib.util.spec_from_file_location("{module_name}_agent", agent_path)
    assert spec is not None and spec.loader is not None
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module.agent.__class__


@pytest.mark.asyncio
async def test_{module_name}_default_skill_echoes() -> None:
    """Verify the default skill echoes the input back."""
    AgentClass = _load_agent_class()
    agent_ref, ctx = mock(AgentClass)

    result = await agent_ref.invoke_skill("{module_name}.default", input_text="hello")

    assert_result_completed(result)


@pytest.mark.asyncio
async def test_{module_name}_default_skill_rejects_empty() -> None:
    """Verify the default skill raises INVALID_INPUT on empty input."""
    AgentClass = _load_agent_class()
    agent_ref, ctx = mock(AgentClass)

    result = await agent_ref.invoke_skill("{module_name}.default", input_text="")

    assert_result_failed(result, code="INVALID_INPUT")
'''

_TEMPLATES: dict[str, str] = {
    "react": REACT_TEMPLATE,
    "conversational": CONVERSATIONAL_TEMPLATE,
    "orchestrated": ORCHESTRATED_TEMPLATE,
}

# ---------------------------------------------------------------------------
# Scaffold logic
# ---------------------------------------------------------------------------


def scaffold_agent(
    name: str,
    agent_type: str = "react",
    output_dir: str = ".",
) -> tuple[str, str]:
    """Generate the files for a new agent.

    Args:
        name: Agent name in kebab-case (e.g. ``'my-agent'``).
        agent_type: One of ``'react'``, ``'conversational'``, ``'orchestrated'``,
            ``'worker'``.
        output_dir: Target directory (defaults to current directory).

    Returns:
        Tuple ``(agent_file_path, test_file_path)`` of the generated files.

    Raises:
        ValueError: If *agent_type* is not one of the supported types.
        FileExistsError: If a target file already exists.
    """
    if agent_type not in VALID_AGENT_TYPES:
        msg = (
            f"Invalid agent type '{agent_type}'. " f"Must be one of: {', '.join(VALID_AGENT_TYPES)}"
        )
        raise ValueError(msg)

    class_name = to_class_name(name)
    module_name = to_module_name(name)

    out = Path(output_dir)

    if agent_type == "worker":
        agent_path = out / "agents" / f"{name}.py"
        test_path = out / "agents" / "tests" / f"test_{module_name}.py"
    else:
        agent_path = out / f"{module_name}_agent.py"
        test_path = out / f"test_{module_name}_agent.py"

    for path in (agent_path, test_path):
        if path.exists():
            raise FileExistsError(f"File already exists: {path}")

    replacements = {
        "class_name": class_name,
        "name": name,
        "module_name": module_name,
    }

    if agent_type == "worker":
        agent_content = WORKER_TEMPLATE.format(**replacements)
        test_content = WORKER_TEST_TEMPLATE.format(**replacements)
    else:
        agent_content = _TEMPLATES[agent_type].format(**replacements)
        test_content = TEST_TEMPLATE.format(**replacements)

    agent_path.parent.mkdir(parents=True, exist_ok=True)
    test_path.parent.mkdir(parents=True, exist_ok=True)
    agent_path.write_text(agent_content, encoding="utf-8")
    test_path.write_text(test_content, encoding="utf-8")

    return str(agent_path), str(test_path)


# ---------------------------------------------------------------------------
# CLI entry point
# ---------------------------------------------------------------------------


def main(argv: list[str] | None = None) -> None:
    """Entry point for the ``apollia`` command.

    Args:
        argv: Command-line arguments.  Uses ``sys.argv[1:]`` when *None*.
    """
    parser = argparse.ArgumentParser(
        prog="apollia",
        description="Apollia SDK - agent development toolkit",
    )
    subparsers = parser.add_subparsers(dest="command")

    new_parser = subparsers.add_parser(
        "new",
        help="Generate a new agent from a template",
    )
    new_parser.add_argument(
        "name",
        help="Agent name in kebab-case (e.g. 'my-agent')",
    )
    new_parser.add_argument(
        "--type",
        dest="agent_type",
        choices=VALID_AGENT_TYPES,
        default="react",
        help="Agent type (default: react). Use 'worker' for A2A workers.",
    )
    new_parser.add_argument(
        "--output-dir",
        default=".",
        help="Output directory (default: current directory)",
    )

    args = parser.parse_args(argv if argv is not None else sys.argv[1:])

    if args.command is None:
        parser.print_help()
        return

    if args.command == "new":
        _handle_new(args)


def _handle_new(args: argparse.Namespace) -> None:
    """Execute the ``apollia new`` sub-command."""
    try:
        agent_path, test_path = scaffold_agent(
            name=args.name,
            agent_type=args.agent_type,
            output_dir=args.output_dir,
        )
    except (ValueError, FileExistsError) as exc:
        print(f"Error: {exc}", file=sys.stderr)
        sys.exit(1)

    print(f"Created {os.path.basename(agent_path)}")
    print(f"Created {os.path.basename(test_path)}")
    print(f"\nGet started:\n  cd {args.output_dir}")
    print(f"  pytest {os.path.basename(test_path)}")
