"""Agent scaffolding — generates a ready-to-run agent from a template."""

from __future__ import annotations

import argparse
import os
import sys
from pathlib import Path

VALID_AGENT_TYPES = ("react", "conversational", "orchestrated", "worker")

# ---------------------------------------------------------------------------
# Name conversions
# ---------------------------------------------------------------------------


def to_class_name(name: str) -> str:
    """Convert a kebab-case name to PascalCase with ``Agent`` suffix.

    The suffix is appended only when *name* does not already end with
    ``-agent`` or ``_agent``.

    Args:
        name: Name in kebab-case (e.g. ``'my-agent'``).

    Returns:
        PascalCase name ending in ``Agent`` (e.g. ``'MyAgent'``).
    """
    pascal = "".join(
        part.capitalize() for part in name.replace("_", "-").split("-")
    )
    if not pascal.lower().endswith("agent"):
        pascal += "Agent"
    return pascal


def to_module_name(name: str) -> str:
    """Convert a kebab-case name to snake_case.

    Args:
        name: Name in kebab-case (e.g. ``'my-agent'``).

    Returns:
        Name in snake_case (e.g. ``'my_agent'``).
    """
    return name.replace("-", "_")


# ---------------------------------------------------------------------------
# Templates
# ---------------------------------------------------------------------------

REACT_TEMPLATE = '''\
"""Agent {class_name} — ReAct mode."""

from apollia.agents import BaseReActAgent


class {class_name}(BaseReActAgent):
    """ReAct agent generated by ``apollia new``."""

    def manifest(self) -> dict:
        return {{
            "name": "{name}",
            "version": "0.1.0",
            "description": "Agent {name} generated by Apollia SDK",
            "tools": [],
            "max_steps": 10,
        }}

    async def run(self, task, ctx):
        result = await self.react(task, ctx, str(task))
        if isinstance(result, dict):
            return result
        return {{"status": "completed", "output": [{{"type": "text", "text": str(result)}}]}}
'''

CONVERSATIONAL_TEMPLATE = '''\
"""Agent {class_name} — Conversational mode."""

from apollia.agents import ConversationalAgent


class {class_name}(ConversationalAgent):
    """Conversational agent generated by ``apollia new``."""

    SYSTEM_PROMPT = "You are a helpful assistant."

    def manifest(self) -> dict:
        return {{
            "name": "{name}",
            "version": "0.1.0",
            "description": "Agent {name} generated by Apollia SDK",
            "tools": [],
        }}

    async def run(self, task, ctx):
        user_message = str(task)
        response, _history = await self.converse(ctx, user_message)
        return {{"status": "completed", "output": [{{"type": "text", "text": response}}]}}
'''

ORCHESTRATED_TEMPLATE = '''\
"""Agent {class_name} — Orchestrated mode (ORIA-piloted)."""

from apollia.agents import OrchestratedAgent


class {class_name}(OrchestratedAgent):
    """Orchestrated agent generated by ``apollia new``."""

    def manifest(self) -> dict:
        return {{
            "name": "{name}",
            "version": "0.1.0",
            "description": "Agent {name} generated by Apollia SDK",
            "execution_mode": "orchestrated",
            "system_prompt": "You are a planning assistant. Break tasks into steps.",
            "tools": [],
        }}

    def on_plan_complete(self, step_results: dict) -> dict:
        text = self.format_step_results(step_results)
        return {{"text": text}}
'''

TEST_TEMPLATE = '''\
"""Tests for {class_name}."""

import pytest

from apollia.testing import mock, assert_result_completed
from {module_name}_agent import {class_name}


@pytest.mark.asyncio
async def test_{module_name}_runs():
    """Verify the agent executes without error."""
    agent, ctx = mock({class_name})
    ctx.llm.responses = [{{"content": "I will help you."}}]
    result = await agent.invoke_message("hello")
    assert_result_completed(result)
'''

WORKER_TEMPLATE = '''\
"""Worker Agent {name}."""

from __future__ import annotations

from typing import Any

from apollia.agents import AIPResult, WorkerAgent


SYSTEM_PROMPT = """
Tu es {name}, un agent expert de {name}.

## RÈGLES ABSOLUES (non-négociables)

1. Toujours vérifier les prérequis avant de commencer la tâche.
   RAISON : Un agent robuste valide son environnement en amont.

2. Retourner une erreur structurée avec domain_error() pour tout cas d\'échec prévisible.
   Ne jamais lever une exception non gérée.

## GESTION DES ERREURS DOMAINE

- FileNotFoundError -> domain_error("file_not_found", ...)

## FORMAT DE RÉPONSE

- Toujours indiquer ce qui a été fait et le résultat obtenu.
"""


def manifest() -> dict:
    """Return the agent manifest."""
    return {{
        "name": "{name}",
        "version": "0.1.0",
        "description": "Worker Agent {name} — generated by Apollia SDK",
        "execution_mode": "direct",
        "tools_required": ["python_executor"],
        "tools_optional": [],
        "tools_requiring_approval": [],
        "packages": [],
        "memory_namespace": "{name}",
        "supports_a2a": True,
        "skills": [
            {{
                "id": "{name}-skill",
                "name": "{name} default skill",
                "description": "Default skill for {name}",
                "input_modes": ["text"],
                "output_modes": ["text"],
            }},
        ],
        "tags": ["{module_name}", "worker"],
        "max_concurrent_tasks": 1,
        "dangerous_tools_allowed": False,
    }}


class {class_name}(WorkerAgent):
    """Worker Agent {name}."""

    SYSTEM_PROMPT = SYSTEM_PROMPT
    MAX_STEPS = 8
    TEMPERATURE = 0.1

    def manifest(self) -> dict:
        """Return the agent manifest."""
        return manifest()

    async def run(self, task: dict, ctx: Any) -> dict[str, Any]:
        """Execute the agent task using the ReAct loop."""
        user_message = (
            task.get("input", {{}}).get("text", "")
            if isinstance(task.get("input"), dict)
            else str(task.get("input", ""))
        )
        result = await self.react(task, ctx, user_message)
        if isinstance(result, dict):
            return result
        return AIPResult.completed(result)


agent = {class_name}()
'''

WORKER_TEST_TEMPLATE = '''\
"""Tests for {name}."""

from __future__ import annotations

import importlib.util
import sys
from pathlib import Path

import pytest

_REPO_ROOT = Path(__file__).resolve().parent.parent.parent
if str(_REPO_ROOT / "sdk") not in sys.path:
    sys.path.insert(0, str(_REPO_ROOT / "sdk"))

_AGENT_PATH = _REPO_ROOT / "agents" / "{name}.py"
_spec = importlib.util.spec_from_file_location("{module_name}", _AGENT_PATH)
assert _spec is not None and _spec.loader is not None
{module_name} = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module({module_name})  # type: ignore[union-attr]


@pytest.mark.asyncio
async def test_manifest_is_valid() -> None:
    """Manifest conforms to Worker Agent contract."""
    m = {module_name}.agent.manifest()
    assert m["name"] == "{name}"
    assert m["supports_a2a"] is True
    assert len(m["skills"]) >= 1


def test_system_prompt_has_guardrails() -> None:
    """SYSTEM_PROMPT contains meaningful guardrail content."""
    prompt = {module_name}.SYSTEM_PROMPT
    assert len(prompt) > 100
'''

_TEMPLATES: dict[str, str] = {
    "react": REACT_TEMPLATE,
    "conversational": CONVERSATIONAL_TEMPLATE,
    "orchestrated": ORCHESTRATED_TEMPLATE,
}

# ---------------------------------------------------------------------------
# Scaffold logic
# ---------------------------------------------------------------------------


def scaffold_agent(
    name: str,
    agent_type: str = "react",
    output_dir: str = ".",
) -> tuple[str, str]:
    """Generate the files for a new agent.

    Args:
        name: Agent name in kebab-case (e.g. ``'my-agent'``).
        agent_type: One of ``'react'``, ``'conversational'``, ``'orchestrated'``.
        output_dir: Target directory (defaults to current directory).

    Returns:
        Tuple ``(agent_file_path, test_file_path)`` of the generated files.

    Raises:
        ValueError: If *agent_type* is not one of the supported types.
        FileExistsError: If a target file already exists.
    """
    if agent_type not in VALID_AGENT_TYPES:
        msg = (
            f"Invalid agent type '{agent_type}'. "
            f"Must be one of: {', '.join(VALID_AGENT_TYPES)}"
        )
        raise ValueError(msg)

    class_name = to_class_name(name)
    module_name = to_module_name(name)

    out = Path(output_dir)

    if agent_type == "worker":
        agent_path = out / "agents" / f"{name}.py"
        test_path = out / "agents" / "tests" / f"test_{module_name}.py"
    else:
        agent_path = out / f"{module_name}_agent.py"
        test_path = out / f"test_{module_name}_agent.py"

    for path in (agent_path, test_path):
        if path.exists():
            raise FileExistsError(f"File already exists: {path}")

    replacements = {
        "class_name": class_name,
        "name": name,
        "module_name": module_name,
    }

    if agent_type == "worker":
        agent_content = WORKER_TEMPLATE.format(**replacements)
        test_content = WORKER_TEST_TEMPLATE.format(**replacements)
    else:
        agent_content = _TEMPLATES[agent_type].format(**replacements)
        test_content = TEST_TEMPLATE.format(**replacements)

    agent_path.parent.mkdir(parents=True, exist_ok=True)
    test_path.parent.mkdir(parents=True, exist_ok=True)
    agent_path.write_text(agent_content, encoding="utf-8")
    test_path.write_text(test_content, encoding="utf-8")

    return str(agent_path), str(test_path)


# ---------------------------------------------------------------------------
# CLI entry point
# ---------------------------------------------------------------------------


def main(argv: list[str] | None = None) -> None:
    """Entry point for the ``apollia`` command.

    Args:
        argv: Command-line arguments.  Uses ``sys.argv[1:]`` when *None*.
    """
    parser = argparse.ArgumentParser(
        prog="apollia",
        description="Apollia SDK — agent development toolkit",
    )
    subparsers = parser.add_subparsers(dest="command")

    new_parser = subparsers.add_parser(
        "new",
        help="Generate a new agent from a template",
    )
    new_parser.add_argument(
        "name",
        help="Agent name in kebab-case (e.g. 'my-agent')",
    )
    new_parser.add_argument(
        "--type",
        dest="agent_type",
        choices=VALID_AGENT_TYPES,
        default="react",
        help="Agent type (default: react). Use 'worker' for domain-specialized Worker Agents.",
    )
    new_parser.add_argument(
        "--output-dir",
        default=".",
        help="Output directory (default: current directory)",
    )

    args = parser.parse_args(argv if argv is not None else sys.argv[1:])

    if args.command is None:
        parser.print_help()
        return

    if args.command == "new":
        _handle_new(args)


def _handle_new(args: argparse.Namespace) -> None:
    """Execute the ``apollia new`` sub-command."""
    try:
        agent_path, test_path = scaffold_agent(
            name=args.name,
            agent_type=args.agent_type,
            output_dir=args.output_dir,
        )
    except (ValueError, FileExistsError) as exc:
        print(f"Error: {exc}", file=sys.stderr)
        sys.exit(1)

    print(f"Created {os.path.basename(agent_path)}")
    print(f"Created {os.path.basename(test_path)}")
    print(f"\nGet started:\n  cd {args.output_dir}")
    print(f"  pytest {os.path.basename(test_path)}")
