//! IPC request envelope: `{request_id, params}`.

use serde::{Deserialize, Serialize};
use uuid::Uuid;

/// Generic envelope for every HTTP request from the daemon to the runner.
///
/// The daemon generates a UUID v4 `request_id` that the runner echoes back in
/// its response, enabling correlation in structured logs.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Request<P> {
    /// Unique request identifier, generated by the daemon.
    pub request_id: Uuid,
    /// Typed parameters specific to the endpoint.
    pub params: P,
}

impl<P> Request<P> {
    pub fn new(params: P) -> Self {
        Self {
            request_id: Uuid::new_v4(),
            params,
        }
    }
}
