"""apollia-reviewer — Local Git pair-reviewer agent.

Tier 0 (always active): static analysis — TODOs, diff size, untested Rust files.
Tier 1 (active when ctx.llm is available): LLM review of the diff.

Usage:
    apollia-os run apollia-reviewer "/absolute/path/to/repo"

Output:
    .apollia/reviews/review-latest.md in the target repo
    Return value: full Markdown report as text
"""

import os


class ApollaReviewer:
    """Pair-reviewer agent that analyses the latest Git commit in a local repo."""

    def manifest(self):
        return {
            "name": "apollia-reviewer",
            "version": "1.0.0",
            "description": (
                "Local pair-reviewer. Analyses the latest Git commit: "
                "static checks (TODOs, diff size, untested Rust files) "
                "plus optional LLM review when a backend is configured."
            ),
            "tools_required": ["bash_executor", "file_io"],
            "memory_namespace": "apollia-reviewer",
            "execution_mode": "direct",
        }

    async def run(self, task, ctx):
        parts = task["input"]["parts"]
        if not parts or not parts[0].get("text", "").strip():
            return {
                "task_id": task["task_id"],
                "status": "failed",
                "error": {
                    "code": "MISSING_INPUT",
                    "message": "Expected first part to be the absolute repo path.",
                },
            }

        repo_path = parts[0]["text"].strip()

        # 1. Collect git data
        diff = await self._git(ctx, repo_path, "diff HEAD~1")
        branch = (await self._git(ctx, repo_path, "branch --show-current")).strip()
        commit_msg = (await self._git(ctx, repo_path, "log -1 --pretty=%B")).strip()
        stat = await self._git(ctx, repo_path, "diff HEAD~1 --stat")

        # 2. Static analysis
        todos = await self._find_risky_patterns(ctx, repo_path)
        missing_tests = await self._find_untested_rust(ctx, repo_path)

        # 3. Build report sections
        static_section = self._build_static_section(diff, todos, missing_tests)
        llm_section = await self._build_llm_section(ctx, branch, commit_msg, diff)

        lines_added = diff.count("\n+")
        lines_removed = diff.count("\n-")
        tier = "Tier 1 — LLM enabled" if ctx.llm else "Tier 0 — static only"

        report = (
            f"# Review — {commit_msg}\n\n"
            f"**Branch:** `{branch}`  \n"
            f"**Repo:** `{repo_path}`\n\n"
            f"## Diff summary\n\n"
            f"```\n{stat.strip()}\n```\n\n"
            f"**Lines:** +{lines_added} / -{lines_removed}\n\n"
            f"## Static analysis\n\n"
            f"{static_section}\n\n"
            f"## LLM analysis\n\n"
            f"{llm_section}\n\n"
            f"---\n"
            f"*Generated by apollia-reviewer ({tier})*\n"
        )

        # 4. Persist report to .apollia/reviews/review-latest.md
        review_dir = os.path.join(repo_path, ".apollia", "reviews")
        await ctx.tools.call("bash_executor", {
            "command": f"mkdir -p '{review_dir}'",
            "timeout_seconds": 5,
        })
        await ctx.tools.call("file_io", {
            "action": "write",
            "path": os.path.join(review_dir, "review-latest.md"),
            "content": report,
        })

        # 5. Record in episodic memory for history tracking
        if ctx.memory:
            await ctx.memory.record(
                f"review: {branch} — {commit_msg[:80]}",
                importance=0.6,
                task_id=task["task_id"],
                metadata={"branch": branch, "repo": repo_path},
            )

        return {
            "task_id": task["task_id"],
            "status": "completed",
            "output": [{"type": "text", "text": report}],
        }

    # ------------------------------------------------------------------ helpers

    async def _git(self, ctx, repo_path, args):
        """Run a git sub-command inside repo_path; return stdout (empty on error)."""
        result = await ctx.tools.call("bash_executor", {
            "command": f"git -C '{repo_path}' {args}",
            "timeout_seconds": 30,
        })
        return result.get("stdout", "")

    async def _find_risky_patterns(self, ctx, repo_path):
        """Return added lines from the diff that match TODO/FIXME/HACK/unwrap()."""
        result = await ctx.tools.call("bash_executor", {
            "command": (
                f"git -C '{repo_path}' diff HEAD~1 | "
                r"grep '^+' | grep -iE 'TODO|FIXME|HACK|unwrap\(\)' || true"
            ),
            "timeout_seconds": 15,
        })
        return result.get("stdout", "")

    async def _find_untested_rust(self, ctx, repo_path):
        """Return Rust files changed in the last commit that contain no #[test]."""
        result = await ctx.tools.call("bash_executor", {
            "command": (
                f"git -C '{repo_path}' diff HEAD~1 --name-only | "
                r"grep '\.rs$' | "
                r"xargs -I{} sh -c "
                r"'grep -lq \"#\[test\]\" {} 2>/dev/null || echo \"NO_TEST: {}\"'"
                r" || true"
            ),
            "timeout_seconds": 15,
        })
        return result.get("stdout", "")

    def _build_static_section(self, diff, todos, missing_tests):
        """Compile static findings into a Markdown section."""
        items = []
        lines_added = diff.count("\n+")

        if todos.strip():
            items.append(
                "### Risky patterns detected\n\n"
                f"```\n{todos.strip()}\n```"
            )

        if lines_added > 300:
            items.append(
                "### Large diff warning\n\n"
                f"{lines_added} lines added — consider splitting the commit."
            )

        no_test_files = [
            line.replace("NO_TEST: ", "").strip()
            for line in missing_tests.splitlines()
            if line.startswith("NO_TEST:")
        ]
        if no_test_files:
            file_list = "\n".join(f"- `{f}`" for f in no_test_files)
            items.append(f"### Rust files without `#[test]`\n\n{file_list}")

        return "\n\n---\n\n".join(items) if items else "No static issues detected."

    async def _build_llm_section(self, ctx, branch, commit_msg, diff):
        """Return LLM analysis if a backend is available, otherwise a notice."""
        if ctx.llm is None:
            return "_LLM backend not configured — static analysis only._"

        diff_body = diff[:8000]
        if len(diff) > 8000:
            diff_body += "\n\n... (diff truncated to 8000 chars)"

        response = await ctx.llm.chat(
            system=(
                "You are an expert Rust code reviewer. Analyse the Git diff below. "
                "Identify: technical debt introduced, missing tests, "
                "commit message coherence with the changes, and concrete suggestions. "
                "Respond in structured Markdown. Be direct and concise."
            ),
            user=(
                f"Branch: {branch}\n"
                f"Commit: {commit_msg}\n\n"
                f"Diff:\n{diff_body}"
            ),
        )
        return response.content


agent = ApollaReviewer()
