"""apollia-reviewer — Local Git pair-reviewer agent.

Validates manually from ONBOARDING-CHECKLIST.md, Bloc 3 and 4.

Bloc 3 — Deploy:
    apollia-os agent start agents/apollia-reviewer.py
    apollia-os agent info apollia-reviewer

Bloc 4.1 — Synchronous execution:
    apollia-os run apollia-reviewer "$(pwd)"
    → # Review — <commit_msg>
    → ## Static analysis
    → ## LLM analysis (or "static only" notice when no LLM)
    → *Generated by apollia-reviewer*
    → .apollia/reviews/review-latest.md created

Bloc 4.2 — Streaming (--stream):
    apollia-os run apollia-reviewer "$(pwd)" --stream

Bloc 4.3 — Async detach (--detach):
    apollia-os run apollia-reviewer "$(pwd)" --detach

Tool strategy:
    - Shell commands: prefers ctx.tools (bash_executor) when wired, falls back
      to stdlib subprocess.
    - File writes: always uses stdlib open() — file_io rejects absolute paths
      (sandbox policy), and the review output path is always absolute.
    This makes the agent self-contained for onboarding validation without
    requiring a fully wired tool proxy.
"""

import os
import subprocess
import asyncio


class ApollaReviewer:
    """Git pair-reviewer agent — analyses the latest commit of a local repository.

    Manifest fields (Bloc 3 validation):
        name:             apollia-reviewer
        version:          1.0.0
        tools_required:   bash_executor, file_io
        memory_namespace: apollia-reviewer
        execution_mode:   direct

    The agent operates in two tiers:
        Tier 0 (always): static checks — TODOs, diff size, untested Rust files.
        Tier 1 (when ctx.llm): LLM-powered structural review of the diff.
    """

    def manifest(self):
        """Return the AIP agent manifest.

        Called by the runtime at `agent start` time to register metadata and
        validate duck-typing requirements (ONBOARDING-CHECKLIST Bloc 3).
        """
        return {
            "name": "apollia-reviewer",
            "version": "1.0.0",
            "description": (
                "Local pair-reviewer. Analyses the latest Git commit: "
                "static checks (TODOs, diff size, untested Rust files) "
                "plus optional LLM review when a backend is configured."
            ),
            "tools_required": ["bash_executor", "file_io"],
            "memory_namespace": "apollia-reviewer",
            "execution_mode": "direct",
        }

    async def run(self, task, ctx):
        """Main entry point — called once per task by the Apollia runtime.

        ONBOARDING-CHECKLIST Bloc 4.1 validation path:
            1. Parse repo_path from task["input"]["parts"][0]["text"]
            2. Collect git data (diff, branch, commit message, stat)
            3. Run static analysis (Tier 0 — always)
            4. Run LLM analysis if ctx.llm is available (Tier 1 — optional)
            5. Build Markdown report starting with "# Review — <commit_msg>"
            6. Persist report to .apollia/reviews/review-latest.md
            7. Record in memory if ctx.memory is available
            8. Return {"status": "completed", "output": [{"type": "text", "text": report}]}

        Args:
            task: AIP task dict — input parts carry the repo path as text.
            ctx:  RuntimeContext — exposes ctx.llm, ctx.tools, ctx.memory.
                  Any of these may be None; the agent degrades gracefully.

        Returns:
            AIP result dict with status "completed" and the full Markdown report.
        """
        # ── 1. Parse input ────────────────────────────────────────────────
        parts = task["input"]["parts"]
        if not parts or not parts[0].get("text", "").strip():
            return {
                "task_id": task["task_id"],
                "status": "failed",
                "error": {
                    "code": "MISSING_INPUT",
                    "message": "Expected first part to be the absolute repo path.",
                },
            }

        repo_path = parts[0]["text"].strip()

        # ── 2. Collect git data ───────────────────────────────────────────
        diff = await self._git(ctx, repo_path, "diff HEAD~1")
        branch = (await self._git(ctx, repo_path, "branch --show-current")).strip()
        commit_msg = (await self._git(ctx, repo_path, "log -1 --pretty=%B")).strip()
        stat = await self._git(ctx, repo_path, "diff HEAD~1 --stat")

        # ── 3. Static analysis (Tier 0 — always active) ───────────────────
        todos = await self._find_risky_patterns(ctx, repo_path)
        missing_tests = await self._find_untested_rust(ctx, repo_path)

        # ── 4. Build report sections ──────────────────────────────────────
        static_section = self._build_static_section(diff, todos, missing_tests)
        llm_section = await self._build_llm_section(ctx, branch, commit_msg, diff)

        lines_added = diff.count("\n+")
        lines_removed = diff.count("\n-")
        tier = "Tier 1 — LLM enabled" if ctx.llm else "Tier 0 — static only"

        # ── 5. Assemble Markdown report ───────────────────────────────────
        # Bloc 4.1: report must start with "# Review —" and end with
        # "*Generated by apollia-reviewer*"
        report = (
            f"# Review — {commit_msg}\n\n"
            f"**Branch:** `{branch}`  \n"
            f"**Repo:** `{repo_path}`\n\n"
            f"## Diff summary\n\n"
            f"```\n{stat.strip()}\n```\n\n"
            f"**Lines:** +{lines_added} / -{lines_removed}\n\n"
            f"## Static analysis\n\n"
            f"{static_section}\n\n"
            f"## LLM analysis\n\n"
            f"{llm_section}\n\n"
            f"---\n"
            f"*Generated by apollia-reviewer ({tier})*\n"
        )

        # ── 6. Persist to .apollia/reviews/review-latest.md ──────────────
        # Bloc 4.1: ls .apollia/reviews/review-latest.md must succeed
        review_dir = os.path.join(repo_path, ".apollia", "reviews")
        await self._write_report(ctx, review_dir, report)

        # ── 7. Memory recording (optional — Tier 0 degradation) ──────────
        if ctx.memory:
            try:
                await ctx.memory.record(
                    f"review: {branch} — {commit_msg[:80]}",
                    importance=0.6,
                    task_id=task["task_id"],
                )
            except Exception:
                pass

        # ── 8. Return result ──────────────────────────────────────────────
        return {
            "task_id": task["task_id"],
            "status": "completed",
            "output": [{"type": "text", "text": report}],
        }

    # ──────────────────────────────────────────────────────── helpers ──────

    async def _run_command(self, ctx, command, timeout_seconds=30):
        """Run a shell command, preferring ctx.tools then stdlib subprocess.

        When ctx.tools is available (runtime fully wired), delegates to
        bash_executor so the call is audited and sandboxed.
        Falls back to asyncio subprocess when ctx.tools is None — this
        makes the agent work during onboarding validation without a tool proxy.

        Returns the stdout string (empty string on error).
        """
        if ctx.tools is not None:
            result = await ctx.tools.call("bash_executor", {
                "command": command,
                "timeout_seconds": timeout_seconds,
            })
            return result.get("stdout", "")

        # Fallback: stdlib subprocess (blocking, run in executor)
        loop = asyncio.get_event_loop()
        try:
            proc = await loop.run_in_executor(
                None,
                lambda: subprocess.run(
                    command,
                    shell=True,
                    capture_output=True,
                    text=True,
                    timeout=timeout_seconds,
                ),
            )
            return proc.stdout
        except Exception:
            return ""

    async def _git(self, ctx, repo_path, args):
        """Run a git sub-command inside repo_path; return stdout (empty on error)."""
        return await self._run_command(ctx, f"git -C '{repo_path}' {args}")

    async def _find_risky_patterns(self, ctx, repo_path):
        """Return added lines from the diff that match TODO/FIXME/HACK/unwrap()."""
        return await self._run_command(ctx, (
            f"git -C '{repo_path}' diff HEAD~1 | "
            r"grep '^+' | grep -iE 'TODO|FIXME|HACK|unwrap\(\)' || true"
        ), timeout_seconds=15)

    async def _find_untested_rust(self, ctx, repo_path):
        """Return Rust files changed in the last commit that contain no #[test]."""
        return await self._run_command(ctx, (
            f"git -C '{repo_path}' diff HEAD~1 --name-only | "
            r"grep '\.rs$' | "
            r"xargs -I{} sh -c "
            r"'grep -lq \"#\[test\]\" {} 2>/dev/null || echo \"NO_TEST: {}\"'"
            r" || true"
        ), timeout_seconds=15)

    def _build_static_section(self, diff, todos, missing_tests):
        """Compile static findings into a Markdown section.

        Checks (always run — Tier 0):
            - Risky patterns: TODO / FIXME / HACK / unwrap() in added lines.
            - Large diff: warns when > 300 lines added.
            - Untested Rust: lists .rs files changed without a #[test] block.

        Returns "No static issues detected." when all checks pass.
        """
        items = []
        lines_added = diff.count("\n+")

        if todos.strip():
            items.append(
                "### Risky patterns detected\n\n"
                f"```\n{todos.strip()}\n```"
            )

        if lines_added > 300:
            items.append(
                "### Large diff warning\n\n"
                f"{lines_added} lines added — consider splitting the commit."
            )

        no_test_files = [
            line.replace("NO_TEST: ", "").strip()
            for line in missing_tests.splitlines()
            if line.startswith("NO_TEST:")
        ]
        if no_test_files:
            file_list = "\n".join(f"- `{f}`" for f in no_test_files)
            items.append(f"### Rust files without `#[test]`\n\n{file_list}")

        return "\n\n---\n\n".join(items) if items else "No static issues detected."

    async def _build_llm_section(self, ctx, branch, commit_msg, diff):
        """Return LLM analysis (Tier 1) or a static-only notice (Tier 0).

        Tier 1 (ctx.llm available):
            Sends branch, commit message, and diff (≤ 8000 chars) to the
            configured LLM backend for structural review.

        Tier 0 (ctx.llm is None):
            Returns a notice explaining that static analysis is the only tier
            active. ONBOARDING-CHECKLIST Bloc 4.1 still passes in this mode.
        """
        if ctx.llm is None:
            return "_LLM backend not configured — static analysis only._"

        diff_body = diff[:8000]
        if len(diff) > 8000:
            diff_body += "\n\n... (diff truncated to 8000 chars)"

        response = await ctx.llm.chat(
            system=(
                "You are an expert Rust code reviewer. Analyse the Git diff below. "
                "Identify: technical debt introduced, missing tests, "
                "commit message coherence with the changes, and concrete suggestions. "
                "Respond in structured Markdown. Be direct and concise."
            ),
            user=(
                f"Branch: {branch}\n"
                f"Commit: {commit_msg}\n\n"
                f"Diff:\n{diff_body}"
            ),
        )
        return response.content

    async def _write_report(self, ctx, review_dir, report):
        """Persist report to review_dir/review-latest.md.

        Bloc 4.1 validation:
            ls -la .apollia/reviews/review-latest.md  → file present, size > 0
            head -5 .apollia/reviews/review-latest.md → starts with "# Review —"

        Uses bash_executor (via ctx.tools) for mkdir when the runtime has wired
        tools, then always uses stdlib for the file write — file_io rejects
        absolute paths (sandbox policy), but the review path is always absolute.
        """
        report_path = os.path.join(review_dir, "review-latest.md")

        # mkdir: prefer audited bash_executor, fall back to stdlib
        if ctx.tools is not None:
            await ctx.tools.call("bash_executor", {
                "command": f"mkdir -p '{review_dir}'",
                "timeout_seconds": 5,
            })
        else:
            os.makedirs(review_dir, exist_ok=True)

        # write: always use stdlib (file_io rejects absolute paths)
        with open(report_path, "w", encoding="utf-8") as fh:
            fh.write(report)


agent = ApollaReviewer()
