"""orchestrated_agent — ORIA Mode Orchestré : planification + exécution automatiques.

Démontre le mode autonome d'Apollia OS.

Contrairement à react_agent.py (qui gère sa propre boucle dans run()),
cet agent délègue intégralement la boucle de planification et d'exécution au
moteur ORIA. L'agent ne définit qu'un manifest + system_prompt. ORIA :
    1. Génère un plan JSON (ExecutionPlan + PlanSteps) via le LLM
    2. Exécute chaque step (appels d'outils) de façon topologique
    3. Re-planifie si un step échoue (replanning)
    4. Notifie le pipeline par des RuntimeEvents (SSE visible côté CLI)

run() est OPTIONNEL en mode orchestré. S'il est défini, il est appelé UNE FOIS
après que ORIA a terminé le plan — utile pour post-traitement ou résumé final.

Bloc 16 — Deploy:
    apollia-os agent start agents/orchestrated_agent.py
    apollia-os agent info orchestrated-agent

Bloc 16.4 — Run (requires LLM):
    apollia-os run orchestrated-agent "Analyse the codebase structure in $(pwd)"
    → ORIA generates a plan (visible in task inspect)
    → Steps execute autonomously
    → Final summary returned

Bloc 16.5 — Inspect the generated plan:
    apollia-os task inspect <task-id>
    → Prints the execution plan and step statuses

Bloc 16.6 — Streaming (watch plan unfold):
    apollia-os run orchestrated-agent "Count .rs files per crate in $(pwd)" --stream
    → ~ Running on orchestrated-agent...
    → (plan_generated, step_started, step_completed events)
    → Final answer
"""


class OrchestratedAgent:
    """ORIA Mode Orchestré — no ReAct loop in Python, ORIA handles everything.

    Manifest fields (Bloc 16 validation):
        name:             orchestrated-agent
        version:          1.0.0
        tools_required:   bash_executor, file_io
        memory_namespace: orchestrated-agent
        execution_mode:   orchestrated

    The system_prompt tells ORIA what kind of agent this is and how to plan.
    ORIA uses it when calling the LLM to generate the execution plan.
    """

    def manifest(self):
        return {
            "name": "orchestrated-agent",
            "version": "1.0.0",
            "description": (
                "ORIA orchestrated agent. The runtime generates and executes a "
                "multi-step plan automatically. No ReAct loop in Python — "
                "ORIA is the autonomous engine."
            ),
            "tools_required": ["bash_executor", "file_io"],
            "memory_namespace": "orchestrated-agent",
            "execution_mode": "orchestrated",
            "system_prompt": (
                "You are an expert software analyst with access to shell commands "
                "and file reading tools. When given a task, decompose it into "
                "concrete, executable steps using the available tools. "
                "Prefer bash_executor for exploration tasks. "
                "Be precise: each step should have a single, clear objective. "
                "Stop when you have a complete and accurate answer."
            ),
        }

    async def run(self, task, ctx):
        """Post-processing hook — called ONCE after ORIA finishes the plan.

        In orchestrated mode this method is OPTIONAL.
        If defined, it receives the completed task and the full ctx.
        Use it to:
            - Summarise ORIA's output
            - Persist results to memory
            - Format a final report

        If you don't need post-processing, you can omit run() entirely.
        """
        # Collect ORIA's output from the task result field (if available)
        oria_output = ""
        if task.get("oria_result"):
            oria_output = task["oria_result"].get("summary", "")

        # Build a concise final report
        user_input = ""
        parts = task["input"].get("parts", [])
        if parts:
            user_input = parts[0].get("text", "").strip()

        report = (
            f"# Orchestrated Analysis — {user_input[:80]}\n\n"
            f"**Mode:** ORIA Orchestrated (autonomous planning + execution)\n\n"
            f"## Result\n\n"
            f"{oria_output or '_ORIA execution completed. See task inspect for step details._'}\n\n"
            f"---\n*Generated by orchestrated-agent (ORIA Mode Orchestré)*\n"
        )

        # Persist to memory if available
        if ctx.memory:
            await ctx.memory.record(
                f"orchestrated: {user_input[:80]}",
                importance=0.6,
                task_id=task["task_id"],
            )

        return {
            "task_id": task["task_id"],
            "status": "completed",
            "output": [{"type": "text", "text": report}],
        }


agent = OrchestratedAgent()
