"""react_agent — Pure-Python ReAct agent (Thought → Action → Observe loop).

Demonstrates:
    - Manual ReAct loop driven by ctx.llm
    - Tool calls via ctx.tools (bash_executor, file_io) with subprocess fallback
    - Graceful degradation when ctx.llm is None (static-only mode)
    - Memory recording of completed analysis

Bloc 16 — Deploy:
    apollia-os agent start agents/react_agent.py
    apollia-os agent info react-agent

Bloc 16.1 — Run (requires LLM):
    apollia-os run react-agent "List the top-level directories in $(pwd)"
    → # ReAct — List the top-level directories in ...
    → ## Loop (Thought/Action/Observe)
    → ## Answer
    → *Generated by react-agent*

Bloc 16.2 — Streaming:
    apollia-os run react-agent "How many .rs files are in $(pwd)/crates?" --stream
    → ~ Running on react-agent...
    → (events arrive progressively)

Bloc 16.3 — Degraded (no LLM):
    apollia-os run react-agent "echo hello"
    → ⚠ LLM not available — running static fallback

Tool strategy:
    - Prefers ctx.tools (bash_executor) when available.
    - Falls back to asyncio subprocess when ctx.tools is None.
"""

import asyncio
import json
import re
import subprocess


MAX_STEPS = 8          # Hard cap on Thought/Action/Observe iterations
MAX_DIFF_CHARS = 6000  # Safety limit on tool output fed back to LLM


SYSTEM_PROMPT = """\
You are an autonomous assistant that solves tasks step by step using the ReAct pattern.

At each step output EXACTLY one of these two formats and nothing else:

Format A — use a tool:
Thought: <one sentence reasoning>
Action: <tool_name>({"param": "value", ...})

Format B — produce the final answer (only when you have enough information):
Thought: <one sentence reasoning>
Action: FINISH({"answer": "<your final answer>"})

Available tools:
  - bash_executor({"command": "<shell command>", "timeout_seconds": <int>})
      Run a shell command. Returns {"stdout": "...", "stderr": "...", "exit_code": 0}.
  - file_io({"action": "read", "path": "<absolute path>"})
      Read a file. Returns {"content": "..."}.

Rules:
  - Always output Thought then Action on two consecutive lines.
  - Never add extra text outside the Thought/Action block.
  - FINISH when you have a conclusive answer, or after exhausting useful tool calls.
"""


class ReactAgent:
    """Pure-Python ReAct agent — manages its own Thought/Action/Observe loop.

    Manifest fields (Bloc 16 validation):
        name:             react-agent
        version:          1.0.0
        tools_required:   bash_executor, file_io
        memory_namespace: react-agent
        execution_mode:   direct
    """

    def manifest(self):
        return {
            "name": "react-agent",
            "version": "1.0.0",
            "description": (
                "Pure-Python ReAct agent. Implements Thought/Action/Observe loop "
                "manually using ctx.llm. Falls back to static mode when no LLM."
            ),
            "tools_required": ["bash_executor", "file_io"],
            "memory_namespace": "react-agent",
            "execution_mode": "direct",
        }

    async def run(self, task, ctx):
        """Main entry point — one call per task.

        Implements:
            1. Parse input
            2. If no LLM → static fallback (single bash call, return)
            3. ReAct loop (up to MAX_STEPS):
               a. Build prompt with history
               b. Call ctx.llm.chat()
               c. Parse Thought + Action
               d. If FINISH → collect answer and exit loop
               e. Execute tool, append Observation
            4. Build Markdown report
            5. Persist to memory if available
            6. Return AIP result dict
        """
        parts = task["input"].get("parts", [])
        if not parts or not parts[0].get("text", "").strip():
            return {
                "task_id": task["task_id"],
                "status": "failed",
                "error": {
                    "code": "MISSING_INPUT",
                    "message": "Expected first part to be the task description.",
                },
            }

        user_input = parts[0]["text"].strip()

        # ── Degraded mode (no LLM) ──────────────────────────────────────────
        if ctx.llm is None:
            fallback_out = await self._run_command(
                ctx,
                f"echo '⚠ LLM not available — running static fallback'; {user_input}",
            )
            report = (
                f"# ReAct — {user_input[:80]}\n\n"
                f"⚠ **LLM backend not configured** — static fallback only.\n\n"
                f"```\n{fallback_out.strip()}\n```\n\n"
                f"---\n*Generated by react-agent (Tier 0 — static only)*\n"
            )
            return {
                "task_id": task["task_id"],
                "status": "completed",
                "output": [{"type": "text", "text": report}],
            }

        # ── ReAct loop ───────────────────────────────────────────────────────
        history = []      # list of {"role": "assistant"|"user", "content": str}
        loop_log = []     # human-readable Thought/Action/Observe trace
        answer = None

        for step in range(1, MAX_STEPS + 1):
            # Build context message (first step = user goal; subsequent = observations)
            if step == 1:
                user_msg = f"Task: {user_input}"
            else:
                # Last observation is the last user message in history
                user_msg = history[-1]["content"] if history else ""

            # Call LLM
            messages = self._build_messages(history, user_msg if step == 1 else None)
            llm_resp = await ctx.llm.chat(system=SYSTEM_PROMPT, user=messages)
            raw = llm_resp.content.strip()

            # Parse Thought + Action
            thought, action_name, action_args, parse_error = self._parse_react(raw)

            if parse_error:
                loop_log.append(
                    f"### Step {step} — parse error\n\n"
                    f"LLM output could not be parsed:\n```\n{raw}\n```\n"
                    f"Error: {parse_error}"
                )
                break

            loop_log.append(
                f"### Step {step}\n\n"
                f"**Thought:** {thought}\n\n"
                f"**Action:** `{action_name}({json.dumps(action_args)})`"
            )
            history.append({"role": "assistant", "content": raw})

            # FINISH action — extract answer and stop
            if action_name == "FINISH":
                answer = action_args.get("answer", "")
                loop_log[-1] += f"\n\n**Answer:** {answer}"
                break

            # Execute tool
            observation = await self._call_tool(ctx, action_name, action_args)
            obs_display = observation[:MAX_DIFF_CHARS]
            if len(observation) > MAX_DIFF_CHARS:
                obs_display += f"\n... (truncated to {MAX_DIFF_CHARS} chars)"

            loop_log[-1] += f"\n\n**Observation:**\n```\n{obs_display}\n```"
            history.append({"role": "user", "content": f"Observation: {obs_display}"})

        else:
            # Exhausted MAX_STEPS without FINISH
            answer = "Maximum steps reached without a conclusive answer."
            loop_log.append(f"⚠ Reached step limit ({MAX_STEPS}).")

        # ── Build report ─────────────────────────────────────────────────────
        loop_section = "\n\n---\n\n".join(loop_log)
        report = (
            f"# ReAct — {user_input[:80]}\n\n"
            f"## Loop (Thought / Action / Observe)\n\n"
            f"{loop_section}\n\n"
            f"## Answer\n\n"
            f"{answer or '_No conclusive answer reached._'}\n\n"
            f"---\n*Generated by react-agent (Tier 1 — LLM enabled)*\n"
        )

        # ── Memory ───────────────────────────────────────────────────────────
        if ctx.memory:
            await ctx.memory.record(
                f"react: {user_input[:80]}",
                importance=0.5,
                task_id=task["task_id"],
            )

        return {
            "task_id": task["task_id"],
            "status": "completed",
            "output": [{"type": "text", "text": report}],
        }

    # ──────────────────────────────────────────── helpers ──────────────────

    def _build_messages(self, history, first_user_msg):
        """Concatenate history into a single user-turn string for ctx.llm.chat()."""
        if not history:
            return first_user_msg or ""
        parts_list = []
        for msg in history:
            role_label = "Assistant" if msg["role"] == "assistant" else "Human"
            parts_list.append(f"{role_label}: {msg['content']}")
        return "\n\n".join(parts_list)

    def _parse_react(self, raw):
        """Extract (thought, action_name, action_args, error) from LLM output.

        Expected format (two consecutive lines):
            Thought: <text>
            Action: tool_name({"key": "val"})
        """
        thought_match = re.search(r"Thought:\s*(.+)", raw)
        action_match = re.search(r"Action:\s*(\w+)\((\{.*\})\)", raw, re.DOTALL)

        if not thought_match:
            return None, None, None, "Missing 'Thought:' line"
        if not action_match:
            return thought_match.group(1).strip(), None, None, "Missing 'Action:' line"

        thought = thought_match.group(1).strip()
        action_name = action_match.group(1)
        try:
            action_args = json.loads(action_match.group(2))
        except json.JSONDecodeError as exc:
            return thought, action_name, None, f"Invalid JSON in Action args: {exc}"

        return thought, action_name, action_args, None

    async def _call_tool(self, ctx, tool_name, args):
        """Dispatch to bash_executor or file_io; return stdout/content as string."""
        if tool_name == "bash_executor":
            cmd = args.get("command", "echo 'no command'")
            timeout = int(args.get("timeout_seconds", 30))
            return await self._run_command(ctx, cmd, timeout_seconds=timeout)

        if tool_name == "file_io":
            path = args.get("path", "")
            if ctx.tools is not None:
                result = await ctx.tools.call("file_io", args)
                return result.get("content", "")
            # Fallback: stdlib
            try:
                with open(path, encoding="utf-8") as fh:
                    return fh.read()
            except OSError as exc:
                return f"Error reading file: {exc}"

        return f"Unknown tool: {tool_name}"

    async def _run_command(self, ctx, command, timeout_seconds=30):
        """Run a shell command, preferring ctx.tools then stdlib subprocess."""
        if ctx.tools is not None:
            result = await ctx.tools.call("bash_executor", {
                "command": command,
                "timeout_seconds": timeout_seconds,
            })
            stdout = result.get("stdout", "")
            stderr = result.get("stderr", "")
            return stdout if stdout else stderr

        loop = asyncio.get_event_loop()
        try:
            proc = await loop.run_in_executor(
                None,
                lambda: subprocess.run(
                    command,
                    shell=True,
                    capture_output=True,
                    text=True,
                    timeout=timeout_seconds,
                ),
            )
            return proc.stdout if proc.stdout else proc.stderr
        except Exception as exc:
            return f"Command error: {exc}"


agent = ReactAgent()
