//! Google Vertex AI client via direct `reqwest`.
//!
//! Anthropic-compatible backend on Google Cloud Platform via the `rawPredict`
//! endpoint. The request body is identical to the Anthropic Messages API.
//! Auth via Application Default Credentials (ADC) with an in-memory cache and
//! automatic refresh before expiry.
//!
//! # Architecture
//!
//! ```text
//! apollia-llm [feature = "cloud"]
//!   └── VertexClient : CompletionModel
//!         ├── new()          builds the client, checks the ADC file exists
//!         ├── get_token()    returns the cached token or triggers a refresh
//!         ├── refresh_token() reads the ADC file and POSTs oauth2.googleapis.com/token
//!         ├── build_request() converts CompletionRequest to the Vertex JSON body
//!         └── do_complete()  POST rawPredict -> CompletionResponse
//! ```
//!
//! # ADC file
//!
//! Path resolved in order:
//! 1. The `GOOGLE_APPLICATION_CREDENTIALS` environment variable
//! 2. `~/.config/gcloud/application_default_credentials.json`
//!
//! Only the `authorized_user` type (gcloud credentials) is supported.
//! Service-account JSON keys are out of scope.

use std::path::PathBuf;
use std::pin::Pin;
use std::sync::Arc;
use std::time::Instant;

use chrono::{DateTime, Duration, Utc};
use futures::Stream;
use tokio::sync::Mutex;
use tokio_util::sync::CancellationToken;

use apollia_core::VertexConfig;

use crate::backends::anthropic::AnthropicClient;
use crate::retry::RetryPolicy;
use crate::types::{
    CompletionModel, CompletionRequest, CompletionResponse, LlmError, MessageContent, Role,
    StreamChunk,
};

// ── Constants ─────────────────────────────────────────────────────────────

/// Vertex AI API base URL (without the region).
const VERTEX_API_BASE: &str = "https://aiplatform.googleapis.com";

/// Anthropic protocol version sent in the body of Vertex requests.
const ANTHROPIC_VERSION_VERTEX: &str = "vertex-2023-10-16";

/// Google OAuth2 refresh endpoint.
const TOKEN_REFRESH_URL: &str = "https://oauth2.googleapis.com/token";

/// Safety margin before expiry (seconds): renews the token 60 s before it lapses.
const TOKEN_EXPIRY_MARGIN_SECS: i64 = 60;

// ── ADC: credentials deserialization ──────────────────────────────────────

/// Contents of the `authorized_user` ADC file generated by `gcloud auth application-default login`.
#[derive(serde::Deserialize)]
struct AdcCredentials {
    #[serde(rename = "type")]
    credential_type: String,
    client_id: String,
    client_secret: String,
    refresh_token: String,
}

/// Response of the OAuth2 refresh endpoint.
#[derive(serde::Deserialize)]
struct TokenRefreshResponse {
    access_token: String,
    expires_in: i64,
}

// ── Token cache ───────────────────────────────────────────────────────────

/// Cached OAuth2 access token with its expiry instant.
#[derive(Debug, Clone)]
struct GoogleToken {
    access_token: String,
    expires_at: DateTime<Utc>,
}

impl GoogleToken {
    /// Return `true` if the token is still usable, accounting for the safety margin.
    fn is_valid(&self) -> bool {
        Utc::now() < self.expires_at - Duration::seconds(TOKEN_EXPIRY_MARGIN_SECS)
    }
}

// ── Request types: Vertex / Anthropic format ──────────────────────────────

/// Request body for the Vertex AI `rawPredict` endpoint.
///
/// Identical format to the Anthropic Messages API, with `anthropic_version`
/// in the body instead of a header.
#[derive(serde::Serialize)]
struct VertexRequest {
    anthropic_version: &'static str,
    max_tokens: u32,
    messages: Vec<VertexMessage>,
    #[serde(skip_serializing_if = "Option::is_none")]
    system: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    temperature: Option<f32>,
}

/// Message in the Vertex / Anthropic format.
#[derive(serde::Serialize)]
struct VertexMessage {
    role: &'static str,
    content: serde_json::Value,
}

/// HTTP client for Google Vertex AI, Anthropic models via `rawPredict`.
///
/// Auth via Application Default Credentials (ADC) with an in-memory cache.
/// The token is refreshed automatically 60 seconds before it expires.
///
/// Shareable via `Arc<VertexClient>`: `reqwest::Client` and `Arc<Mutex<...>>`
/// are `Clone + Send + Sync`.
pub struct VertexClient {
    config: VertexConfig,
    http_client: reqwest::Client,
    token_cache: Arc<Mutex<Option<GoogleToken>>>,
    retry_policy: RetryPolicy,
    cancel: CancellationToken,
}

impl VertexClient {
    /// Build a Vertex AI client and check the ADC file is present.
    ///
    /// Returns `LlmError::Unauthorized` if the ADC file is absent at startup.
    /// A missing file in production is detected immediately (fail fast).
    pub fn new(config: &VertexConfig, cancel: CancellationToken) -> Result<Self, LlmError> {
        let path = adc_credentials_path();
        if !path.exists() {
            return Err(LlmError::Unauthorized);
        }
        Ok(Self {
            config: config.clone(),
            http_client: reqwest::Client::new(),
            token_cache: Arc::new(Mutex::new(None)),
            retry_policy: RetryPolicy::default(),
            cancel,
        })
    }

    /// Return a valid Bearer token, refreshing from OAuth2 if needed.
    ///
    /// 1. Check the cache: if the token has not expired, return it directly.
    /// 2. Otherwise, read the ADC file and POST `https://oauth2.googleapis.com/token`.
    /// 3. Update the cache with the new token.
    async fn get_token(&self) -> Result<String, LlmError> {
        {
            let cache = self.token_cache.lock().await;
            if let Some(token) = cache.as_ref() {
                if token.is_valid() {
                    return Ok(token.access_token.clone());
                }
            }
        }

        let new_token = self.refresh_token().await?;
        let access_token = new_token.access_token.clone();
        {
            let mut cache = self.token_cache.lock().await;
            *cache = Some(new_token);
        }
        Ok(access_token)
    }

    /// Read the ADC file and call the OAuth2 refresh endpoint.
    async fn refresh_token(&self) -> Result<GoogleToken, LlmError> {
        let path = adc_credentials_path();
        let content = std::fs::read_to_string(&path).map_err(|e| {
            LlmError::InferenceError(format!(
                "cannot read ADC credentials file {}: {e}",
                path.display()
            ))
        })?;

        let creds: AdcCredentials = serde_json::from_str(&content)
            .map_err(|e| LlmError::InferenceError(format!("invalid ADC file format: {e}")))?;

        if creds.credential_type != "authorized_user" {
            return Err(LlmError::InferenceError(format!(
                "ADC credential type '{}' not supported - \
                 run `gcloud auth application-default login` to generate user credentials",
                creds.credential_type
            )));
        }

        let params = [
            ("client_id", creds.client_id.as_str()),
            ("client_secret", creds.client_secret.as_str()),
            ("refresh_token", creds.refresh_token.as_str()),
            ("grant_type", "refresh_token"),
        ];

        let response = self
            .http_client
            .post(TOKEN_REFRESH_URL)
            .form(&params)
            .send()
            .await
            .map_err(|e| {
                LlmError::InferenceError(format!("OAuth2 token refresh request failed: {e}"))
            })?;

        if response.status().as_u16() == 401 {
            return Err(LlmError::Unauthorized);
        }
        if !response.status().is_success() {
            let status = response.status().as_u16();
            let body = response.text().await.unwrap_or_default();
            return Err(LlmError::HttpError { status, body });
        }

        let refresh: TokenRefreshResponse = response.json().await.map_err(|e| {
            LlmError::ParseError(format!("cannot parse OAuth2 token refresh response: {e}"))
        })?;

        Ok(GoogleToken {
            access_token: refresh.access_token,
            expires_at: Utc::now() + Duration::seconds(refresh.expires_in),
        })
    }

    /// Build the `rawPredict` URL for this client.
    fn endpoint_url(&self) -> String {
        format!(
            "{}/v1/projects/{}/locations/{}/publishers/anthropic/models/{}:rawPredict",
            VERTEX_API_BASE, self.config.project_id, self.config.location, self.config.model_id,
        )
    }

    /// Convert a [`CompletionRequest`] into a Vertex AI JSON body.
    ///
    /// Extracts the first `System` message into the top-level `system` field.
    /// `Tool` messages (tool results) are sent with the `user` role.
    fn build_request(&self, req: &CompletionRequest) -> VertexRequest {
        let system = req.messages.iter().find_map(|m| {
            if m.role == Role::System {
                if let MessageContent::Text(text) = &m.content {
                    return Some(text.clone());
                }
            }
            None
        });

        let messages = req
            .messages
            .iter()
            .filter(|m| m.role != Role::System)
            .filter_map(|m| {
                let role: &'static str = match m.role {
                    Role::User | Role::Tool => "user",
                    Role::Assistant => "assistant",
                    Role::System => return None,
                };

                let content = match &m.content {
                    MessageContent::Text(text) => serde_json::Value::String(text.clone()),
                    MessageContent::ToolResult {
                        content,
                        tool_call_id,
                    } => serde_json::json!([{
                        "type": "tool_result",
                        "tool_use_id": tool_call_id,
                        "content": content,
                    }]),
                    MessageContent::WithToolCalls { text, tool_calls } => {
                        let mut blocks: Vec<serde_json::Value> = Vec::new();
                        if !text.is_empty() {
                            blocks.push(serde_json::json!({ "type": "text", "text": text }));
                        }
                        for tc in tool_calls {
                            blocks.push(serde_json::json!({
                                "type": "tool_use",
                                "id": tc.id,
                                "name": tc.name,
                                "input": tc.arguments,
                            }));
                        }
                        serde_json::Value::Array(blocks)
                    }
                };

                Some(VertexMessage { role, content })
            })
            .collect();

        VertexRequest {
            anthropic_version: ANTHROPIC_VERSION_VERTEX,
            max_tokens: req.max_tokens.unwrap_or(4096),
            messages,
            system,
            temperature: req.temperature,
        }
    }

    /// Make a single `rawPredict` HTTP call without retry.
    ///
    /// Maps HTTP codes to [`LlmError`] variants:
    /// - 401 to [`LlmError::Unauthorized`] (no retry)
    /// - 429 to [`LlmError::RateLimit`] (retryable)
    /// - 503 to [`LlmError::ServiceUnavailable`] (retryable)
    async fn do_complete(&self, req: CompletionRequest) -> Result<CompletionResponse, LlmError> {
        let started = Instant::now();
        let token = self.get_token().await?;
        let body = self.build_request(&req);
        let url = self.endpoint_url();

        let http_response = self
            .http_client
            .post(&url)
            .bearer_auth(&token)
            .header(
                reqwest::header::CONTENT_TYPE,
                reqwest::header::HeaderValue::from_static("application/json"),
            )
            .json(&body)
            .send()
            .await
            .map_err(|e| LlmError::HttpError {
                status: e.status().map(|s| s.as_u16()).unwrap_or(0),
                body: e.to_string(),
            })?;

        let status = http_response.status();
        if !status.is_success() {
            let body_text = http_response.text().await.unwrap_or_default();
            return Err(match status.as_u16() {
                401 => LlmError::Unauthorized,
                429 => LlmError::RateLimit,
                503 => LlmError::ServiceUnavailable,
                code => LlmError::HttpError {
                    status: code,
                    body: body_text,
                },
            });
        }

        let json: serde_json::Value = http_response.json().await.map_err(|e| {
            LlmError::ParseError(format!("failed to decode Vertex AI response: {e}"))
        })?;

        let mut result = AnthropicClient::parse_response(&json)?;
        result.latency_ms = started.elapsed().as_millis() as u64;
        // Vertex AI does not provide the Anthropic pricing detail, so cost_usd stays None.
        result.usage.cost_usd = None;

        tracing::info!(
            project = %self.config.project_id,
            location = %self.config.location,
            model = %self.config.model_id,
            prompt_tokens = result.usage.prompt_tokens,
            completion_tokens = result.usage.completion_tokens,
            latency_ms = result.latency_ms,
            "Vertex AI complete() done"
        );

        Ok(result)
    }
}

#[async_trait::async_trait]
impl CompletionModel for VertexClient {
    /// Send an inference request and return the full response.
    ///
    /// Uses [`RetryPolicy`] for transient errors (429, 503). Non-retryable
    /// errors (401) are propagated immediately.
    async fn complete(&self, req: CompletionRequest) -> Result<CompletionResponse, LlmError> {
        self.retry_policy
            .execute(self.cancel.clone(), || {
                let req = req.clone();
                async move { self.do_complete(req).await }
            })
            .await
    }

    /// Streaming not supported for Vertex AI in this version.
    ///
    /// Returns `LlmError::InferenceError`. SSE streaming via Vertex will be
    /// implemented in a future version.
    async fn stream(
        &self,
        _req: CompletionRequest,
    ) -> Result<Pin<Box<dyn Stream<Item = Result<StreamChunk, LlmError>> + Send>>, LlmError> {
        Err(LlmError::InferenceError(
            "streaming not supported for Vertex AI backend in this version".to_owned(),
        ))
    }

    /// Return `true`: the ADC file is present and the client is ready.
    fn is_available(&self) -> bool {
        true
    }

    /// Logical backend name in the `LlmRouter`.
    fn backend_name(&self) -> &str {
        "vertex"
    }

    /// Identifier of the Anthropic model configured on Vertex.
    fn model_id(&self) -> &str {
        &self.config.model_id
    }
}

// ── Helpers ───────────────────────────────────────────────────────────────

/// Return the path to the ADC file to use.
///
/// Checks `GOOGLE_APPLICATION_CREDENTIALS` first, then the default gcloud path
/// `~/.config/gcloud/application_default_credentials.json`.
fn adc_credentials_path() -> PathBuf {
    if let Ok(p) = std::env::var("GOOGLE_APPLICATION_CREDENTIALS") {
        return PathBuf::from(p);
    }
    let home = apollia_core::paths::home_string()
        .unwrap_or_else(|| std::env::temp_dir().display().to_string());
    PathBuf::from(home).join(".config/gcloud/application_default_credentials.json")
}

#[cfg(test)]
mod tests {
    use super::*;

    fn make_config() -> VertexConfig {
        VertexConfig {
            enabled: true,
            project_id: "test-project".to_owned(),
            location: "us-east5".to_owned(),
            model_id: "claude-test@001".to_owned(),
        }
    }

    fn make_client() -> VertexClient {
        VertexClient {
            config: make_config(),
            http_client: reqwest::Client::new(),
            token_cache: Arc::new(Mutex::new(None)),
            retry_policy: RetryPolicy::default(),
            cancel: CancellationToken::new(),
        }
    }

    // GIVEN a VertexConfig deserialized with enabled = false
    // WHEN reading the enabled field
    // THEN it is false
    #[test]
    fn test_vertex_config_disabled_by_default() {
        let config: VertexConfig = toml::from_str(
            r#"
            enabled = false
            project_id = "test"
            location = "us-east5"
            model_id = "test"
        "#,
        )
        .expect("valid toml");
        assert!(!config.enabled);
    }

    // GIVEN a valid token in cache (expires in 1h)
    // WHEN get_token() is called
    // THEN the cached token is returned without a network call
    #[tokio::test]
    async fn test_token_cache_returns_cached_when_valid() {
        let client = make_client();
        {
            let mut cache = client.token_cache.lock().await;
            *cache = Some(GoogleToken {
                access_token: "valid-cached-token".to_owned(),
                expires_at: Utc::now() + Duration::hours(1),
            });
        }

        let token = client.get_token().await.expect("cache hit must succeed");
        assert_eq!(token, "valid-cached-token");
    }

    // GIVEN an expired token in cache (expires_at in the past)
    // WHEN get_token() is called
    // THEN a refresh is attempted (fails because no ADC file); the expired token is not returned
    #[tokio::test]
    async fn test_expired_token_triggers_refresh() {
        let client = make_client();
        {
            let mut cache = client.token_cache.lock().await;
            *cache = Some(GoogleToken {
                access_token: "expired-token".to_owned(),
                expires_at: Utc::now() - Duration::hours(1),
            });
        }

        // The expired token is not returned; a refresh is attempted
        let result = client.get_token().await;
        assert!(
            result.is_err(),
            "expired token must trigger refresh, not return the stale value"
        );
        // Make sure the expired token was not the one returned
        assert!(!matches!(result, Ok(ref t) if t == "expired-token"));
    }

    // GIVEN a request with a system + user message
    // WHEN build_request() is called
    // THEN the system message is extracted into the `system` field and absent from the messages
    #[test]
    fn test_build_request_extracts_system_message() {
        use crate::types::ChatMessage;

        let client = make_client();
        let req = CompletionRequest {
            messages: vec![
                ChatMessage::system("Be helpful"),
                ChatMessage::user("Hello"),
            ],
            ..Default::default()
        };

        let vertex_req = client.build_request(&req);
        assert_eq!(vertex_req.system.as_deref(), Some("Be helpful"));
        assert_eq!(vertex_req.messages.len(), 1);
        assert_eq!(vertex_req.messages[0].role, "user");
    }

    // GIVEN a Vertex config with project, location and model
    // WHEN endpoint_url() is called
    // THEN the URL contains the correct rawPredict path
    #[test]
    fn test_endpoint_url_format() {
        let client = make_client();
        let url = client.endpoint_url();
        assert!(url.contains("test-project"), "URL must contain project_id");
        assert!(url.contains("us-east5"), "URL must contain location");
        assert!(url.contains("claude-test@001"), "URL must contain model_id");
        assert!(
            url.ends_with(":rawPredict"),
            "URL must end with :rawPredict"
        );
    }

    // GIVEN no ADC file present (GOOGLE_APPLICATION_CREDENTIALS points at a nonexistent path)
    // WHEN VertexClient::new() is called
    // THEN LlmError::Unauthorized is returned
    #[test]
    fn test_new_returns_unauthorized_when_adc_absent() {
        // Point at a file that does not exist
        std::env::set_var(
            "GOOGLE_APPLICATION_CREDENTIALS",
            "/tmp/apollia-test-nonexistent-adc.json",
        );
        let config = make_config();
        let cancel = CancellationToken::new();
        let result = VertexClient::new(&config, cancel);
        // Clean up the env var for the other tests
        std::env::remove_var("GOOGLE_APPLICATION_CREDENTIALS");

        assert!(
            matches!(result, Err(LlmError::Unauthorized)),
            "absent ADC must produce Unauthorized, got: {:?}",
            result.err()
        );
    }

    #[tokio::test]
    #[ignore = "requires valid GCP credentials and network access"]
    async fn test_vertex_integration() {
        let config = VertexConfig {
            enabled: true,
            project_id: std::env::var("GCP_PROJECT_ID").expect("GCP_PROJECT_ID required"),
            location: "us-east5".to_owned(),
            model_id: "claude-sonnet-4-6@20251001".to_owned(),
        };
        let cancel = CancellationToken::new();
        let client = VertexClient::new(&config, cancel).expect("ADC must be present");

        let req = CompletionRequest {
            messages: vec![crate::types::ChatMessage::user("Say 'ok'")],
            max_tokens: Some(10),
            ..Default::default()
        };
        let response = client
            .complete(req)
            .await
            .expect("Vertex call must succeed");
        assert!(!response.content.is_empty());
    }
}
