use serde::{Deserialize, Serialize};

use crate::events::AgentId;
use crate::result::InputResponseData;

/// Task submitted by the runtime to the agent through the AIP bridge.
///
/// Carries all the context the agent needs to handle the request:
/// identifier, multi-modal input, conversation history, and timeout.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct AIPTask {
    /// Unique task identifier (UUID v4 generated by the runtime).
    pub task_id: String,
    /// Context identifier grouping related tasks (e.g. a user session).
    pub context_id: String,
    /// Invoked A2A skill. Populated only during an A2A delegation; `None`
    /// for root executions, trigger-fired tasks, or direct invocation via
    /// the CLI / REST API without a targeted skill.
    ///
    /// Multi-skill workers declare one handler per operation via the
    /// `@skill(id="...")` decorator; the SDK-side dispatch glue reads this
    /// field and routes automatically to the right handler. Convention:
    /// full ID such as `"chart.bar"` (not just the suffix).
    #[serde(default)]
    pub skill_id: Option<String>,
    /// Identifier of the project this task belongs to.
    ///
    /// `None` for standalone sessions. Used by the runtime to prefix the
    /// agent's effective memory namespace: `"{project_id}:{memory_namespace}"`.
    #[serde(default)]
    pub project_id: Option<String>,
    /// Multi-modal task input.
    pub input: AIPInput,
    /// History of previous exchanges within this context.
    pub history: Vec<AIPMessage>,
    /// Timeout in seconds (None = use the runtime default).
    pub timeout_seconds: Option<u32>,
    /// `true` if this execution is a resumption after an `input_required`.
    ///
    /// The agent checks this field to tell a first call apart from a resume.
    /// Always `false` on the first call (default value).
    #[serde(default)]
    pub is_resumed: bool,
    /// Identifier of the in-flight response message (chat mode only).
    ///
    /// Populated by the `ChatSessionManager` before invoking the agent so the
    /// `RuntimeContext` can emit `ChatToken` events the frontend can route.
    /// `None` in task mode (CLI `agent run`), where there is no session to tag.
    #[serde(default)]
    pub message_id: Option<String>,
    /// Human response provided after suspension. Populated only when `is_resumed == true`.
    ///
    /// Holds the decision (`approved`), the optional reason, and the JSON
    /// context the agent serialized at the time of `input_required`.
    /// Built by `TaskRepository::rebuild_for_resume()`.
    #[serde(default)]
    pub input_response: Option<InputResponseData>,
    /// A2A delegation chain: IDs of the parent agents in the chain.
    ///
    /// Empty for a root task. Extended by the runtime on each A2A delegation
    /// with the ID of the delegating agent. Used by `a2a::validate_chain` to
    /// detect cycles and enforce the hop limit (default 5).
    #[serde(default)]
    pub delegation_chain: Vec<AgentId>,
}

/// Multi-modal input of an AIP task.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct AIPInput {
    /// The parts that make up the input (text, files, structured data).
    pub parts: Vec<AIPPart>,
}

/// Multi-modal part aligned with the A2A protocol.
///
/// Uses a JSON `type` discriminant for polymorphic deserialization.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "type", rename_all = "snake_case")]
pub enum AIPPart {
    /// Text content.
    Text(TextPart),
    /// Binary file (inline or referenced by URI).
    File(FilePart),
    /// Arbitrary structured JSON data.
    Data(DataPart),
}

/// Text part of an input or output.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TextPart {
    /// Text content.
    pub text: String,
}

/// File part of an input or output.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct FilePart {
    /// File name.
    pub name: String,
    /// MIME type (e.g. "application/pdf", "image/png").
    pub mime_type: String,
    /// Inline binary content (None if referenced by URI).
    pub data: Option<Vec<u8>>,
    /// Reference URI (None if data is inline).
    pub uri: Option<String>,
}

/// Structured JSON data part.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DataPart {
    /// Arbitrary JSON data.
    pub data: serde_json::Value,
}

/// Message in the conversation history of an AIP context.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AIPMessage {
    /// Role of the sender: "user" or "agent".
    pub role: String,
    /// Parts of the message.
    pub parts: Vec<AIPPart>,
}

#[cfg(test)]
mod tests {
    use super::*;
    use serde_json::json;

    #[test]
    fn test_ac2_aip_task_multi_part_input() {
        // GIVEN
        let task = AIPTask {
            task_id: "550e8400-e29b-41d4-a716-446655440000".into(),
            context_id: "session-abc".into(),
            input: AIPInput {
                parts: vec![
                    AIPPart::Text(TextPart {
                        text: "Génère un devis".into(),
                    }),
                    AIPPart::Data(DataPart {
                        data: json!({ "client": "Dupont" }),
                    }),
                ],
            },
            history: vec![],
            timeout_seconds: None,
            ..AIPTask::default()
        };
        // WHEN
        let cloned = task.clone();
        // THEN
        assert_eq!(cloned.input.parts.len(), 2);
        assert!(!cloned.task_id.is_empty());
    }

    #[test]
    fn test_aip_part_text_round_trip() {
        // GIVEN
        let part = AIPPart::Text(TextPart {
            text: "Bonjour".into(),
        });
        // WHEN
        let json = serde_json::to_string(&part).expect("serialize failed");
        let restored: AIPPart = serde_json::from_str(&json).expect("deserialize failed");
        // THEN
        assert!(json.contains("\"type\":\"text\""));
        match restored {
            AIPPart::Text(t) => assert_eq!(t.text, "Bonjour"),
            _ => panic!("expected TextPart"),
        }
    }

    #[test]
    fn test_aip_part_file_with_uri() {
        // GIVEN
        let part = AIPPart::File(FilePart {
            name: "rapport.pdf".into(),
            mime_type: "application/pdf".into(),
            data: None,
            uri: Some("file:///tmp/rapport.pdf".into()),
        });
        // WHEN
        let json = serde_json::to_string(&part).expect("serialize failed");
        let restored: AIPPart = serde_json::from_str(&json).expect("deserialize failed");
        // THEN
        match restored {
            AIPPart::File(f) => {
                assert_eq!(f.name, "rapport.pdf");
                assert!(f.data.is_none());
                assert!(f.uri.is_some());
            }
            _ => panic!("expected FilePart"),
        }
    }

    #[test]
    fn test_aip_message_round_trip() {
        // GIVEN
        let msg = AIPMessage {
            role: "user".into(),
            parts: vec![AIPPart::Text(TextPart {
                text: "Bonjour agent".into(),
            })],
        };
        // WHEN
        let json = serde_json::to_string(&msg).expect("serialize failed");
        let restored: AIPMessage = serde_json::from_str(&json).expect("deserialize failed");
        // THEN
        assert_eq!(restored.role, "user");
        assert_eq!(restored.parts.len(), 1);
    }
}
