//! SQLite persistence for triggers: `trigger_history` and `trigger_state`.
//!
//! [`TriggerPersistence`] is a **synchronous** struct (no Tokio actor). It is
//! meant to be used directly from [`crate::engine::TriggerEngine`] (the SQLite
//! connection is `Send`, so it lives in the actor's Tokio task) or via
//! `spawn_blocking` when called from a context that cannot tolerate blocking.
//!
//! The [`include_str`] migration is idempotent (`CREATE TABLE IF NOT EXISTS`).

use std::collections::HashMap;

use chrono::{DateTime, Utc};
use rusqlite::{params, Connection};

// --- Errors ----------------------------------------------------------------

/// Trigger persistence errors.
#[derive(thiserror::Error, Debug)]
pub enum TriggerPersistenceError {
    /// Underlying SQLite error.
    #[error("database error: {0}")]
    Database(#[from] rusqlite::Error),

    /// Failed to parse a timestamp stored in the database.
    #[error("timestamp parse error: {0}")]
    TimestampParse(String),
}

// --- Result types ------------------------------------------------------------

/// History entry returned by [`TriggerPersistence::query_history`].
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct TriggerHistoryEntry {
    /// Unique entry identifier (hex randomblob generated by SQLite).
    pub id: String,
    /// Identifier of the relevant trigger.
    pub trigger_id: String,
    /// Target agent name.
    pub agent_name: String,
    /// Fire timestamp.
    pub fired_at: DateTime<Utc>,
    /// Identifier of the submitted task; `None` when `status` is `skipped` or `error`.
    pub task_id: Option<String>,
    /// Status: `"fired"` | `"skipped"` | `"error"`.
    pub status: String,
    /// Reason for the skip or error; `None` when `status` is `"fired"`.
    pub reason: Option<String>,
    /// Full trigger JSON payload; `None` when absent (timer without payload).
    pub payload_json: Option<String>,
    /// Dispatch time in milliseconds (trigger reception to task submission).
    pub dispatch_ms: Option<i64>,
}

/// Current state of a trigger in `trigger_state`.
#[derive(Debug, Clone)]
pub struct TriggerStateRow {
    /// Trigger identifier.
    pub trigger_id: String,
    /// Timestamp of the last successful fire; `None` if never fired.
    pub last_fired: Option<DateTime<Utc>>,
    /// Cumulative count of successful fires.
    pub fire_count: u64,
    /// Cumulative count of skips.
    pub skip_count: u64,
    /// Whether the trigger is enabled in `trigger_state`.
    pub enabled: bool,
}

/// Trigger statistics recomputed from the `trigger_history` table.
#[derive(Debug, Clone)]
pub struct TriggerStats {
    /// Count of successful fires.
    pub fire_count: u64,
    /// Count of skips.
    pub skip_count: u64,
    /// Timestamp of the last successful fire; `None` if never fired.
    pub last_fired: Option<DateTime<Utc>>,
}

// --- Helpers -----------------------------------------------------------------

/// Adds columns to a table if they do not exist yet.
///
/// Uses `PRAGMA table_info` to list the existing columns, then runs
/// `ALTER TABLE ADD COLUMN` only for the missing ones.
fn add_columns_if_missing(
    conn: &Connection,
    table: &str,
    columns: &[(&str, &str)],
) -> Result<(), rusqlite::Error> {
    let mut stmt = conn.prepare(&format!("SELECT name FROM pragma_table_info('{table}')"))?;
    let existing: Vec<String> = stmt
        .query_map([], |row| row.get::<_, String>(0))?
        .collect::<rusqlite::Result<Vec<_>>>()?;

    for (col_name, col_type) in columns {
        if !existing.iter().any(|c| c == col_name) {
            conn.execute_batch(&format!(
                "ALTER TABLE {table} ADD COLUMN {col_name} {col_type};"
            ))?;
        }
    }
    Ok(())
}

/// Common context for recording a `trigger_history` entry: trigger identity,
/// target agent, timestamp, and optional JSON payload.
///
/// Groups the fields shared by [`TriggerPersistence::record_fired`],
/// [`TriggerPersistence::record_skipped`] and [`TriggerPersistence::record_error`].
pub struct TriggerRecord<'a> {
    /// Identifier of the relevant trigger.
    pub trigger_id: &'a str,
    /// Target agent name.
    pub agent_name: &'a str,
    /// Fire timestamp.
    pub fired_at: DateTime<Utc>,
    /// Full trigger JSON payload, `None` when absent (timer without payload).
    pub payload_json: Option<&'a str>,
}

// --- TriggerPersistence ------------------------------------------------------

/// Persistence interface for triggers, wrapping `rusqlite::Connection`.
///
/// Meant to be owned by [`crate::engine::TriggerEngine`]. The SQLite connection
/// implements `Send`, which allows storing it inside a `tokio::spawn`.
pub struct TriggerPersistence {
    conn: Connection,
}

impl TriggerPersistence {
    /// Opens (or creates) the SQLite database and applies the trigger tables migration.
    ///
    /// Uses `CREATE TABLE IF NOT EXISTS`, so it is idempotent. Fails fast: a
    /// migration error is fatal (`.expect`), in line with the runtime's
    /// fail-fast policy.
    pub fn open(db_path: &std::path::Path) -> Result<Self, TriggerPersistenceError> {
        let conn = Connection::open(db_path)?;
        // WAL for better concurrent write performance.
        conn.execute_batch("PRAGMA journal_mode=WAL;")?;
        conn.execute_batch(include_str!(
            "../../apollia-tools/migrations/003_trigger_tables.sql"
        ))?;
        // Add payload_json and dispatch_ms columns when missing, checking
        // existence via PRAGMA table_info.
        add_columns_if_missing(
            &conn,
            "trigger_history",
            &[("payload_json", "TEXT"), ("dispatch_ms", "INTEGER")],
        )?;
        Ok(Self { conn })
    }

    /// Persists a successful fire in `trigger_history` and increments `fire_count`.
    ///
    /// Also updates `trigger_state.last_fired` with `fired_at`.
    /// `payload_json` and `dispatch_ms` are optional for backward compatibility.
    pub fn record_fired(
        &mut self,
        record: TriggerRecord<'_>,
        task_id: &str,
        dispatch_ms: Option<i64>,
    ) -> Result<(), TriggerPersistenceError> {
        let fired_at_str = record.fired_at.to_rfc3339();
        self.conn.execute(
            "INSERT INTO trigger_history \
             (trigger_id, agent_name, fired_at, task_id, status, payload_json, dispatch_ms) \
             VALUES (?1, ?2, ?3, ?4, 'fired', ?5, ?6)",
            params![
                record.trigger_id,
                record.agent_name,
                fired_at_str,
                task_id,
                record.payload_json,
                dispatch_ms
            ],
        )?;
        self.conn.execute(
            "INSERT INTO trigger_state (trigger_id, last_fired, fire_count, skip_count) \
             VALUES (?1, ?2, 1, 0) \
             ON CONFLICT(trigger_id) DO UPDATE SET \
               last_fired = excluded.last_fired, \
               fire_count = fire_count + 1",
            params![record.trigger_id, fired_at_str],
        )?;
        Ok(())
    }

    /// Persists a skip (`on_busy=drop`) in `trigger_history` and increments `skip_count`.
    ///
    /// `payload_json` is optional and lets the payload be traced even on a skip.
    pub fn record_skipped(
        &mut self,
        record: TriggerRecord<'_>,
        reason: &str,
    ) -> Result<(), TriggerPersistenceError> {
        let fired_at_str = record.fired_at.to_rfc3339();
        self.conn.execute(
            "INSERT INTO trigger_history \
             (trigger_id, agent_name, fired_at, task_id, status, reason, payload_json) \
             VALUES (?1, ?2, ?3, NULL, 'skipped', ?4, ?5)",
            params![
                record.trigger_id,
                record.agent_name,
                fired_at_str,
                reason,
                record.payload_json
            ],
        )?;
        self.conn.execute(
            "INSERT INTO trigger_state (trigger_id, fire_count, skip_count) \
             VALUES (?1, 0, 1) \
             ON CONFLICT(trigger_id) DO UPDATE SET \
               skip_count = skip_count + 1",
            params![record.trigger_id],
        )?;
        Ok(())
    }

    /// Persists a `TaskRouter` submission error in `trigger_history`.
    ///
    /// `payload_json` is optional and lets the payload be traced even on an error.
    pub fn record_error(
        &mut self,
        record: TriggerRecord<'_>,
        error: &str,
    ) -> Result<(), TriggerPersistenceError> {
        let fired_at_str = record.fired_at.to_rfc3339();
        self.conn.execute(
            "INSERT INTO trigger_history \
             (trigger_id, agent_name, fired_at, task_id, status, reason, payload_json) \
             VALUES (?1, ?2, ?3, NULL, 'error', ?4, ?5)",
            params![
                record.trigger_id,
                record.agent_name,
                fired_at_str,
                error,
                record.payload_json
            ],
        )?;
        Ok(())
    }

    /// Returns the last `limit` entries for a given trigger, sorted `fired_at DESC`.
    pub fn query_history(
        &self,
        trigger_id: &str,
        limit: usize,
    ) -> Result<Vec<TriggerHistoryEntry>, TriggerPersistenceError> {
        let mut stmt = self.conn.prepare(
            "SELECT id, trigger_id, agent_name, fired_at, task_id, status, reason, \
                    payload_json, dispatch_ms \
             FROM trigger_history \
             WHERE trigger_id = ?1 \
             ORDER BY fired_at DESC \
             LIMIT ?2",
        )?;

        let mut entries = Vec::new();
        let rows = stmt.query_map(params![trigger_id, limit as i64], |row| {
            Ok(RawHistoryRow {
                id: row.get(0)?,
                trigger_id: row.get(1)?,
                agent_name: row.get(2)?,
                fired_at: row.get(3)?,
                task_id: row.get(4)?,
                status: row.get(5)?,
                reason: row.get(6)?,
                payload_json: row.get(7)?,
                dispatch_ms: row.get(8)?,
            })
        })?;

        for row_result in rows {
            let row = row_result?;
            let fired_at = DateTime::parse_from_rfc3339(&row.fired_at)
                .map(|dt| dt.with_timezone(&Utc))
                .map_err(|e| TriggerPersistenceError::TimestampParse(e.to_string()))?;
            entries.push(TriggerHistoryEntry {
                id: row.id,
                trigger_id: row.trigger_id,
                agent_name: row.agent_name,
                fired_at,
                task_id: row.task_id,
                status: row.status,
                reason: row.reason,
                payload_json: row.payload_json,
                dispatch_ms: row.dispatch_ms,
            });
        }
        Ok(entries)
    }

    /// Recomputes the counters of all triggers from `trigger_history`.
    ///
    /// Returns a `trigger_id -> TriggerStats` map. Triggers with no history do
    /// not appear in the map; their counters stay at zero on the engine side.
    /// The query uses `SUM(CASE WHEN ...)` for maximum compatibility with every
    /// SQLite version bundled in rusqlite.
    pub fn load_counters(&self) -> Result<HashMap<String, TriggerStats>, TriggerPersistenceError> {
        let mut stmt = self.conn.prepare(
            "SELECT trigger_id, \
                    SUM(CASE WHEN status = 'fired'   THEN 1 ELSE 0 END) AS fire_count, \
                    SUM(CASE WHEN status = 'skipped' THEN 1 ELSE 0 END) AS skip_count, \
                    MAX(CASE WHEN status = 'fired'   THEN fired_at ELSE NULL END) AS last_fired \
             FROM trigger_history \
             GROUP BY trigger_id",
        )?;

        let mut map = HashMap::new();
        let rows = stmt.query_map([], |row| {
            Ok(RawCounterRow {
                trigger_id: row.get(0)?,
                fire_count: row.get::<_, i64>(1)?,
                skip_count: row.get::<_, i64>(2)?,
                last_fired: row.get(3)?,
            })
        })?;

        for row_result in rows {
            let row = row_result?;
            let last_fired = row
                .last_fired
                .map(|s: String| {
                    DateTime::parse_from_rfc3339(&s)
                        .map(|dt| dt.with_timezone(&Utc))
                        .map_err(|e| TriggerPersistenceError::TimestampParse(e.to_string()))
                })
                .transpose()?;
            map.insert(
                row.trigger_id,
                TriggerStats {
                    fire_count: row.fire_count as u64,
                    skip_count: row.skip_count as u64,
                    last_fired,
                },
            );
        }

        Ok(map)
    }

    /// Returns the current state of a trigger (`last_fired`, `fire_count`, `skip_count`).
    ///
    /// Returns `None` if no state exists yet for this trigger.
    pub fn get_state(
        &self,
        trigger_id: &str,
    ) -> Result<Option<TriggerStateRow>, TriggerPersistenceError> {
        let mut stmt = self.conn.prepare(
            "SELECT trigger_id, last_fired, fire_count, skip_count, enabled \
             FROM trigger_state \
             WHERE trigger_id = ?1",
        )?;

        let mut rows = stmt.query_map(params![trigger_id], |row| {
            Ok(RawStateRow {
                trigger_id: row.get(0)?,
                last_fired: row.get(1)?,
                fire_count: row.get::<_, i64>(2)?,
                skip_count: row.get::<_, i64>(3)?,
                enabled: row.get(4)?,
            })
        })?;

        match rows.next() {
            None => Ok(None),
            Some(row_result) => {
                let row = row_result?;
                let last_fired = row
                    .last_fired
                    .map(|s: String| {
                        DateTime::parse_from_rfc3339(&s)
                            .map(|dt| dt.with_timezone(&Utc))
                            .map_err(|e| TriggerPersistenceError::TimestampParse(e.to_string()))
                    })
                    .transpose()?;
                Ok(Some(TriggerStateRow {
                    trigger_id: row.trigger_id,
                    last_fired,
                    fire_count: row.fire_count as u64,
                    skip_count: row.skip_count as u64,
                    enabled: row.enabled,
                }))
            }
        }
    }
}

// --- Internal types (raw rows) -----------------------------------------------

/// Raw `trigger_history` row as read from SQLite.
struct RawHistoryRow {
    id: String,
    trigger_id: String,
    agent_name: String,
    fired_at: String,
    task_id: Option<String>,
    status: String,
    reason: Option<String>,
    payload_json: Option<String>,
    dispatch_ms: Option<i64>,
}

/// Raw `trigger_history` row aggregated by `load_counters`.
struct RawCounterRow {
    trigger_id: String,
    fire_count: i64,
    skip_count: i64,
    last_fired: Option<String>,
}

/// Raw `trigger_state` row as read from SQLite.
struct RawStateRow {
    trigger_id: String,
    last_fired: Option<String>,
    fire_count: i64,
    skip_count: i64,
    enabled: bool,
}

// --- Tests -------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;
    use tempfile::TempDir;

    /// Opens a test database in a temporary directory.
    fn open_test_db() -> (TempDir, TriggerPersistence) {
        let dir = TempDir::new().unwrap();
        let db = TriggerPersistence::open(&dir.path().join("test.db")).unwrap();
        (dir, db)
    }

    #[test]
    fn test_ac1_migration_creates_tables() {
        // GIVEN / WHEN: open_test_db applies the migration
        let (_dir, persistence) = open_test_db();
        // THEN the tables exist (query does not panic, returns empty vec)
        let entries = persistence.query_history("any", 10).unwrap();
        assert!(entries.is_empty());
    }

    #[test]
    fn test_ac2_record_fired_persists_entry() {
        // GIVEN
        let (_dir, mut persistence) = open_test_db();
        // WHEN
        persistence
            .record_fired(
                TriggerRecord {
                    trigger_id: "rapport-hebdo",
                    agent_name: "rapport-agent",
                    fired_at: Utc::now(),
                    payload_json: None,
                },
                "task-001",
                None,
            )
            .unwrap();
        // THEN entry in trigger_history
        let entries = persistence.query_history("rapport-hebdo", 10).unwrap();
        assert_eq!(entries.len(), 1);
        assert_eq!(entries[0].status, "fired");
        assert_eq!(entries[0].task_id, Some("task-001".into()));
        // AND trigger_state.fire_count = 1
        let state = persistence.get_state("rapport-hebdo").unwrap().unwrap();
        assert_eq!(state.fire_count, 1);
        assert!(state.last_fired.is_some());
    }

    #[test]
    fn test_ac3_record_skipped_persists_reason() {
        // GIVEN
        let (_dir, mut persistence) = open_test_db();
        // WHEN
        persistence
            .record_skipped(
                TriggerRecord {
                    trigger_id: "crm-sync",
                    agent_name: "crm-agent",
                    fired_at: Utc::now(),
                    payload_json: None,
                },
                "agent busy",
            )
            .unwrap();
        // THEN
        let entries = persistence.query_history("crm-sync", 10).unwrap();
        assert_eq!(entries[0].status, "skipped");
        assert!(entries[0].task_id.is_none());
        assert_eq!(entries[0].reason, Some("agent busy".into()));
        let state = persistence.get_state("crm-sync").unwrap().unwrap();
        assert_eq!(state.skip_count, 1);
        assert_eq!(state.fire_count, 0);
    }

    #[test]
    fn test_ac4_record_error_persists_error_message() {
        // GIVEN
        let (_dir, mut persistence) = open_test_db();
        // WHEN
        persistence
            .record_error(
                TriggerRecord {
                    trigger_id: "factures",
                    agent_name: "facture-agent",
                    fired_at: Utc::now(),
                    payload_json: None,
                },
                "submit failed: agent not found",
            )
            .unwrap();
        // THEN
        let entries = persistence.query_history("factures", 10).unwrap();
        assert_eq!(entries.len(), 1);
        assert_eq!(entries[0].status, "error");
        assert!(entries[0]
            .reason
            .as_deref()
            .unwrap_or("")
            .contains("submit failed"));
    }

    #[test]
    fn test_ac5_query_history_returns_n_last_entries_sorted_desc() {
        // GIVEN 5 fires spaced 1 second apart
        let (_dir, mut persistence) = open_test_db();
        let base = Utc::now();
        for i in 0..5u64 {
            let t = base + chrono::Duration::seconds(i as i64);
            persistence
                .record_fired(
                    TriggerRecord {
                        trigger_id: "rapport-hebdo",
                        agent_name: "agent",
                        fired_at: t,
                        payload_json: None,
                    },
                    &format!("task-{i}"),
                    None,
                )
                .unwrap();
        }
        // WHEN limit = 3
        let entries = persistence.query_history("rapport-hebdo", 3).unwrap();
        // THEN 3 entries, sorted DESC (most recent first)
        assert_eq!(entries.len(), 3);
        assert_eq!(entries[0].task_id, Some("task-4".into()));
        assert_eq!(entries[1].task_id, Some("task-3".into()));
        assert_eq!(entries[2].task_id, Some("task-2".into()));
    }

    // --- Extra -------------------------------------------------------------

    #[test]
    fn test_get_state_returns_none_for_unknown_trigger() {
        // GIVEN an empty database
        let (_dir, persistence) = open_test_db();
        // WHEN
        let state = persistence.get_state("unknown-trigger").unwrap();
        // THEN
        assert!(state.is_none());
    }

    #[test]
    fn test_fire_count_accumulates_across_multiple_fires() {
        // GIVEN
        let (_dir, mut persistence) = open_test_db();
        // WHEN 3 fires
        for i in 0..3u64 {
            persistence
                .record_fired(
                    TriggerRecord {
                        trigger_id: "my-trigger",
                        agent_name: "my-agent",
                        fired_at: Utc::now(),
                        payload_json: None,
                    },
                    &format!("task-{i}"),
                    None,
                )
                .unwrap();
        }
        // THEN fire_count = 3
        let state = persistence.get_state("my-trigger").unwrap().unwrap();
        assert_eq!(state.fire_count, 3);
        assert_eq!(state.skip_count, 0);
    }

    #[test]
    fn test_idempotent_migration_can_open_twice() {
        // GIVEN an already-migrated database
        let dir = TempDir::new().unwrap();
        let path = dir.path().join("test.db");
        {
            let _p = TriggerPersistence::open(&path).unwrap();
        }
        // WHEN opening again (IF NOT EXISTS, so no error)
        let result = TriggerPersistence::open(&path);
        // THEN
        assert!(result.is_ok());
    }

    // --- payload_json + dispatch_ms ----------------------------------------

    #[test]
    fn test_trigger_payload_persisted() {
        // GIVEN an in-memory TriggerPersistence
        let (_dir, mut persistence) = open_test_db();
        // WHEN record_fired with payload_json
        persistence
            .record_fired(
                TriggerRecord {
                    trigger_id: "trg-1",
                    agent_name: "agent-x",
                    fired_at: Utc::now(),
                    payload_json: Some(r#"{"key":"val"}"#),
                },
                "t-123",
                Some(45),
            )
            .unwrap();
        // THEN payload_json is persisted
        let entries = persistence.query_history("trg-1", 10).unwrap();
        assert_eq!(entries.len(), 1);
        assert_eq!(entries[0].payload_json.as_deref(), Some(r#"{"key":"val"}"#));
    }

    #[test]
    fn test_trigger_task_id_recorded() {
        // GIVEN a successful fire
        let (_dir, mut persistence) = open_test_db();
        // WHEN record_fired with task_id = "t-abc"
        persistence
            .record_fired(
                TriggerRecord {
                    trigger_id: "trg-2",
                    agent_name: "agent-y",
                    fired_at: Utc::now(),
                    payload_json: None,
                },
                "t-abc",
                None,
            )
            .unwrap();
        // THEN task_id is persisted
        let entries = persistence.query_history("trg-2", 10).unwrap();
        assert_eq!(entries[0].task_id, Some("t-abc".into()));
    }

    #[test]
    fn test_trigger_dispatch_ms_measured() {
        // GIVEN a fire
        let (_dir, mut persistence) = open_test_db();
        // WHEN record_fired with dispatch_ms = 45
        persistence
            .record_fired(
                TriggerRecord {
                    trigger_id: "trg-3",
                    agent_name: "agent-z",
                    fired_at: Utc::now(),
                    payload_json: None,
                },
                "t-456",
                Some(45),
            )
            .unwrap();
        // THEN dispatch_ms is persisted
        let entries = persistence.query_history("trg-3", 10).unwrap();
        assert_eq!(entries[0].dispatch_ms, Some(45));
    }

    #[test]
    fn test_trigger_payload_none_when_absent() {
        // GIVEN a fire without payload
        let (_dir, mut persistence) = open_test_db();
        // WHEN record_fired without payload_json or dispatch_ms
        persistence
            .record_fired(
                TriggerRecord {
                    trigger_id: "trg-4",
                    agent_name: "agent-w",
                    fired_at: Utc::now(),
                    payload_json: None,
                },
                "t-789",
                None,
            )
            .unwrap();
        // THEN the fields are None
        let entries = persistence.query_history("trg-4", 10).unwrap();
        assert!(entries[0].payload_json.is_none());
        assert!(entries[0].dispatch_ms.is_none());
    }

    #[test]
    fn test_skipped_with_payload() {
        // GIVEN a skip with payload
        let (_dir, mut persistence) = open_test_db();
        // WHEN record_skipped with payload_json
        persistence
            .record_skipped(
                TriggerRecord {
                    trigger_id: "trg-5",
                    agent_name: "agent-v",
                    fired_at: Utc::now(),
                    payload_json: Some(r#"{"action":"sync"}"#),
                },
                "agent busy",
            )
            .unwrap();
        // THEN payload_json is persisted, dispatch_ms is None (no dispatch for a skip)
        let entries = persistence.query_history("trg-5", 10).unwrap();
        assert_eq!(
            entries[0].payload_json.as_deref(),
            Some(r#"{"action":"sync"}"#)
        );
        assert!(entries[0].dispatch_ms.is_none());
    }

    // --- load_counters -----------------------------------------------------

    #[test]
    fn test_load_counters_empty_history_table() {
        // GIVEN an empty database
        let (_dir, persistence) = open_test_db();
        // WHEN
        let counters = persistence.load_counters().unwrap();
        // THEN no entries, no error
        assert!(counters.is_empty());
    }

    #[test]
    fn test_load_counters_after_3_fires() {
        // GIVEN 3 inserted fires
        let (_dir, mut persistence) = open_test_db();
        let base = Utc::now();
        for i in 0..3u64 {
            persistence
                .record_fired(
                    TriggerRecord {
                        trigger_id: "t-fires",
                        agent_name: "agent",
                        fired_at: base + chrono::Duration::seconds(i as i64),
                        payload_json: None,
                    },
                    &format!("task-{i}"),
                    None,
                )
                .unwrap();
        }
        // WHEN
        let counters = persistence.load_counters().unwrap();
        // THEN fire_count = 3
        let stats = counters.get("t-fires").expect("trigger absent de la map");
        assert_eq!(stats.fire_count, 3);
        assert_eq!(stats.skip_count, 0);
    }

    #[test]
    fn test_load_counters_after_2_skips() {
        // GIVEN 2 inserted skips
        let (_dir, mut persistence) = open_test_db();
        for _ in 0..2 {
            persistence
                .record_skipped(
                    TriggerRecord {
                        trigger_id: "t-skips",
                        agent_name: "agent",
                        fired_at: Utc::now(),
                        payload_json: None,
                    },
                    "busy",
                )
                .unwrap();
        }
        // WHEN
        let counters = persistence.load_counters().unwrap();
        // THEN skip_count = 2
        let stats = counters.get("t-skips").expect("trigger absent de la map");
        assert_eq!(stats.skip_count, 2);
        assert_eq!(stats.fire_count, 0);
    }

    #[test]
    fn test_load_counters_preserves_last_fired() {
        // GIVEN fires with distinct timestamps
        let (_dir, mut persistence) = open_test_db();
        let base = Utc::now();
        let t0 = base;
        let t1 = base + chrono::Duration::seconds(10);
        persistence
            .record_fired(
                TriggerRecord {
                    trigger_id: "t-last",
                    agent_name: "agent",
                    fired_at: t0,
                    payload_json: None,
                },
                "task-a",
                None,
            )
            .unwrap();
        persistence
            .record_fired(
                TriggerRecord {
                    trigger_id: "t-last",
                    agent_name: "agent",
                    fired_at: t1,
                    payload_json: None,
                },
                "task-b",
                None,
            )
            .unwrap();
        // WHEN
        let counters = persistence.load_counters().unwrap();
        // THEN last_fired = t1 (the most recent)
        let stats = counters.get("t-last").expect("trigger absent de la map");
        let last = stats.last_fired.expect("last_fired doit être Some");
        // Compare to the nearest second (RFC3339 does not preserve Utc::now sub-seconds)
        assert_eq!(last.timestamp(), t1.timestamp());
    }

    #[test]
    fn test_load_counters_new_trigger_zero() {
        // GIVEN a database with no entry for this trigger
        let (_dir, persistence) = open_test_db();
        // WHEN
        let counters = persistence.load_counters().unwrap();
        // THEN the unknown trigger is not in the map (counters at zero on the engine side)
        assert!(counters.get("non-existant").is_none());
    }

    #[test]
    fn test_load_counters_mixed_triggers() {
        // GIVEN two triggers with different histories
        let (_dir, mut persistence) = open_test_db();
        let now = Utc::now();
        // trigger-a: 5 fires, 1 skip
        for i in 0..5u64 {
            persistence
                .record_fired(
                    TriggerRecord {
                        trigger_id: "trigger-a",
                        agent_name: "agent",
                        fired_at: now + chrono::Duration::seconds(i as i64),
                        payload_json: None,
                    },
                    &format!("t{i}"),
                    None,
                )
                .unwrap();
        }
        persistence
            .record_skipped(
                TriggerRecord {
                    trigger_id: "trigger-a",
                    agent_name: "agent",
                    fired_at: now,
                    payload_json: None,
                },
                "busy",
            )
            .unwrap();
        // trigger-b: 0 fires, 3 skips
        for _ in 0..3 {
            persistence
                .record_skipped(
                    TriggerRecord {
                        trigger_id: "trigger-b",
                        agent_name: "agent",
                        fired_at: now,
                        payload_json: None,
                    },
                    "busy",
                )
                .unwrap();
        }
        // WHEN
        let counters = persistence.load_counters().unwrap();
        // THEN independent counters
        let a = counters.get("trigger-a").expect("trigger-a absent");
        assert_eq!(a.fire_count, 5);
        assert_eq!(a.skip_count, 1);
        let b = counters.get("trigger-b").expect("trigger-b absent");
        assert_eq!(b.fire_count, 0);
        assert_eq!(b.skip_count, 3);
    }

    #[test]
    fn test_error_with_payload() {
        // GIVEN an error with payload
        let (_dir, mut persistence) = open_test_db();
        // WHEN record_error with payload_json
        persistence
            .record_error(
                TriggerRecord {
                    trigger_id: "trg-6",
                    agent_name: "agent-u",
                    fired_at: Utc::now(),
                    payload_json: Some(r#"{"data":"test"}"#),
                },
                "submit failed",
            )
            .unwrap();
        // THEN payload_json is persisted
        let entries = persistence.query_history("trg-6", 10).unwrap();
        assert_eq!(
            entries[0].payload_json.as_deref(),
            Some(r#"{"data":"test"}"#)
        );
        assert!(entries[0].dispatch_ms.is_none());
    }
}
