//! Outlook Mail client (Microsoft Graph `/me/messages`).
//!
//! Free-tier scope policy: Microsoft Graph has no CASA equivalent, so the
//! full read + write surface is exposed in v0.1.0:
//! - `search` (`$search` query parameter)
//! - `get` (single message by id)
//! - `send` (compose + send in one call via `/sendMail`)
//! - `reply` (`/messages/{id}/reply`)
//! - `list_folders`
//! - `move` (`/messages/{id}/move`)

use reqwest::Method;
use serde::{Deserialize, Serialize};

use crate::{error::ConnectorError, http::HttpClient};

const GRAPH: &str = "https://graph.microsoft.com/v1.0/me";

// ─── Domain types ────────────────────────────────────────────────────────────

/// Outlook message envelope.
#[derive(Debug, Clone, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct OutlookMessage {
    /// Graph-assigned message id.
    pub id: String,
    /// Subject line.
    #[serde(default)]
    pub subject: Option<String>,
    /// Preview snippet generated by Graph.
    #[serde(default)]
    pub body_preview: Option<String>,
    /// Sender details.
    #[serde(default)]
    pub from: Option<Recipient>,
    /// Primary recipients.
    #[serde(default)]
    pub to_recipients: Vec<Recipient>,
    /// Carbon copy recipients.
    #[serde(default)]
    pub cc_recipients: Vec<Recipient>,
    /// Optional folder id.
    #[serde(default)]
    pub parent_folder_id: Option<String>,
    /// RFC 3339 received time.
    #[serde(default)]
    pub received_date_time: Option<String>,
    /// True when the message is unread.
    #[serde(default)]
    pub is_read: bool,
}

/// Recipient envelope.
#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct Recipient {
    /// Email address payload.
    #[serde(rename = "emailAddress")]
    pub email_address: EmailAddress,
}

/// `emailAddress` payload used by Graph.
#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct EmailAddress {
    /// Optional display name.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// Required address.
    pub address: String,
}

/// Outlook mail folder.
#[derive(Debug, Clone, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct MailFolder {
    /// Folder id.
    pub id: String,
    /// Folder display name.
    pub display_name: String,
    /// Total item count.
    #[serde(default)]
    pub total_item_count: Option<u32>,
    /// Unread item count.
    #[serde(default)]
    pub unread_item_count: Option<u32>,
}

/// Compose-and-send payload.
#[derive(Debug, Clone, Serialize)]
pub struct ComposeMessage {
    /// Subject.
    pub subject: String,
    /// Body (plain or HTML).
    pub body: MessageBody,
    /// Primary recipients.
    #[serde(rename = "toRecipients")]
    pub to_recipients: Vec<Recipient>,
    /// Optional CC.
    #[serde(
        default,
        rename = "ccRecipients",
        skip_serializing_if = "Vec::is_empty"
    )]
    pub cc_recipients: Vec<Recipient>,
    /// Optional BCC.
    #[serde(
        default,
        rename = "bccRecipients",
        skip_serializing_if = "Vec::is_empty"
    )]
    pub bcc_recipients: Vec<Recipient>,
}

/// Body wrapper required by Graph (`contentType` + `content`).
#[derive(Debug, Clone, Serialize)]
pub struct MessageBody {
    /// `"text"` (plain) or `"html"`.
    #[serde(rename = "contentType")]
    pub content_type: BodyContentType,
    /// Body content.
    pub content: String,
}

/// Supported body content types.
#[derive(Debug, Clone, Copy, Serialize)]
#[serde(rename_all = "lowercase")]
pub enum BodyContentType {
    /// Plain text body.
    Text,
    /// HTML body.
    Html,
}

#[derive(Debug, Serialize)]
struct SendMailEnvelope {
    message: ComposeMessage,
    #[serde(rename = "saveToSentItems")]
    save_to_sent_items: bool,
}

#[derive(Debug, Serialize)]
struct ReplyEnvelope {
    comment: String,
}

#[derive(Debug, Serialize)]
struct MoveEnvelope<'a> {
    #[serde(rename = "destinationId")]
    destination_id: &'a str,
}

#[derive(Debug, Deserialize)]
#[serde(rename_all = "camelCase")]
struct MessageList {
    value: Vec<OutlookMessage>,
}

#[derive(Debug, Deserialize)]
#[serde(rename_all = "camelCase")]
struct FolderList {
    value: Vec<MailFolder>,
}

// ─── Client ──────────────────────────────────────────────────────────────────

/// Outlook Mail client.
#[derive(Clone)]
pub struct OutlookMailClient {
    http: HttpClient,
}

impl OutlookMailClient {
    /// Build a new client.
    pub fn new(http: HttpClient) -> Self {
        Self { http }
    }

    /// Search the mailbox using Graph's `$search` query.
    ///
    /// Pass `top` to limit the result count (Graph default is 10, max 1000).
    pub async fn search<F, Fut>(
        &self,
        query: &str,
        top: u32,
        bearer: &str,
        refresh: F,
    ) -> Result<Vec<OutlookMessage>, ConnectorError>
    where
        F: FnOnce() -> Fut + Send,
        Fut: std::future::Future<Output = Result<String, ConnectorError>> + Send,
    {
        let url = format!(
            "{GRAPH}/messages?$search=\"{}\"&$top={top}",
            urlencode(query)
        );
        let resp: MessageList = self.http.get_json(&url, bearer, refresh).await?;
        Ok(resp.value)
    }

    /// Get one message by id.
    pub async fn get<F, Fut>(
        &self,
        message_id: &str,
        bearer: &str,
        refresh: F,
    ) -> Result<OutlookMessage, ConnectorError>
    where
        F: FnOnce() -> Fut + Send,
        Fut: std::future::Future<Output = Result<String, ConnectorError>> + Send,
    {
        let url = format!("{GRAPH}/messages/{message_id}");
        self.http.get_json(&url, bearer, refresh).await
    }

    /// Compose and send a new message.
    pub async fn send<F, Fut>(
        &self,
        message: ComposeMessage,
        save_to_sent_items: bool,
        bearer: &str,
        refresh: F,
    ) -> Result<(), ConnectorError>
    where
        F: FnOnce() -> Fut + Send,
        Fut: std::future::Future<Output = Result<String, ConnectorError>> + Send,
    {
        let url = format!("{GRAPH}/sendMail");
        let body = SendMailEnvelope {
            message,
            save_to_sent_items,
        };
        // sendMail returns 202 Accepted with empty body — we route through the
        // raw response path to avoid trying to decode JSON from nothing.
        self.http
            .send_with_retries(
                Method::POST,
                &url,
                Some(
                    serde_json::to_vec(&body)
                        .map_err(|e| ConnectorError::Decoding(e.to_string()))?,
                ),
                bearer,
                refresh,
            )
            .await?;
        Ok(())
    }

    /// Reply to a message. Microsoft Graph composes the reply from the
    /// original headers; we only contribute the comment / body text.
    pub async fn reply<F, Fut>(
        &self,
        message_id: &str,
        comment: &str,
        bearer: &str,
        refresh: F,
    ) -> Result<(), ConnectorError>
    where
        F: FnOnce() -> Fut + Send,
        Fut: std::future::Future<Output = Result<String, ConnectorError>> + Send,
    {
        let url = format!("{GRAPH}/messages/{message_id}/reply");
        let body = ReplyEnvelope {
            comment: comment.to_owned(),
        };
        self.http
            .send_with_retries(
                Method::POST,
                &url,
                Some(
                    serde_json::to_vec(&body)
                        .map_err(|e| ConnectorError::Decoding(e.to_string()))?,
                ),
                bearer,
                refresh,
            )
            .await?;
        Ok(())
    }

    /// List the user's mail folders.
    pub async fn list_folders<F, Fut>(
        &self,
        bearer: &str,
        refresh: F,
    ) -> Result<Vec<MailFolder>, ConnectorError>
    where
        F: FnOnce() -> Fut + Send,
        Fut: std::future::Future<Output = Result<String, ConnectorError>> + Send,
    {
        let url = format!("{GRAPH}/mailFolders");
        let resp: FolderList = self.http.get_json(&url, bearer, refresh).await?;
        Ok(resp.value)
    }

    /// Move a message to a different folder. Returns the new message id.
    pub async fn move_to<F, Fut>(
        &self,
        message_id: &str,
        destination_folder_id: &str,
        bearer: &str,
        refresh: F,
    ) -> Result<OutlookMessage, ConnectorError>
    where
        F: FnOnce() -> Fut + Send,
        Fut: std::future::Future<Output = Result<String, ConnectorError>> + Send,
    {
        let url = format!("{GRAPH}/messages/{message_id}/move");
        let body = MoveEnvelope {
            destination_id: destination_folder_id,
        };
        self.http
            .json_request(Method::POST, &url, &body, bearer, refresh)
            .await
    }
}

// ─── URL helpers ─────────────────────────────────────────────────────────────

fn urlencode(s: &str) -> String {
    let mut out = String::with_capacity(s.len() + 8);
    for c in s.chars() {
        if c.is_ascii_alphanumeric() || matches!(c, '-' | '_' | '.' | '~') {
            out.push(c);
        } else {
            for b in c.to_string().as_bytes() {
                out.push_str(&format!("%{b:02X}"));
            }
        }
    }
    out
}

// ─── Tests ───────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_compose_message_serializes_with_graph_field_names() {
        let msg = ComposeMessage {
            subject: "Hello".into(),
            body: MessageBody {
                content_type: BodyContentType::Text,
                content: "Hi".into(),
            },
            to_recipients: vec![Recipient {
                email_address: EmailAddress {
                    name: Some("Alice".into()),
                    address: "alice@example.com".into(),
                },
            }],
            cc_recipients: vec![],
            bcc_recipients: vec![],
        };
        let json = serde_json::to_value(&msg).expect("serialize");
        assert_eq!(json["subject"], "Hello");
        assert_eq!(json["body"]["contentType"], "text");
        assert_eq!(
            json["toRecipients"][0]["emailAddress"]["address"],
            "alice@example.com"
        );
        // Empty CC / BCC vectors are skipped via skip_serializing_if.
        assert!(json.get("ccRecipients").is_none());
        assert!(json.get("bccRecipients").is_none());
    }

    #[test]
    fn test_body_content_type_lowercase() {
        let body = MessageBody {
            content_type: BodyContentType::Html,
            content: "<p>hi</p>".into(),
        };
        let json = serde_json::to_value(&body).expect("serialize");
        assert_eq!(json["contentType"], "html");
    }

    #[test]
    fn test_urlencode_escapes_quotes_and_spaces() {
        assert!(urlencode("from:alice subject:hello").contains("%20"));
        assert!(urlencode("\"quoted\"").contains("%22"));
    }
}
