"""Type stubs for LlmProxy, LlmResponse, and TokenUsage.

These classes mirror the ``#[pyclass]`` / ``#[pymethods]`` definitions in
``crates/apollia-aip/src/llm.rs``.  They exist purely to provide IDE
autocompletion and ``mypy`` validation — the real implementations live in
Rust and are injected at runtime via PyO3.
"""

from __future__ import annotations

from typing import AsyncIterator, Awaitable


class TokenUsage:
    """Token consumption statistics returned by an LLM call."""

    @property
    def prompt_tokens(self) -> int:
        """Number of tokens in the prompt (input)."""
        ...

    @property
    def completion_tokens(self) -> int:
        """Number of tokens generated (output)."""
        ...

    @property
    def cost_usd(self) -> float | None:
        """Estimated cost in USD — ``None`` for local backends."""
        ...


class LlmResponse:
    """Response from an LLM completion call.

    Returned by ``ctx.llm.chat()`` and ``ctx.llm.complete()``.
    """

    @property
    def content(self) -> str:
        """Text content generated by the model."""
        ...

    @property
    def latency_ms(self) -> int:
        """Total call latency in milliseconds."""
        ...

    @property
    def usage(self) -> TokenUsage:
        """Token consumption statistics."""
        ...


class LlmProxy:
    """Bridge to the Apollia LLM router, exposed via ``ctx.llm``.

    Provides convenience methods for single-turn chat, multi-turn
    completion, streaming, and ReAct tool-use loops.
    """

    @property
    def default_backend(self) -> str:
        """Name of the default LLM backend configured in ``apollia.toml``."""
        ...

    def chat(
        self,
        system: str,
        user: str,
        backend: str | None = None,
    ) -> Awaitable[LlmResponse]:
        """Single-turn LLM call with a system prompt and user message.

        ``backend`` overrides the default backend for this call.
        """
        ...

    def complete(
        self,
        messages: list[dict[str, object]],
        backend: str | None = None,
    ) -> Awaitable[LlmResponse]:
        """Multi-turn LLM call with a full message history.

        Each message dict must have ``role`` and ``content`` keys.
        """
        ...

    def stream(
        self,
        messages: list[dict[str, object]],
        backend: str | None = None,
    ) -> Awaitable[list[str]]:
        """Streaming LLM call returning collected text chunks.

        Falls back to a single ``complete()`` call if the backend does
        not support streaming natively.

        Legacy API: chunks are buffered server-side and returned as a
        list.  Prefer ``stream_complete()`` for real token-by-token
        streaming in the ReAct loop.
        """
        ...

    def stream_complete(
        self,
        messages: list[dict[str, object]],
        backend: str | None = None,
    ) -> Awaitable[AsyncIterator[str]]:
        """Streaming LLM call returning an async iterator of chunks.

        Each chunk is yielded as soon as it arrives from the backend,
        enabling the ReAct loop to emit `ChatToken` events in real time.

        Example::

            async for chunk in await ctx.llm.stream_complete(messages):
                buffer += chunk
                await ctx.emit_token(chunk)
        """
        ...

    def run_tools(
        self,
        messages: list[dict[str, object]],
        tools: list[dict[str, object]],
        max_iterations: int = 5,
    ) -> Awaitable[str]:
        """ReAct loop: LLM -> tool(s) -> LLM -> ... -> final answer.

        ``tools`` is a list of dicts with ``name``, ``description``, and
        ``parameters`` keys.  ``max_iterations`` caps the number of LLM
        round-trips.
        """
        ...
